### ISSUE TITLE
A random crash happening to only 1 person.

### ISSUE THREAD

**Issue by jordan11v** [Alex-the-666/Ice_and_Fire#1088]
Time: 10/3/18 7:27 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.getAgeInDays(EntityDragonBase.java:545)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.getDragonStage(EntityDragonBase.java:1417)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70631_g_(EntityDragonBase.java:1440)
	at net.minecraft.entity.EntityLiving.canSkipUpdate(EntityLiving.java:1657)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:370)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1486)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.getAgeInDays(EntityDragonBase.java:545)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.getDragonStage(EntityDragonBase.java:1417)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70631_g_(EntityDragonBase.java:1440)
	at net.minecraft.entity.EntityLiving.canSkipUpdate(EntityLiving.java:1657)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:370)

My friend keeps crashing to what i believe is a dragons texture updating. Any idea on how to fix it?

**Comment by jordan11v** [comment]
Make that two people now.

**Comment by AlexModGuy** [comment]
another mod is interfering with non-vanilla property trackers. Nothing i can do about it but tell other modders not to
