### ISSUE TITLE
Server 1.12.2 forge 2806 crash

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [Alex-the-666/Ice_and_Fire#1309]
[04:48:41] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$SubList$1.checkForComodification(Unknown Source) ~[?:1.8.0_172]
	at java.util.ArrayList$SubList$1.next(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.world.chunk.Chunk.handler$getEntitiesOfTypeWithinAAAB_CubicChunks$zzh000(Chunk.java:2353) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_177430_a(Chunk.java) ~[axw.class:?]
	at net.minecraft.world.World.func_175647_a(World.java:3080) ~[amu.class:?]
	at net.minecraft.entity.ai.EntityAIAvoidEntity.func_75250_a(SourceFile:52) ~[ws.class:?]
	at com.github.alexthe666.iceandfire.entity.ai.VillagerAIFearUntamed.func_75250_a(VillagerAIFearUntamed.java:20) ~[VillagerAIFearUntamed.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[04:48:41] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: .\crash-reports\crash-2019-01-15_04.48.41-server.txt
[04:48:41] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[04:48:41] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[04:48:41] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[04:48:41] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/overworld

Crashed the server while flying a fire dragon

There are also some synchronisation issues, like you press a and fly to the opposite direction for instance.
![zrzut ekranu 290](https://user-images.githubusercontent.com/34427698/51182170-9d6c6600-18cd-11e9-9e53-7d3338248f91.png)

**Comment by AlexModGuy** [comment]
dupe #1116

**Comment by Adam-R-Kaminski** [comment]
Hmmm, but the guy on the "duplicate" report some MineColony interference and we DON'T have minecolonies installed.

**Comment by combustionsquirrel** [comment]
We're having the same issue on the server I play on as well. It's happened with death worms, hippocampi, and cockatrice. Strangely it seems to come and go; Earlier today one of my friends crashed with this error when going near my base (which has cockatrices in it), but it's not happening at the moment.
