### ISSUE TITLE
Ai Crash, possibly Dynamic Stealth

### ISSUE THREAD

**Issue by Fortist** [Alex-the-666/Ice_and_Fire#1425]
I was flying around and got this crash 
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 2019-02-19 22:06:54 EST
Description: Ticking entity

java.lang.NullPointerException
    at com.github.alexthe666.iceandfire.entity.ai.HippogryphAIAttackMelee.updateTask(HippogryphAIAttackMelee.java:111)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at com.github.alexthe666.iceandfire.entity.EntityHippogryph.onLivingUpdate(EntityHippogryph.java:714)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at com.github.alexthe666.iceandfire.entity.EntityHippogryph.onUpdate(EntityHippogryph.java:910)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zcd000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: iceandfire:hippogryph (com.github.alexthe666.iceandfire.entity.EntityHippogryph)
  Entity ID: 677
  Entity Name: Hippogryph
  Entity's Exact location: -139.46, 97.00, -656.26
  Entity's Block location: World: (-140,97,-657), Chunk: (at 4,6,15 in -9,-42; contains blocks -144,0,-672 to -129,255,-657), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
  Entity's Momentum: 0.00, -0.07, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{"naturesaura:time_alive":9793,hmag.checked:1b,"Potion Core - Health Fix":6.0f,"Potion Core - Jump Boost Updated":1b,HungerOverhaulCheck:7},Saddled:0b,RelativeAABB:[-0.8500000238419148d,0.0d,-0.8500000238418579d,0.8500000238419148d,1.600000023841858d,0.8500000238418579d],Sitting:0b,Attributes:[{Base:100.0d,Name:"dynamicstealth.visibilityReduction"},{Base:100.0d,Name:"dynamicstealth.sight"},{Base:100.0d,Name:"dynamicstealth.noiseReduction"},{Base:100.0d,Name:"dynamicstealth.hearing"},{Base:100.0d,Name:"dynamicstealth.scentReduction"},{Base:100.0d,Name:"dynamicstealth.smelling"},{Base:1.0d,Name:"potioncore.projectileDamage"},{Base:1.0d,Name:"potioncore.magicDamage"},{Base:1.0d,Name:"potioncore.jumpHeight"},{Base:1.0d,Name:"potioncore.damageResistance"},{Base:0.0d,Name:"potioncore.magicShielding"},{Base:40.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.3d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:32.0d,Modifiers:[{UUIDMost:-8793972406527176755L,UUIDLeast:-7858974071737364510L,Amount:0.019430871812635243d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:5.0d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,Hovering:0b,FallDistance:0.0f,InLove:0,DeathTime:0s,Armor:0,ForgeCaps:{"colytra:colytraflying":{colytra_flying:0b},"bettercombatmod:ioffhandattack":0,"dsurround:data":{a:0b,f:0b},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:1},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"multimob:summonable":{SummonerUUID:"",Following:0b,TimeLimit:1000},"bettercombatmod:isecondhurttimer":0,"enderutilities:entity_portal_cooldown":{LastInPortal:0L},"somanyenchantments:player_capabilities":{isResurrecting:0b,moralitasDamage:0.0d}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Items:[],Age:0,Motion:[0.0d,-0.06840000152587891d,0.0d],Leashed:0b,UUIDLeast:-4754295631783235551L,Health:6.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[61.697006f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],HasHomePosition:0b,Variant:1,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],OwnerUUID:"",Flying:1b,UUIDMost:1640425197547701730L,Pos:[-139.45917307342344d,97.0d,-656.2621173019794d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s,Chested:0b}
```

I think it could possibly be Dynamic Stealth, as it only happens when that mod is added, and I havent at least crashed without it.

**Comment by Laike-Endaril** [comment]
Hey, I'm the DS dev.  This is a fairly common issue, so I already knew the cause when it was posted on my end.

The short of it is that dynamic stealth is not compatible with AI tasks that reference the entity's attack target without checking it for null first, eg. this line:
https://github.com/Alex-the-666/Ice_and_Fire/blob/1d7153ffdf53f10dbfadc7f804ee169eae0737f7/src/main/java/com/github/alexthe666/iceandfire/entity/ai/HippogryphAIAttackMelee.java#L111

entitylivingbase on that line is null, due to a very complex reason which I can explain if need be.

In any case, I already have a filter set up to handle this type of thing and will add entries to it for Ice and Fire mobs for now, but it's not super efficient, so if you end up changing the AI so it checks the attack target for null first, please tell me so I can remove the filtering

**Comment by Laike-Endaril** [comment]
Update; just finished looking through all your AI classes to do my filtering correctly; 
I believe the only problematic ones are DragonAIAttackMelee, HippogryphAIAttackMelee, and SeaSerpentAIAttackMelee, so I'll put those into my filter for now.
