### ISSUE TITLE
Crash while loading pixie house

### ISSUE THREAD

**Issue by Ag1Nt** [Alex-the-666/Ice_and_Fire#1431]
When I load the game it's fine, as soon as I open the "ice and fire" tab in creative mode I crash, the crash report report's it being caused by the pixie house not loading

Time: 2/24/19 7:40 PM
Description: Rendering item

java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/client/util/ItemTESRContext
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:46)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)
	at net.minecraftforge.client.ForgeHooksClient.renderTileItem(ForgeHooksClient.java:568)
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_192838_a(TileEntityItemStackRenderer.java:121)
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java:45)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:140)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:303)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.client.util.ItemTESRContext
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
Caused by: java.lang.NullPointerException

That is part of the crash report if you want more of it please let me know

**Comment by AlexModGuy** [comment]
what version of LLibrary were you using?

**Comment by Ag1Nt** [comment]
I was using the latest version I could fine, after poking around a bit I
found a newer version that fixed the issue
