### ISSUE TITLE
Hippogryphs Buggy?

### ISSUE THREAD

**Issue by RaineDash** [Alex-the-666/Ice_and_Fire#1474]
My game crashes when I attempt to load into my server. This was the crash report that seemed most relevant.

PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.up(EntityHippogryph.java:305)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:914)

**Comment by AlexModGuy** [comment]
see #728 

basically, mod conflict with another mod not doing its job and assigning values to joppoggryphs
