### ISSUE TITLE
Sea Serpent Bubble Crashes Game

### ISSUE THREAD

**Issue by redknight378** [Alex-the-666/Ice_and_Fire#1537]
Sea Serpents using their Bubble attack logs me out of the world and crashed Minecraft. This issue is on every world I test it out on. The entity itself is fine and works, until it uses the bubble attack. 

Time: 4/17/19 10:56 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.EntityDamageSource.func_188404_v(SourceFile:60)
	at thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_564_EntityWeedwoodRowboat_onLivingAttacked_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:850)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.minecraft.entity.monster.EntityGuardian.func_70097_a(SourceFile:342)
	at com.github.alexthe666.iceandfire.entity.EntitySeaSerpentBubbles.func_70227_a(EntitySeaSerpentBubbles.java:112)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at com.github.alexthe666.iceandfire.entity.EntitySeaSerpentBubbles.func_70071_h_(EntitySeaSerpentBubbles.java:49)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.util.EntityDamageSource.func_188404_v(SourceFile:60)
	at thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_564_EntityWeedwoodRowboat_onLivingAttacked_LivingAttackEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:850)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.minecraft.entity.monster.EntityGuardian.func_70097_a(SourceFile:342)
	at com.github.alexthe666.iceandfire.entity.EntitySeaSerpentBubbles.func_70227_a(EntitySeaSerpentBubbles.java:112)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at com.github.alexthe666.iceandfire.entity.EntitySeaSerpentBubbles.func_70071_h_(EntitySeaSerpentBubbles.java:49)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:seaserpentbubble (com.github.alexthe666.iceandfire.entity.EntitySeaSerpentBubbles)
	Entity ID: 9397
	Entity Name: entity.seaserpentbubble.name
	Entity's Exact location: 1936.01, 44.81, 779.67
	Entity's Block location: World: (1936,44,779), Chunk: (at 0,2,11 in 121,48; contains blocks 1936,0,768 to 1951,255,783), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
	Entity's Momentum: -0.22, -0.36, -0.52
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

Hopefully that is enough.

**Comment by ZeekDaGeek** [comment]
I'm receiving a similar bubble crash that's taking down my whole server:

https://gist.github.com/ZeekDaGeek/0223a7140425e38c55c0029f50b955c9

**Comment by ZeekDaGeek** [comment]
One of the worst things about the bug is there's no way to disable Sea Serpents or any specific entity, you can only disable their spawning so it essentially corrupts the world, with no way to fix it.

**Comment by AlexModGuy** [comment]
thebetweenlands.common.entity.rowboat.EntityWeedwoodRowboat.onLivingAttacked(EntityWeedwoodRowboat.java:1027)

issue with betweenlands

**Comment by BluePhoenix0120** [comment]
im having this issue  but i am not using betweenlands
