### ISSUE TITLE
Console Flood - hippogryph egg

### ISSUE THREAD

**Issue by Zentraxius** [Alex-the-666/Ice_and_Fire#1549]
[02:38:27] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name bakingEgg has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemHippogryphEgg) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!
[02:38:27] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:679)
[02:38:27] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[02:38:27] [Server thread/WARN] [FML]: *  at com.github.alexthe666.iceandfire.core.ModRecipes.preInit(ModRecipes.java:80)
[02:38:27] [Server thread/WARN] [FML]: *  at com.github.alexthe666.iceandfire.IceAndFire.preInit(IceAndFire.java:86)
[02:38:27] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:38:27] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
[02:38:27] [Server thread/WARN] [FML]: ****************************************
[02:38:27] [Server thread/WARN] [FML]: ****************************************

**Comment by SokyranTheDragon** [comment]
Duplicate of #1517, #1520, #1521, #1529.

Should be fixed by #1550

**Comment by AlexModGuy** [comment]
fixed
