### ISSUE TITLE
Crash due to compatibility error with Betteranimalsplus.

### ISSUE THREAD

**Issue by PeppeJ** [Alex-the-666/Ice_and_Fire#1611]
**Describe what you were doing before the crash**
(compatibility error with Betteranimalsplus 6.0.3)
Exploring near an ice and fire dragon. I posted this on Betteranimalsplus issuetracker as well, not sure which mod is at fault.

Betteranimalsplus dev is @itsmeow

**To Reproduce** (Required unless unknown)
Steps to reproduce the behavior (if possible):
1. Have an enemy ice and fire dragon alive.
2. Chill near it for a bit.
3. Crash

**Crash Log (REQUIRED)**
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2019-07-07 06:30:30 CEST
Description: Ticking entity

java.lang.NullPointerException
    at its_meow.betteranimalsplus.util.HeadTypes.getItem(HeadTypes.java:104)
    at its_meow.betteranimalsplus.common.entity.EntityDeer.onDeath(EntityDeer.java:89)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(SourceFile:66)
    at com.github.alexthe666.iceandfire.entity.FireExplosion.doExplosionA(FireExplosion.java:145)
    at com.github.alexthe666.iceandfire.entity.EntityDragonFire.onImpact(EntityDragonFire.java:80)
    at net.minecraft.entity.projectile.EntityFireball.onUpdate(EntityFireball.java:98)
    at com.github.alexthe666.iceandfire.entity.EntityDragonFire.onUpdate(EntityDragonFire.java:49)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zzj000(World.java:4118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: iceandfire:dragonfire (com.github.alexthe666.iceandfire.entity.EntityDragonFire)
  Entity ID: 486018
  Entity Name: Dragon Fire
  Entity's Exact location: -192.49, 74.28, -44.85
  Entity's Block location: World: (-193,74,-45), Chunk: (at 15,4,3 in -13,-3; contains blocks -208,0,-48 to -193,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Entity's Momentum: -1.22, -8.43, -1.19
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[-1.215184276786421d,-8.426560878848262d,-1.188772729952345d],ForgeData:{"roughmobs:featuresApplied":1b},UUIDLeast:-8605616081709213706L,RelativeAABB:[-0.6499999761581421d,0.0d,-0.6499999761581421d,0.6499999761581421d,1.2999999523162842d,0.6499999761581421d],Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[24.441137f,38.700783f],UpdateBlocked:0b,life:0,FallDistance:0.0f,UUIDMost:4041602936081564569L,Pos:[-192.48610166830625d,74.28306659247352d,-44.85408750754031d],Fire:-1s,ForgeCaps:{"llibrary:extendedentitydatacapability":{}},power:[-0.28272183969781034d,-1.9605033076084646d,-0.276576992983745d],direction:[-1.215184276786421d,-8.426560878848262d,-1.188772729952345d]}

-- Affected level --
  Level name: world2
  All players: 3 total; [EntityPlayerMP['u80a'/5053, l='world2', x=-102.70, y=63.56, z=58.70], EntityPlayerMP['Davvid93'/5052, l='world2', x=-99.33, y=10.00, z=-138.47], EntityPlayerMP['PeppeJ'/480299, l='world2', x=-99.07, y=63.00, z=43.96]]
  Chunk stats: ServerChunkCache: 1138 Drop: 0
  Level seed: 12341234
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-164,64,252), Chunk: (at 12,4,12 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 481645 game time, 497151 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 72063 (now: false), thunder time: 15583 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows Server 2016 (amd64) version 10.0
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3290550296 bytes (3138 MB) / 5247598592 bytes (5004 MB) up to 5247598592 bytes (5004 MB)
  JVM Flags: 2 total; -Xms2G -Xmx5G
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 110 mods loaded, 110 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                              | Version                  | Source                                               | Signature                                |
       |:------ |:------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                       | 1.12.2                   | minecraft.jar                                        | None                                     |
       | LCHIJA | mcp                             | 9.42                     | minecraft.jar                                        | None                                     |
       | LCHIJA | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                           | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ivtoolkit                       | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
       | LCHIJA | foamfixcore                     | 7.7.4                    | minecraft.jar                                        | None                                     |
       | LCHIJA | dsurroundcore                   | 3.5.4.3                  | minecraft.jar                                        | None                                     |
       | LCHIJA | randompatches                   | 1.12.2-1.17.2.0          | randompatches-1.12.2-1.17.2.0.jar                    | None                                     |
       | LCHIJA | aiimprovements                  | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                      | None                                     |
       | LCHIJA | anvilfix                        | 1.0.3                    | AnvilFix-1.12.2-1.0.3.jar                            | None                                     |
       | LCHIJA | jei                             | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
       | LCHIJA | appleskin                       | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
       | LCHIJA | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
       | LCHIJA | chisel                          | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
       | LCHIJA | tconstruct                      | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                     | None                                     |
       | LCHIJA | thedragonlib                    | 1.12.2-5.3.0             | thedragonlib-1.12.2-5.3.0.jar                        | None                                     |
       | LCHIJA | armorplus                       | 1.12.2-11.24.0.60        | armorplus-1.12.2-11.24.0.60.jar                      | None                                     |
       | LCHIJA | conarm                          | 1.2.4                    | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | armoryexpansion                 | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCHIJA | armoryexpansion-custommaterials | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCHIJA | llibrary                        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                      | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                          | None                                     |
       | LCHIJA | armoryexpansion-iceandfire      | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCHIJA | armoryexpansion-matteroverdrive | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCHIJA | attributefix                    | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | quark                           | r1.5-167                 | Quark-r1.5-167.jar                                   | None                                     |
       | LCHIJA | autoreglib                      | 1.3-31                   | AutoRegLib-1.3-31.jar                                | None                                     |
       | LCHIJA | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCHIJA | bedrockbgone                    | 5.0.8                    | BedrockBGone-1.12.2-5.0-b8.jar                       | None                                     |
       | LCHIJA | betteranimalsplus               | 6.0.3                    | betteranimalsplus-1.12.2-6.0.3.jar                   | None                                     |
       | LCHIJA | bibliocraft                     | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
       | LCHIJA | biomesoplenty                   | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar        | None                                     |
       | LCHIJA | bloodmoon                       | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | chameleon                       | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
       | LCHIJA | charm                           | 1.12.2-1.1.14            | Charm-1.12.2-1.1.14.jar                              | None                                     |
       | LCHIJA | chiselsandbits                  | 14.33                    | chiselsandbits-14.33.jar                             | None                                     |
       | LCHIJA | chunkpregenerator               | 2.1                      | Chunk Pregenerator V1.12-2.1.jar                     | None                                     |
       | LCHIJA | storagedrawers                  | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                      | None                                     |
       | LCHIJA | compactdrawers                  | 1.12.2-1.0.5.121         | CompactDrawers-1.12.2-1.0.5.121.jar                  | None                                     |
       | LCHIJA | cookingforblockheads            | 6.4.71                   | CookingForBlockheads_1.12.2-6.4.71.jar               | None                                     |
       | LCHIJA | cosmeticarmorreworked           | 1.12.2-v4a               | CosmeticArmorReworked-1.12.2-v4a.jar                 | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | craftingtweaks                  | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                      | None                                     |
       | LCHIJA | customspawner                   | 3.11.4                   | CustomMobSpawner-3.11.4.jar                          | None                                     |
       | LCHIJA | orespawn                        | 3.3.1                    | OreSpawn-1.12-3.3.1.172.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | densemetals                     | 1.2.0                    | DenseMetals-1.12-1.2.0.21.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | dldungeonsjbg                   | 1.12.5                   | DoomlikeDungeons-1.12.5-MC1.12.2.jar                 | None                                     |
       | LCHIJA | mocreatures                     | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar                  | None                                     |
       | LCHIJA | thaumcraft                      | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
       | LCHIJA | dungeonmobs                     | 5.7.2                    | dungeonmobs-5.7.2-MC1.12.2.jar                       | None                                     |
       | LCHIJA | fastfurnace                     | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                         | None                                     |
       | LCHIJA | fastleafdecay                   | v14                      | FastLeafDecay-v14.jar                                | None                                     |
       | LCHIJA | fastbench                       | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                       | None                                     |
       | LCHIJA | foamfix                         | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                            | None                                     |
       | LCHIJA | forgelin                        | 1.8.3                    | Forgelin-1.8.3.jar                                   | None                                     |
       | LCHIJA | ftblib                          | 5.4.3.126                | FTBLib-5.4.3.126.jar                                 | None                                     |
       | LCHIJA | ftbutilities                    | 5.4.0.100                | FTBUtilities-5.4.0.100.jar                           | None                                     |
       | LCHIJA | ftbbackups                      | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.4.jar                      | None                                     |
       | LCHIJA | gravestone                      | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar                   | None                                     |
       | LCHIJA | grimoireofgaia                  | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                   | None                                     |
       | LCHIJA | hardcoredarkness                | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | harvest                         | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                            | None                                     |
       | LCHIJA | waila                           | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
       | LCHIJA | ichunutil                       | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | infernalmobs                    | 1.7.6                    | InfernalMobs-1.12.1.jar                              | None                                     |
       | LCHIJA | inventorytweaks                 | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest                       | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar                      | None                                     |
       | LCHIJA | jepb                            | 1.2.1                    | jepb-1.12-1.2.1.jar                                  | None                                     |
       | LCHIJA | journeymap                      | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                          | None                                     |
       | LCHIJA | jaff                            | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                        | None                                     |
       | LCHIJA | kleeslabs                       | 5.4.12                   | KleeSlabs_1.12.2-5.4.12.jar                          | None                                     |
       | LCHIJA | lex                             | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                               | None                                     |
       | LCHIJA | login_shield                    | 1.12.2-3-g7c6e7ac        | Login_Shield-1.12.2-3-g7c6e7ac.jar                   | None                                     |
       | LCHIJA | lootbags                        | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                          | None                                     |
       | LCHIJA | lunatriuscore                   | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar          | None                                     |
       | LCHIJA | magma_monsters                  | 0.3.0                    | MagmaMonsters-0.3.0.jar                              | None                                     |
       | LCHIJA | mmdlib                          | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                         | None                                     |
       | LCHIJA | mowziesmobs                     | 1.5.4                    | mowziesmobs-1.5.4.jar                                | None                                     |
       | LCHIJA | natura                          | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                           | None                                     |
       | LCHIJA | naturalnetherportals            | 1.2.0                    | naturalnetherportals-1.2.0-mc1.12.x.jar              | None                                     |
       | LCHIJA | nex                             | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                            | None                                     |
       | LCHIJA | nethermetals                    | 1.2.0-rc2                | NetherMetals-1.12-1.2.0-rc2.76.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | netherportalfix                 | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                    | None                                     |
       | LCHIJA | samsocean                       | 1.0.2                    | OceanFloor-1.12.2-1.0.2.jar                          | None                                     |
       | LCHIJA | openglider                      | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                          | None                                     |
       | LCHIJA | getalltheseeds                  | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar                   | None                                     |
       | LCHIJA | harvestcraft                    | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar | None                                     |
       | LCHIJA | placebo                         | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                             | None                                     |
       | LCHIJA | quarkoddities                   | 1                        | QuarkOddities-1.12.2.jar                             | None                                     |
       | LCHIJA | randomtweaks                    | 1.12.2-2.6.0.0           | randomtweaks-1.12.2-2.6.0.0.jar                      | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCHIJA | reccomplex                      | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                         | None                                     |
       | LCHIJA | roughmobs                       | 2.0.0                    | roughmobs2-1.12.2_2.0.15.jar                         | None                                     |
       | LCHIJA | sereneseasons                   | 1.2.16                   | SereneSeasons-1.12.2-1.2.16-universal.jar            | None                                     |
       | LCHIJA | specialai                       | 1.1.0_for_mc1.12.2       | specialai-1.1.0_for_mc1.12.2.jar                     | None                                     |
       | LCHIJA | specialmobs                     | 1.0.2_for_mc1.12.2       | specialmobs-1.0.2_for_mc1.12.2.jar                   | None                                     |
       | LCHIJA | stackie                         | 1.6.0.48                 | Stackie-1.12.2-1.6.0.48-universal.jar                | None                                     |
       | LCHIJA | stg                             | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                 | None                                     |
       | LCHIJA | storagedrawersunlimited         | 1.12.2-1.3.0             | StorageDrawersUnlimited-1.12.2-1.3.0.jar             | None                                     |
       | LCHIJA | stygian                         | 1.0.4                    | stygian-1.0.4.jar                                    | None                                     |
       | LCHIJA | tcinventoryscan                 | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar           | None                                     |
       | LCHIJA | thaumictinkerer                 | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar               | None                                     |
       | LCHIJA | tcomplement                     | 1.12.2-0.4.2             | TinkersComplement-1.12.2-0.4.2.jar                   | None                                     |
       | LCHIJA | vanillafix                      | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                             | None                                     |
       | LCHIJA | waddles                         | 0.6.0                    | Waddles-1.12.2-0.6.0.jar                             | None                                     |
       | LCHIJA | waim                            | 1.0.0                    | WAIM-1.0.0.jar                                       | None                                     |
       | LCHIJA | wawla                           | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | xtones                          | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                             | None                                     |
       | LCHIJA | orelib                          | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                       | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | phosphor-lighting               | 1.12.2-0.2.4             | phosphor-1.12.2-0.2.4+build46-universal.jar          | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | armoryexpansion-conarm          | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.17.2.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CharmLoadingPlugin (Charm-1.12.2-1.1.14.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Quark Plugin (Quark-r1.5-167.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - craftingtweaksIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
                               - craftingtweaksIntegration (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  Suspected Mods: Better Animals+ (betteranimalsplus), Ice and Fire (iceandfire)
  Profiler Position: N/A (disabled)
  Player Count: 3 / 8; [EntityPlayerMP['u80a'/5053, l='world2', x=-102.70, y=63.56, z=58.70], EntityPlayerMP['Davvid93'/5052, l='world2', x=-99.33, y=10.00, z=-138.47], EntityPlayerMP['PeppeJ'/480299, l='world2', x=-99.07, y=63.00, z=43.96]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
```

**Versions:**
 - Forge Version: 14.23.5.2838
 - MC Version: 1.12.2
 - Mod Version: 1.7.1

**Comment by itsmeow** [comment]
Hey, BA+ dev here,
This is a BA+ issue, feel free to close.

**Comment by PeppeJ** [comment]
Got it.

**Comment by PeppeJ** [comment]
Got it.
