### ISSUE TITLE
Broken ore dictionary registration for Silver ingots and nuggets

### ISSUE THREAD

**Issue by SnaveSutit** [Alex-the-666/Ice_and_Fire#1669]
[21:32:27] [Client thread/WARN]: ****************************************
[21:32:27] [Client thread/WARN]: * A broken ore dictionary registration with name ingotSilver has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemGeneric) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!
[21:32:27] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:679)
[21:32:27] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[21:32:27] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:649)
[21:32:27] [Client thread/WARN]: *  at com.github.alexthe666.iceandfire.core.ModRecipes.preInit(ModRecipes.java:54)
[21:32:27] [Client thread/WARN]: *  at com.github.alexthe666.iceandfire.IceAndFire.preInit(IceAndFire.java:86)
[21:32:27] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[21:32:27] [Client thread/WARN]: ****************************************
[21:32:27] [Client thread/WARN]: ****************************************
[21:32:27] [Client thread/WARN]: * A broken ore dictionary registration with name nuggetSilver has occurred. It adds an item (type: class com.github.alexthe666.iceandfire.item.ItemGeneric) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Ice and Fire report it to them!
[21:32:27] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:679)
[21:32:27] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:651)
[21:32:27] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:649)
[21:32:27] [Client thread/WARN]: *  at com.github.alexthe666.iceandfire.core.ModRecipes.preInit(ModRecipes.java:55)
[21:32:27] [Client thread/WARN]: *  at com.github.alexthe666.iceandfire.IceAndFire.preInit(IceAndFire.java:86)
[21:32:27] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[21:32:27] [Client thread/WARN]: ****************************************

Idk if you need any extra information, but it said report it so I thought there's no harm in reporting it ;)

**Comment by SnaveSutit** [comment]
This is also preventing me from using Unidict to combine multiple mods versions of silver

**Comment by SnaveSutit** [comment]
[log_cut.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/3487652/log_cut.txt)

**Comment by BugmanBugman** [comment]
This is a dupe, please close

**Comment by SnaveSutit** [comment]
My apologies! I searched beforehand and didn't find anything.
