### ISSUE TITLE
Server Console Spam

### ISSUE THREAD

**Issue by PlatinumFox** [Alex-the-666/Ice_and_Fire#1705]
[18:45:14] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id minecraft:dragonforge
[18:45:18] [Server thread/ERROR] [minecraft/TileEntity]: Failed to create block entity minecraft:dragonforge
java.lang.NullPointerException: null
        at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforge.<init>(TileEntityDragonforge.java:45) ~[TileEntityDragonforge.class:?]
        at sun.reflect.GeneratedConstructorAccessor146.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.tileentity.TileEntity.create(TileEntity.java:105) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[18:45:18] [Server thread/ERROR] [FML]: A TileEntity minecraft:dragonforge(com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforge) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: null
        at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforge.<init>(TileEntityDragonforge.java:45) ~[TileEntityDragonforge.class:?]
        at sun.reflect.GeneratedConstructorAccessor146.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.tileentity.TileEntity.create(TileEntity.java:105) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by PlatinumFox** [comment]
over and over and over again

**Comment by RivaHakushia** [comment]
I am also getting this with my Modpack server - http://prntscr.com/os7t2l
