### ISSUE TITLE
Wyvern Dimension Crashes

### ISSUE THREAD

**Issue by Vahlmira** [Alex-the-666/Ice_and_Fire#1762]
So, in the current crash report for my server, when I try to join the Wyvern Dimension from Mo' Creatures, it brings up Ice and Fire. I don't know why and I even changed the tick to -1 to completely disable the Max-Tick-Time, but that still doesn't seem to work. I went to my console to even try and kill myself so I could respawn out of the dimension, but now my respawn button doesn't work, only my title button. This worked once before and I don't know why it's doing this now. This is the current crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.5-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/19/19 1:41 PM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at com.github.alexthe666.iceandfire.structures.WorldGenRoostArch.generate(WorldGenRoostArch.java:37)
	at com.github.alexthe666.iceandfire.structures.WorldGenFireDragonRoosts.func_180709_b(WorldGenFireDragonRoosts.java:108)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:107)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at com.github.alexthe666.iceandfire.structures.WorldGenRoostArch.generate(WorldGenRoostArch.java:37)
	at com.github.alexthe666.iceandfire.structures.WorldGenFireDragonRoosts.func_180709_b(WorldGenFireDragonRoosts.java:108)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:107)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

-- Thread Dump --
Details:
	Threads: "Netty Epoll Server IO #4" Id=56 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"Netty Epoll Server IO #3" Id=55 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"pool-3-thread-1" Id=54 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@677b518a
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@677b518a
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-6-thread-1" Id=53 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@69bca315
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@69bca315
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"Chunk I/O Executor Thread-1" Id=51 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6d833afa
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6d833afa
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Netty Epoll Server IO #2" Id=47 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"threadDeathWatcher-2-1" Id=46 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

"Netty Epoll Server IO #1" Id=45 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"File IO Thread" Id=44 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
	at java.lang.Thread.run(Thread.java:748)

"Java2D Disposer" Id=42 WAITING on java.lang.ref.ReferenceQueue$Lock@2881a92e
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@2881a92e
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:748)

"Armourer's Workshop Server Skin Thread" Id=41 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at moe.plushie.armourers_workshop.common.skin.cache.CommonSkinCache.run(CommonSkinCache.java:84)
	at java.lang.Thread.run(Thread.java:748)

"Server Watchdog" Id=40 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:45)
	at java.lang.Thread.run(Thread.java:748)

"Netty Epoll Server IO #0" Id=38 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

"Server console handler" Id=21 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	-  locked java.io.BufferedInputStream@15cb4ab5
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	-  locked java.io.InputStreamReader@1963e712
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	...

"DestroyJavaVM" Id=20 RUNNABLE

"Server thread" Id=18 RUNNABLE
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at com.github.alexthe666.iceandfire.structures.WorldGenRoostArch.generate(WorldGenRoostArch.java:37)
	at com.github.alexthe666.iceandfire.structures.WorldGenFireDragonRoosts.func_180709_b(WorldGenFireDragonRoosts.java:108)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:107)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	...

"Server Infinisleeper" Id=17 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:82)

"Snooper Timer" Id=16 RUNNABLE (in native)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	-  locked java.net.SocksSocketImpl@6dc35a2e
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	...

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@1220fa9
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@1220fa9
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@76c73789
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@76c73789
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:62)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-957.1.3.el7.x86_64
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2443369592 bytes (2330 MB) / 4294443008 bytes (4095 MB) up to 4294443008 bytes (4095 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 92
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 42 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                | Source                                                | Signature                                |
	|:------ |:------------------- |:---------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                 | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                 | 9.42                   | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                 | 8.0.99.99              | forge1122.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838           | forge1122.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ageofweapons        | 0.13.5                 | Age+of+Weapons+1.12.2++(v.0.13.5).jar                 | None                                     |
	| LCHIJA | armourers_workshop  | 1.12.2-0.49.1          | Armourers-Workshop-1.12.2-0.49.1.jar                  | None                                     |
	| LCHIJA | astikorcarts        | 1.12.2-0.1.2.7         | astikorcarts-1.12.2-0.1.2.7.jar                       | None                                     |
	| LCHIJA | baubles             | 1.5.2                  | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCHIJA | patchouli           | 1.0-20                 | Patchouli-1.0-20.jar                                  | None                                     |
	| LCHIJA | bewitchment         | 0.20.6                 | bewitchment-1.12.2-0.0.20.6.jar                       | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5                  | BiblioCraft[v2.4.5][MC1.12.2].jar                     | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2441             | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar         | None                                     |
	| LCHIJA | guideapi            | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                           | None                                     |
	| LCHIJA | bloodmagic          | 1.12.2-2.4.1-103       | BloodMagic-1.12.2-2.4.1-103.jar                       | None                                     |
	| LCHIJA | botania             | r1.10-361              | Botania+r1.10-361.jar                                 | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                              | None                                     |
	| LCHIJA | customspawner       | 3.11.4                 | Custom-Mob-Spawner-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | mocreatures         | 12.0.5                 | DrZharks MoCreatures Mod-12.0.5.jar                   | None                                     |
	| LCHIJA | forbidden_arcanus   | 1.12.2-1.1.4           | forbidden_arcanus-1.12.2-1.1.4.jar                    | None                                     |
	| LCHIJA | llibrary            | 1.7.19                 | llibrary-1.7.19-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire          | 1.8.0                  | iceandfire-1.8.0.jar                                  | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844      | ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
	| LCHIJA | malisiscore         | 1.12.2-6.5.1-SNAPSHOT  | malisiscore-1.12.2-6.5.1.jar                          | None                                     |
	| LCHIJA | malisisdoors        | 1.12.2-7.3.0           | malisisdoors-1.12.2-7.3.0.jar                         | None                                     |
	| LCHIJA | radixcore           | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                  | None                                     |
	| LCHIJA | mca                 | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                        | None                                     |
	| LCHIJA | moreplayermodels    | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                  | None                                     |
	| LCHIJA | travellersbackpack  | 1.0.19.19              | TravellersBackpack-1.12.2-1.0.19.19.jar               | None                                     |
	| LCHIJA | twilightforest      | 3.8.689                | twilightforest-1.12.2-3.8.689-universal.jar           | None                                     |
	| LCHIJA | veinminer           | 0.38.2                 | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                 | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| LCHIJA | waystones           | 4.0.72                 | Waystones_1.12.2-4.0.72.jar                           | None                                     |
	| LCHIJA | wings               | 1.1.5                  | wings-1.1.5-1.12.2.jar                                | None                                     |
	| LCHIJA | bauble_wings        | 1.0.0                  | wings-1.1.5-1.12.2.jar                                | None                                     |
	| LCHIJA | drplibrary          | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.034240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmmaarg          | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.074036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmguis           | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.120253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmlocks          | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.111203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcore             | 1.12.2-0.4.7           | drpcore-1.12.2-0.4.7.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpmedieval         | 1.12.2-0.3.5           | drpmedieval-1.12.2-0.3.5.jar                          | None                                     |
	| LCHIJA | drpcmblueprints     | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UD     | mobends_wings       | 1.0.0                  | wings-1.1.5-1.12.2.jar                                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.5-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 1 / 50; [EntityPlayerMP['Vahlmira'/4105, l='Please Work', x=0.00, y=69.00, z=0.00]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

And if this also helps, it says this from console when I log back into my server in the Wyvern Dimension. I removed Aether and every file there was before I even tried testing the Wyvern Dimension and it is bringing this up:

19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDamageLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.pierceDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.impactDefenseLevel'
19.08 14:37:31 [Server] Server thread/WARN [minecraft/SharedMonsterAttributes]: Ignoring unknown attribute 'aether.slashDamageLevel'

**Comment by Vahlmira** [comment]
You know, I know the title had nothing to do with the mod, but the crash
report does. I am using both Ice and Fire and Mo' Creatures in my modpack
and for some reason, it brings up Ice and Fire in the crash report, but I
don't know what the core issue could be with it corrupting the world. I
would really appreciate it if you guys could help me with this problem and
not just delete my issue.

>

**Comment by AlexModGuy** [comment]
" @Alex-the-666 Alex-the-666 closed this in 25a5b19 7 minutes ago"

I fixed the bug. that is what this means. The crash will not be present in 1.8.1.

**Comment by Vahlmira** [comment]
Do you at least have insight on how to fix my respawn button? I could not
make it crash till the time being when you update the mod again. My respawn
button doesn’t work and I’m stuck in the dimension and can’t get out. Only
my title button works. Sorry I’m bothering you about another mod, but
there’s no GitHub for it.

**Comment by BugmanBugman** [comment]
1.8.1 is around the corner, just try to hold on for a lil longer. Unfortunately mo creatures tends to be a lil incompatible..

**Comment by Vahlmira** [comment]
Oh trust me, I know. But yours and Mo’ Creatures have always been my
favorite mods. Thank you guys for the input though.
