### ISSUE TITLE
ContainerHorseChest crash

### ISSUE THREAD

**Issue by GodHenko** [Alex-the-666/Ice_and_Fire#1830]
java.lang.NoSuchMethodError: net.minecraft.inventory.ContainerHorseChest.<init>(Ljava/lang/String;I)V
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.initDragonInv(EntityDragonBase.java:348)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.<init>(EntityDragonBase.java:194)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.<init>(EntityFireDragon.java:41)
	at com.github.alexthe666.iceandfire.structures.WorldGenFireDragonRoosts.func_180709_b(WorldGenFireDragonRoosts.java:114)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:107)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1155)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1113)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:163)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:491)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:457)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
	at java.lang.Thread.run(Thread.java:748)

**Comment by FrostDrago** [comment]
"Without any more information it is difficult to pinpoint the problem, but the root cause is that you most likely have compiled a class against a different version of the class that is missing a method, than the one you are using when running it.

Look at the stack trace ... If the exception appears when calling a method on an object in a library, you are most likely using separate versions of the library when compiling and running. Make sure you have the right version both places.

If the exception appears when calling a method on objects instantiated by classes you made, then your build process seems to be faulty. Make sure the class files that you are actually running are updated when you compile."

An answer i found on another source.
==> https://stackoverflow.com/questions/35186/how-do-i-fix-a-nosuchmethoderror
