### ISSUE TITLE
Crashing everytime i tried to wear sea serpent armor and crashing everytime i tried to summon queen wyrmx

### ISSUE THREAD

**Issue by HansenND** [Alex-the-666/Ice_and_Fire#1849]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 9/14/19 11:52 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_99_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:580)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at DamageIndicatorsMod.core.DIEventBus.livingEvent(DIEventBus.java:229)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_99_DIEventBus_livingEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:580)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 1720
	Entity Name: HansenND
	Entity's Exact location: 214.84, 87.74, 257.18
	Entity's Block location: World: (214,87,257), Chunk: (at 6,5,1 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HansenND'/1720, l='MpServer', x=214.84, y=87.74, z=257.18]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (212,64,256), Chunk: (at 4,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 939 game time, 939 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 39 total; [EntityCreeper['Creeper'/2116, l='MpServer', x=189.40, y=30.00, z=234.81], EntityTroll['Troll'/2117, l='MpServer', x=188.50, y=30.00, z=216.50], EntityWitch['Witch'/2119, l='MpServer', x=183.50, y=40.00, z=248.50], EntityBat['Bat'/2127, l='MpServer', x=194.80, y=38.61, z=213.96], EntitySkeleton['Skeleton'/2133, l='MpServer', x=180.50, y=40.00, z=258.50], EntityBat['Bat'/2141, l='MpServer', x=262.62, y=33.01, z=219.49], EntityCreeper['Creeper'/2149, l='MpServer', x=257.50, y=30.00, z=236.50], EntityCreeper['Creeper'/2154, l='MpServer', x=214.50, y=32.00, z=284.50], EntitySkeleton['Skeleton'/2158, l='MpServer', x=234.50, y=21.00, z=293.50], EntityZombie['Zombie'/1904, l='MpServer', x=202.19, y=31.00, z=210.49], EntityBat['Bat'/1907, l='MpServer', x=195.35, y=28.10, z=217.61], EntityBat['Bat'/2163, l='MpServer', x=257.75, y=26.10, z=211.41], EntityCreeper['Creeper'/2165, l='MpServer', x=186.68, y=28.00, z=230.50], EntityZombie['Zombie'/2168, l='MpServer', x=183.81, y=30.00, z=235.50], EntitySheep['Sheep'/123, l='MpServer', x=188.52, y=74.00, z=297.20], EntitySheep['Sheep'/124, l='MpServer', x=186.91, y=74.00, z=297.83], EntitySheep['Sheep'/125, l='MpServer', x=188.40, y=74.00, z=299.70], EntitySheep['Sheep'/126, l='MpServer', x=187.94, y=74.00, z=298.72], EntityBat['Bat'/2184, l='MpServer', x=232.67, y=22.07, z=296.68], EntitySheep['Sheep'/142, l='MpServer', x=216.58, y=76.00, z=209.42], EntitySheep['Sheep'/143, l='MpServer', x=218.18, y=74.00, z=210.64], EntityZombie['Zombie'/2192, l='MpServer', x=188.59, y=28.00, z=233.93], EntityZombie['Zombie'/2193, l='MpServer', x=189.50, y=28.00, z=228.50], EntityZombie['Zombie'/2194, l='MpServer', x=190.50, y=28.00, z=228.50], EntityCreeper['Creeper'/2205, l='MpServer', x=186.50, y=44.00, z=243.50], EntityCreeper['Creeper'/2207, l='MpServer', x=185.23, y=55.00, z=291.49], EntitySkeleton['Skeleton'/2214, l='MpServer', x=195.50, y=40.00, z=217.50], EntityZombie['Zombie'/2219, l='MpServer', x=196.50, y=54.00, z=215.50], EntityCreeper['Creeper'/2220, l='MpServer', x=187.50, y=40.00, z=239.50], EntityPig['Pig'/175, l='MpServer', x=234.78, y=67.00, z=224.47], EntityPig['Pig'/176, l='MpServer', x=240.71, y=65.00, z=231.74], EntityPig['Pig'/177, l='MpServer', x=236.67, y=67.00, z=225.49], EntityPig['Pig'/178, l='MpServer', x=240.50, y=65.00, z=234.50], EntityZombie['Zombie'/2229, l='MpServer', x=184.50, y=26.00, z=293.50], EntityCreeper['Creeper'/2231, l='MpServer', x=184.50, y=30.00, z=242.50], EntityPlayerSP['HansenND'/1720, l='MpServer', x=214.84, y=87.74, z=257.18], EntityPig['Pig'/188, l='MpServer', x=259.50, y=65.00, z=210.50], EntityPig['Pig'/190, l='MpServer', x=255.50, y=65.00, z=212.50], EntitySkeleton['Skeleton'/2241, l='MpServer', x=236.50, y=22.00, z=294.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 270211728 bytes (257 MB) / 786751488 bytes (750 MB) up to 1253310464 bytes (1195 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx1208M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                      | Signature                                |
	|:------ |:------------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                               | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                               | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | damageindicatorsmod | 1.0          | Damage-Indicators-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | llibrary            | 1.7.19       | llibrary-1.7.19-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire          | 1.8.1        | iceandfire-1.8.1.jar                        | None                                     |
	| LCHIJA | jei                 | 4.8.5.132    | jei_1.12.2-4.8.5.132.jar                    | None                                     |
	| LCHIJA | qsilkspawners       | 1.1.2        | qsilkspawners-1.1.2.jar                     | None                                     |
	| LCHIJA | somanyenchantments  | 0.4.3        | somanyenchantments+V0.4.31.jar              | None                                     |
	| LCHIJA | travellersbackpack  | 1.0.20.20    | TravellersBackpack-1.12.2-1.0.20.20 (1).jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by AlexModGuy** [comment]
> at DamageIndicatorsMod

not our issue.
