### ISSUE TITLE
Minecraft crash first of the inizialization of mods starts

### ISSUE THREAD

**Issue by nobody-arch** [Alex-the-666/Ice_and_Fire#2111]
[21:20:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:20:33] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:20:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:20:33] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[21:20:33] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_231, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jre1.8.0_231
[21:20:34] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[21:20:34] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[21:20:34] [main/INFO] [FML]: Searching C:\Users\Family\AppData\Roaming\.minecraft\mods for mods
[21:20:34] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:34] [main/WARN] [FML]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[21:20:34] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-99.jar
[21:20:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:20:34] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:20:34] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Family/AppData/Roaming/.minecraft/mods/VanillaFix-1.0.10-99.jar Service=LaunchWrapper Env=CLIENT
[21:20:35] [main/INFO] [VanillaFix]: Initializing VanillaFix
[21:20:36] [main/INFO] [VanillaFix]: Initializing StacktraceDeobfuscator
[21:20:36] [main/INFO] [VanillaFix]: Downloading MCP method mappings to: methods-stable_39.csv
[21:20:37] [main/INFO] [VanillaFix]: Done initializing StacktraceDeobfuscator
[21:20:37] [main/INFO] [VanillaFix]: Initializing Bug Fix Mixins
[21:20:37] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[21:20:37] [main/INFO] [VanillaFix]: Initializing Crash Fix Mixins
[21:20:37] [main/INFO] [VanillaFix]: Initializing Profiler Improvement Mixins
[21:20:37] [main/INFO] [VanillaFix]: Initializing Texture Fix Mixins
[21:20:37] [main/INFO] [VanillaFix]: Initializing Mod Support Mixins
[21:20:37] [main/WARN] [FML]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[21:20:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:20:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:20:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:20:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:20:41] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:20:41] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[21:20:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:20:41] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[21:20:41] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@6e0f32
[21:20:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:20:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:20:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:20:42] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:20:42] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:20:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:20:42] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:20:43] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:20:44] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraftforge/client/ForgeHooksClient.invalidateLog4jThreadCache()V @65: invokeinterface
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @65
    flags: { }
    locals: { 'java/lang/Object' }
    stack: { 'org/apache/logging/log4j/Logger', 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0x0000000: 1305 b813 05ba b605 be4b 1305 c013 05c2
    0x0000010: b605 be4c 2a04 b605 c82b 04b6 05c8 2a01
    0x0000020: b605 c9c0 0124 01b6 0128 2b01 b605 c9c0
    0x0000030: 0124 01b6 0128 a700 104b b202 eb13 05cd
    0x0000040: 2ab9 05d1 0300 b1                      
  Exception Handler Table:
    bci [0, 54] => handler: 57
    bci [0, 54] => handler: 57
  Stackmap Table:
    same_locals_1_stack_item_frame(@57,Object[#4])
    append_frame(@70,Object[#4])

	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:20:44] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
I dont know how to fix this error that happens when i launch minecraft with this mod please help the mod version is the 1.8.3 and game version is 1.12.2

**Comment by nobody-arch** [comment]
I fixed it uptading llibrary

**Comment by nobody-arch** [comment]
>
