### ISSUE TITLE
Cant even load up the game.

### ISSUE THREAD

**Issue by Shimeey** [Alex-the-666/Ice_and_Fire#2212]
So everytime I try to load up the mod on its own it doesn't even open the game and says "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.". Any clue how to fix?

**Comment by messicedragon** [comment]
Emm... I don&#39;t have this issue. Thanks for your consideration.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shimeey"; 
发送时间: 2020年3月1日(星期天) 凌晨0:25
收件人: "Alex-the-666/Ice_and_Fire";
抄送: "Subscribed";
主题: [Alex-the-666/Ice_and_Fire] Cant even load up the game. (#2212)




So everytime I try to load up the mod on its own it doesn't even open the game and says "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.". Any clue how to fix?
 
&mdash;

**Comment by chrisgoulden** [comment]
I'm getting the same issue. http://snpy.in/EhYsdV

**Comment by chrisgoulden** [comment]
Here is a log of the error. Hope this helps: 

`[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/patcher/IceAndFireRuntimePatcher
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.github.alexthe666.iceandfire.asm.IceAndFirePlugin.getASMTransformerClass(IceAndFirePlugin.java:18)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:33:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:33:11] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: `

**Comment by Tomas225** [comment]
Do you have llibrary installed ?

**Comment by chrisgoulden** [comment]
Awesome. HAd some issues with wrong forge versions and the LLibrary. All
sorted now. Cheers!
