### ISSUE TITLE
Error casting EntityPlayerMP to EntityDragonBase Part 2: Electric Boogaloo

### ISSUE THREAD

**Issue by Hazerd** [Alex-the-666/Ice_and_Fire#2216]
I'm having issue #1938 reoccur on my server, on the latest 1.8.4 release.
Looks like that error was only half-fixed. The same error is happening on a different line of code.
Particularly: It seems the if statement on EntityDragonFireCharge:127 needs the same check that was added to line 114 to fix the previous report.
Here's my crash report, if that helps:

	Time: 2020-03-03 23:26:26 EST
	Description: Ticking entity

	java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to com.github.alexthe666.iceandfire.entity.EntityDragonBase
		at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.onImpact(EntityDragonFireCharge.java:139)
		at net.minecraft.entity.projectile.EntityFireball.onUpdate(EntityFireball.java:98)
		at com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge.onUpdate(EntityDragonFireCharge.java:59)
		at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
		at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
		at net.minecraft.world.World.updateEntity(World.java:1955)
		at net.minecraft.world.World.redirect$updateEntity$zzj000(World.java:4118)
		at net.minecraft.world.World.updateEntities(World.java:1759)
		at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
		at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
		at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
		at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
		at java.lang.Thread.run(Thread.java:745)

	A detailed walkthrough of the error, its code path and all known details is as follows:
	---------------------------------------------------------------------------------------

	-- Entity being ticked --
	  Entity Type: iceandfire:dragonfirecharge (com.github.alexthe666.iceandfire.entity.EntityDragonFireCharge)
	  Entity ID: 53385
	  Entity Name: Dragon Fire Charge
	  Entity's Exact location: 81.47, 80.95, 1698.10
	  Entity's Block location: World: (81,80,1698), Chunk: (at 1,5,2 in 5,106; contains blocks 80,0,1696 to 95,255,1711), Region: (0,3; contains chunks 0,96 to 31,127, blocks 0,0,1536 to 511,255,2047)
	  Entity's Momentum: 0.63, -0.18, 0.03
	  Entity's Passengers: []
	  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	  Entity NBT: {Motion:[0.6332324416329904d,-0.18326852261693918d,0.031712555634363496d],ForgeData:{},UUIDLeast:-6385241034252161156L,RelativeAABB:[-0.4000000059604645d,0.0d,-0.4000000059604645d,0.4000000059604645d,0.800000011920929d,0.4000000059604645d],Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[115.4658f,7.470532f],UpdateBlocked:0b,life:0,FallDistance:0.0f,UUIDMost:-3345516018630309351L,Pos:[81.46687634949058d,80.95284227388889d,1698.0989664201652d],Fire:20s,ForgeCaps:{"llibrary:extendedentitydatacapability":{},"cavern:portal_cache":{LastPos:[],LastDim:[]}},power:[-0.01882937206243878d,-0.06741776998885529d,-5.466200319370488E-4d],direction:[0.6332324416329904d,-0.18326852261693918d,0.031712555634363496d]}

**Comment by AlexModGuy** [comment]
fixed
