### ISSUE TITLE
Client crash on Deathworm scale calc

### ISSUE THREAD

**Issue by soullinker** [Alex-the-666/Ice_and_Fire#2470]
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.getScale(EntityDeathWorm.java:328)
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.getScaleForAge(EntityDeathWorm.java:332)
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.func_70636_d(EntityDeathWorm.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.func_70071_h_(EntityDeathWorm.java:666)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by AlexModGuy** [comment]
dupe, old bug caused by shitty code from another mod. #1877
