### ISSUE TITLE
[2.0.0] Silver armor makes mod fail to load for some people, apparently.

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/Ice_and_Fire#2677]
[05Sep2020 19:41:02.004] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, fmlclient, --fml.forgeVersion, 31.2.36, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601, --username, FireLordZuko1, --version, 1.15.2-forge-31.2.36, --gameDir, C:\Users\Collin\AppData\Roaming\.technic\modpacks\forge-1152-slate, --assetsDir, C:\Users\Collin\AppData\Roaming\.technic\assets, --assetIndex, 1.15, --uuid, f86d24e6c0464f3287248d8f8b83ebc1, --accessToken, ????????, --userType, mojang, --versionType, release, --title, Forge Slate - 1.15.2, --icon, C:\Users\Collin\AppData\Roaming\.technic\assets\packs\forge-1152-slate\icon.png]
[05Sep2020 19:41:02.009] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0_201 by Oracle Corporation
[05Sep2020 19:41:02.788] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[05Sep2020 19:41:04.379] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.15.2-forge-31.2.36, --gameDir, C:\Users\Collin\AppData\Roaming\.technic\modpacks\forge-1152-slate, --assetsDir, C:\Users\Collin\AppData\Roaming\.technic\assets, --uuid, f86d24e6c0464f3287248d8f8b83ebc1, --username, FireLordZuko1, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --title, Forge Slate - 1.15.2, --icon, C:\Users\Collin\AppData\Roaming\.technic\assets\packs\forge-1152-slate\icon.png]
[05Sep2020 19:41:04.483] [main/INFO] [STDOUT/]: [net.minecraft.client.main.Main:main:79]: Completely ignored arguments: [--title, Forge Slate - 1.15.2, --icon, C:\Users\Collin\AppData\Roaming\.technic\assets\packs\forge-1152-slate\icon.png]
[05Sep2020 19:41:06.162] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: FireLordZuko1
[05Sep2020 19:41:14.317] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[05Sep2020 19:41:16.404] [Render thread/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `citadel` for name `debug`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
[05Sep2020 19:41:17.336] [modloading-worker-2/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.36, for MC 1.15.2 with MCP 20200515.085601
[05Sep2020 19:41:17.337] [modloading-worker-2/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.2.36 Initialized
[05Sep2020 19:41:19.227] [modloading-worker-5/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: iceandfire, class com.github.alexthe666.iceandfire.IceAndFire
java.lang.AbstractMethodError: null
	at net.minecraft.item.ArmorItem.<init>(ArmorItem.java:58) ~[?:?]
	at com.github.alexthe666.iceandfire.item.ItemSilverArmor.<init>(ItemSilverArmor.java:20) ~[?:2.0.0]
	at com.github.alexthe666.iceandfire.item.IafItemRegistry.<clinit>(IafItemRegistry.java:68) ~[?:2.0.0]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_201]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_201]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_201]
[05Sep2020 19:41:19.232] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[05Sep2020 19:41:19.233] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.36-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
[05Sep2020 19:41:19.890] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[05Sep2020 19:41:19.933] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[05Sep2020 19:41:19.955] [Server-Worker-3/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[05Sep2020 19:41:19.955] [Server-Worker-3/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[05Sep2020 19:41:19.955] [Server-Worker-3/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_201]
[05Sep2020 19:41:22.150] [Server-Worker-2/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[05Sep2020 19:41:22.150] [Server-Worker-2/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[05Sep2020 19:41:22.150] [Server-Worker-2/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_201]
[05Sep2020 19:41:22.318] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[05Sep2020 19:41:22.319] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[05Sep2020 19:41:22.477] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x0 jei:textures/atlas/gui.png-atlas
[05Sep2020 19:41:22.478] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[05Sep2020 19:41:22.574] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[05Sep2020 19:41:22.575] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[05Sep2020 19:41:22.575] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[05Sep2020 19:41:22.576] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[05Sep2020 19:41:22.577] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[05Sep2020 19:41:22.577] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[05Sep2020 19:41:22.915] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[05Sep2020 19:41:22.916] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[05Sep2020 19:41:22.916] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas

**Comment by AlexModGuy** [comment]
what other mods were they using

**Comment by Carro1001** [comment]
Only ice and fire and citadel, afaik
