### ISSUE TITLE
Ice and Fire 1.1.1 Crash (New map)

### ISSUE THREAD

**Issue by CainSeldon** [Alex-the-666/Ice_and_Fire#270]
Downloaded latest version of the mod as well as the library file, crash upon new map gen. Still seems to be related to snow villagers... 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.6-1.11.2.jar)
  SpongeCoremod (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar)
  TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 6/19/17 12:47 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1836)
	at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:852)
	at net.minecraft.entity.passive.EntityVillager.func_180482_a(EntityVillager.java:839)
	at com.github.alexthe666.iceandfire.entity.EntitySnowVillager.func_180482_a(EntitySnowVillager.java:38)
	at com.github.alexthe666.iceandfire.world.village.SnowVillagePieces$Village.spawnVillagers(SnowVillagePieces.java:981)
	at com.github.alexthe666.iceandfire.world.village.SnowVillagePieces$WoodHut.func_74875_a(SnowVillagePieces.java:1315)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at com.github.alexthe666.iceandfire.world.village.MapGenSnowVillage.func_180709_b(MapGenSnowVillage.java:50)
	at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:124)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzc000(GameRegistry.java:585)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:172)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3559)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:824)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:770)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3507)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3371099272 bytes (3214 MB) / 4136108032 bytes (3944 MB) up to 4136108032 bytes (3944 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
	IntCache: cache: 3, tcache: 104, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2296 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (custom256.jar) 
	UCHIJAA	forge{13.20.0.2296} [Minecraft Forge] (custom256.jar) 
	UCHIJAA	spongeapi{7.0.0-SNAPSHOT-0e27053} [SpongeAPI] (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar) 
	UCHIJAA	sponge{1.11.2-2282-7.0.0-BETA-2319} [SpongeForge] (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar) 
	UCHIJAA	animania{1.0.4.7} [Animania] (animania-1.11.2-1.0.4.7.jar) 
	UCHIJAA	biomesoplenty{6.1.0.2211} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2211-universal.jar) 
	UCHIJAA	bullseye{2.0.0} [Bullseye] (Bullseye-1.11.2-2.0.0.jar) 
	UCHIJAA	catclearlag{0.7.1} [CatClearLag] (CatClearLag-0.7.1.jar) 
	UCHIJAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJAA	iceandfire{1.1.1} [Ice and Fire] (iceandfire-1.1.1.jar) 
	UCHIJAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAA	luckperms{3.1.51} [LuckPerms] (LuckPerms-Sponge-3.1.51.jar) 
	UCHIJAA	mobrepeller{v1.1} [MobRepeller] (MobRepeller-v1.1.jar) 
	UCHIJAA	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) 
	UCHIJAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHIJAA	nucleus{0.28.1-S6.0} [Nucleus] (Nucleus-0.28.1-1.11.2-S6.0-plugin.jar) 
	UCHIJAA	realistictorches{2.1.0} [Realistic Torches] (RealisticTorches-1.11.2-2.1.0.jar) 
	UCHIJAA	realstonetools{7.0.2} [Real Stone Tools] (RealStoneTools-Forge-7.0.2.jar) 
	UCHIJAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAA	serverlistplus{3.4.7} [ServerListPlus] (ServerListPlus-3.4.7-Universal.jar) 
	UCHIJAA	lteleporters{1.11.2-2.1.2} [Simple Teleporters] (SimpleTeleporters-1.11.2-2.1.2.jar) 
	UCHIJAA	thutcore{4.4.1} [ThutCore] (thutcore-4.4.1.jar) 
	UCHIJAA	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCHIJAA	timewarp{2.2.1-r6.0.0} [TimeWarp] (timewarp-2.2.1-r6.0.0.jar) 
	UCHIJAA	tmotd{1.0} [TitleMOTD] (TitleMOTD.-.1.0.jar) 
	UCHIJAA	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
	UCHIJAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SpongeCoremod (spongeforge-1.11.2-2282-7.0.0-BETA-2319.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 100; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by CainSeldon** [comment]
another crash while exploring a wasteland biome:

[crash-2017-06-19_13.18.38-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1085754/crash-2017-06-19_13.18.38-server.txt)

**Comment by AlexModGuy** [comment]
duplicate #249
