### ISSUE TITLE
[1.16.1] Skeleton arrows crash server.

### ISSUE THREAD

**Issue by AvrgDerk** [Alex-the-666/Ice_and_Fire#2822]
Skeleton arrows now crash a server after installing Ice and Fire. Tested player arrows and this didn't cause an issue but when a skeleton was summoned and allowed to attack a player, our server instantly goes down. 

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 9/22/20 12:16 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_184215_y(Lnet/minecraft/entity/Entity;)Z
	at com.github.alexthe666.iceandfire.event.ServerEvents.onArrowCollide(ServerEvents.java:175) ~[?:2.0.1-1.16.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_260_ServerEvents_onArrowCollide_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:638) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:187) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:596) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.event.ServerEvents.onArrowCollide(ServerEvents.java:175)
	at net.minecraftforge.eventbus.ASMEventHandler_260_ServerEvents_onArrowCollide_ProjectileImpactEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:638)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:187)
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.entity.projectile.ArrowEntity)
	Entity ID: 1192
	Entity Name: Arrow
	Entity's Exact location: -1009.13, 64.54, -1607.79
	Entity's Block location: World: (-1010,64,-1608), Chunk: (at 14,4,8 in -64,-101; contains blocks -1024,0,-1616 to -1009,255,-1601), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,0,-2048 to -513,255,-1537)
	Entity's Momentum: 0.37, -0.15, 1.40
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:596)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397)

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['MythicSandman'/169, l='ServerLevel[world]', x=-405.87, y=49.00, z=-539.74], ServerPlayerEntity['AvrgDerk'/312, l='ServerLevel[world]', x=-1008.66, y=63.00, z=-1606.84]]
	Chunk stats: ServerChunkCache: 6050
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,69,80), Chunk: (at 0,4,0 in 11,5; contains blocks 176,0,80 to 191,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 62281108 game time, 51772197 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 47240 (now: false), thunder time: 85217 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 3.10.0-1062.1.1.el7.x86_64
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3072012248 bytes (2929 MB) / 5009047552 bytes (4777 MB) up to 5009047552 bytes (4777 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx5120M -Xms5120M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		TrashSlot_1.16.1-12.0.1.jar TrashSlot {trashslot@12.0.1 DONE}
		NetherPortalFix_1.16.1-7.0.1.jar NetherPortalFix {netherportalfix@7.0.1 DONE}
		zombiehs_1.16-2.4.jar Zombie Horse Spawn {zombiehs@2.4 DONE}
		treeharvester_1.16-1.3.jar Tree Harvester {treeharvester@1.3 DONE}
		curiousshulkerboxes-FORGE-1.16.1-3.0.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.16.1-3.0 DONE}
		jei-1.16.1-7.0.1.10.jar Just Enough Items {jei@7.0.1.10 DONE}
		prefab-1.6.0.1.jar Prefab {prefab@1.6.0.1 DONE}
		the-conjurer-1.16.1-1.0.8.jar The Conjurer {conjurer_illager@1.0.8 DONE}
		Abnormals-Core-1.16.1-v2.0.3.jar Abnormals Core {abnormals_core@2.0.3 DONE}
		Buzzier-Bees-1.16.1-2.0.1.jar Buzzier Bees {buzzier_bees@2.0.1 DONE}
		Berry-Good-1.16.1-3.0.0.jar Berry Good {berry_good@3.0.0 DONE}
		Hanami-1.16.1-v1.1.2.jar Hanami {hanami@1.1.2 DONE}
		Fruitful-1.16.1-v1.3.0.jar Fruitful {fruitful@1.3.0 DONE}
		Upgrade-Aquatic-1.16.1-2.0.1.jar Upgrade Aquatic {upgrade_aquatic@2.0.1 DONE}
		skeletonhs_1.16-1.3.jar Skeleton Horse Spawn {skeletonhs@1.3 DONE}
		Extra-Boats-1.16.1-1.4.1.jar Extra Boats {extraboats@1.4.1 DONE}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		Waystones_1.16.1-7.1.0.jar Waystones {waystones@7.1.0 DONE}
		Clumps-6.0.0.3.jar Clumps {clumps@6.0.0.3 DONE}
		XaerosWorldMap_1.10.1_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.10.1 DONE}
		comforts-FORGE-1.16.1-3.0.0.1.jar Comforts {comforts@FORGE-1.16.1-3.0.0.1 DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		TravelersBackpack-1.16.1-5.0.1.jar Traveler's Backpack {travelersbackpack@5.0.1 DONE}
		Bamboo-Blocks-1.16.1-2.0.1.jar Bamboo Blocks {bamboo_blocks@2.0.1 DONE}
		randompatches-1.16.1-1.22.1.1.jar RandomPatches {randompatches@1.16.1-1.22.1.1 DONE}
		BetterHurtTimer-1.16.1-3.3.0.4.jar Better Hurt Timer {betterhurttimer@1.16.1-3.3.0.4 DONE}
		ironshulkerboxes-1.16.1-5.0.1.jar Iron Shulker Boxes {ironshulkerbox@1.16.1-5.0.1 DONE}
		bedspreads-FORGE-1.16.1-4.0.0.2.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0.0.2 DONE}
		iceandfire-2.0.1-1.16.1.jar Ice and Fire {iceandfire@2.0.1-1.16.1 DONE}
		Ma-Essentials-1.16.1-3.2.5.jar Ma Essentials {maessentials@1.16.1-3.2.5 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		Nether-Extension-1.16.1-0.1.0.jar Nether Extension {nether_extension@0.1.0 DONE}
		Neapolitan-1.16.1-1.0.2.jar Neapolitan {neapolitan@1.0.2 DONE}
		structure-gel-api-1.16.1-1.2.1.jar Structure Gel API {structure_gel@1.2.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		forge-1.16.1-32.0.108-server.jar Minecraft {minecraft@1.16.1 DONE}
		The-Endergetic-Expansion-1.16.1-2.0.0.jar The Endergetic Expansion {endergetic@2.0.0 DONE}
		repurposed_structures-1.16.1-2.0.6.jar Repurposed Structures {repurposed_structures@1.16.1-2.0.6 DONE}
		inventorytotem_1.16-1.1.jar Inventory Totem {inventorytotem@1.1 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		enderitemod-1.16.1-0.5.3-forge-32.0.98.jar Enderite Mod {enderitemod@1.16.1-0.5.3-forge-32.0.98 DONE}
		towers_of_the_wild-1.16.1-1.2.2.jar Towers Of the Wild {towers_of_the_wild@1.16.1-1.2.2 DONE}
		Atmospheric-1.16.1-2.0.0.jar Atmospheric {atmospheric@2.0.0 DONE}
		curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 DONE}
		Savage-and-Ravage-1.16.1-2.0.0.jar Savage & Ravage {savageandravage@2.0.0 DONE}
		pamhc2foodcore-1.16.1-1.0.5.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		Autumnity-1.16.1-1.4.0.jar Autumnity {autumnity@1.4.0 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		Quark-r2.2-264.jar Quark {quark@r2.2-264 DONE}
		Enhanced-Mushrooms-1.16.1-v2.0.8.jar Enhanced Mushrooms {enhanced_mushrooms@2.0.8 DONE}
		DoubleSlabs-1.16-3.3.3.jar Double Slabs {doubleslabs@3.3.3 DONE}
		worldedit-forge-mc1.16.1-7.2.0-beta-03.jar WorldEdit {worldedit@7.2.0-beta-03+94ce464 DONE}
		Incubation-1.16.1-1.1.0.jar Incubation {incubation@1.1.0 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		CosmeticArmorReworked-1.16.1-v1b.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1b DONE}
		BetterMineshaftsForge-1.16.1-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 DONE}
	Player Count: 2 / 12; [ServerPlayerEntity['MythicSandman'/169, l='ServerLevel[world]', x=-405.87, y=49.00, z=-539.74], ServerPlayerEntity['AvrgDerk'/312, l='ServerLevel[world]', x=-1008.66, y=63.00, z=-1606.84]]
	Data Packs: vanilla, mod:quarkoddities, mod:trashslot (incompatible), mod:netherportalfix (incompatible), mod:zombiehs, mod:treeharvester, mod:curiousshulkerboxes (incompatible), mod:jei (incompatible), mod:prefab, mod:conjurer_illager, mod:abnormals_core, mod:buzzier_bees, mod:berry_good (incompatible), mod:hanami, mod:fruitful, mod:upgrade_aquatic, mod:skeletonhs, mod:extraboats, mod:bettercaves, mod:waystones (incompatible), mod:clumps (incompatible), mod:comforts (incompatible), mod:bamboo_blocks, mod:randompatches (incompatible), mod:betterhurttimer (incompatible), mod:ironshulkerbox (incompatible), mod:bedspreads (incompatible), mod:maessentials (incompatible), mod:forge, mod:nether_extension, mod:neapolitan, mod:structure_gel, mod:ironchest, mod:endergetic (incompatible), mod:repurposed_structures, mod:inventorytotem, mod:dungeons_plus, mod:enderitemod, mod:towers_of_the_wild, mod:atmospheric, mod:curios (incompatible), mod:savageandravage, mod:ftbbackups (incompatible), mod:collective, mod:autumnity, mod:autoreglib (incompatible), mod:quark, mod:enhanced_mushrooms, mod:doubleslabs, mod:worldedit (incompatible), mod:incubation, mod:fastleafdecay, mod:cosmeticarmorreworked (incompatible), mod:bettermineshafts, file/bac_advancements, mod:travelersbackpack, mod:pamhc2foodcore (incompatible), mod:xaeroworldmap, mod:citadel (incompatible), mod:iceandfire
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AvrgDerk** [comment]
Edit: Player arrows actually do crash the server when fired at entities, it seems like they crash worlds when they hit a mob.

**Comment by MattyExie** [comment]
Known issue, Alex and the team are aware of it, stay tuned!

**Comment by jamesdgessel** [comment]
This is happening on my server as well. Thanks for working on a fix!

**Comment by AlexModGuy** [comment]
fixed

**Comment by jamesdgessel** [comment]
> fixed

How do I get the fixed version? Is it updated on curse?

**Comment by Carro1001** [comment]
It's gonna update soon
