### ISSUE TITLE
Gorgon head statues which arent from this mod crash the game and corrupt the save when placed down

### ISSUE THREAD

**Issue by agr21** [Alex-the-666/Ice_and_Fire#2860]
it works with mobs from different mods, but also bees for example, unsure about the old ones

**Comment by AlexModGuy** [comment]
crashlog please?

**Comment by agr21** [comment]
sure,here :+1: 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.entity.passive.BeeEntity.func_70037_a(BeeEntity.java:187)
	at com.github.alexthe666.iceandfire.item.ItemStoneStatue.func_195939_a(ItemStoneStatue.java:91)
	at net.minecraft.item.ItemStack.lambda$onItemUse$5(ItemStack.java:185)
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:185)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:302)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:97)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1340)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1597)

also im not sure if it counts as corrupt, but i place it down,game closes, and so does everytime i try to go into the world

**Comment by agr21** [comment]
also enderman. other few random other mod entities work,just not all. only when placing down

**Comment by agr21** [comment]
[m[1;31m[02:07:43] [Render thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at net.minecraft.entity.passive.PolarBearEntity.func_70037_a(SourceFile:118) ~[?:?] {re:classloading}

polarbear too!
and iron golem

**Comment by AlexModGuy** [comment]
fixed
