### ISSUE TITLE
1.16.1 Server crashes when trying to fly on a any mob

### ISSUE THREAD

**Issue by DylanWDev** [Alex-the-666/Ice_and_Fire#2877]
I was doing some testing on my server and was seeing how well the server would handle a player flying on a dragon then the server crashed so I tried it again and same result so I tried flying a Hippogryph and it happened again. please fix :)

**Comment by AlexModGuy** [comment]
any crash report or log?

**Comment by Alex-the-666** [comment]
Or version?

**Comment by DylanWDev** [comment]
I didn't think to send that sorry :p. Here is the crash report and
screenshot. I also got this error ocer and over in the console " [m
[1;31m[13:39:46] [main/ERROR] [minecraft/GlobalEntityTypeAttributes]:
Entity iceandfire:stone_statue has no attributes" i dont know if this is a
problem or not but thought id send it anyway.
[image: Screenshot_36.png]

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/28/20 1:42 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_184215_y(Lnet/minecraft/entity/Entity;)Z
	at com.github.alexthe666.iceandfire.message.MessageDragonControl$Handler.handle(MessageDragonControl.java:70) ~[?:2.0.1-1.16.1] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:73) ~[?:?] {re:classloading}
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:73) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1331) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:735) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:157) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:718) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:712) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:647) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8619902712 bytes (8220 MB) / 10360455168 bytes (9880 MB) up to 10360455168 bytes (9880 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xmx10G -Xms10G
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-server.jar Minecraft {minecraft@1.16.1 DONE}
		repurposed_structures-1.16.1-2.0.6.jar Repurposed Structures {repurposed_structures@1.16.1-2.0.6 DONE}
		GentleFawn-1.1.1-MC1.16.1.jar Gentle Fawn {gentlefawn@1.1.1 DONE}
		torchslabmod-1.16.1_v1.6.16.jar Torch Slab Mod {torchslabmod@1.6.16 DONE}
		LetSleepingDogsLie-1.16.1-1.1.1.jar Let Sleeping Dogs Lie {dogslie@1.1.1 DONE}
		jei-1.16.1-7.0.1.10.jar Just Enough Items {jei@7.0.1.10 DONE}
		enderitemod-1.16.1-0.5.3-forge-32.0.98.jar Enderite Mod {enderitemod@1.16.1-0.5.3-forge-32.0.98 DONE}
		Abnormals-Core-1.16.1-2.0.4.jar Abnormals Core {abnormals_core@2.0.4 DONE}
		Upgrade-Aquatic-1.16.1-2.0.1.jar Upgrade Aquatic {upgrade_aquatic@2.0.1 DONE}
		Craftable+Saddles+[1.16.1]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		guildedarmor-1.16.1-1.0.1.jar Gilded Armor {gildedarmor@1.0.1 DONE}
		Extra-Boats-1.16.1-1.4.1.jar Extra Boats {extraboats@1.4.1 DONE}
		Placebo-1.16.1-4.1.3.jar Placebo {placebo@4.1.3 DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		DoubleSlabs-1.16-3.3.3.jar Double Slabs {doubleslabs@3.3.3 DONE}
		lanterncolors-1.16.1-2.0.0.jar Lantern Colors {lanterncolors@1.16.1-2.0.0 DONE}
		Bookshelf-1.16.1-6.3.21.jar Bookshelf {bookshelf@6.3.21 DONE}
		The-Endergetic-Expansion-1.16.1-2.0.0.jar The Endergetic Expansion {endergetic@2.0.0 DONE}
		snowundertrees-1.16.1-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		guardvillagers-1.16.1-1.1.4.jar Guard Villagers {guardvillagers@1.1.4 DONE}
		SaltOreMod+1.16.1+-+1.0.1.jar.jar Salt Ore Mod {saltoremod@1.16.1-1.0.0 DONE}
		iceandfire-2.0.1-1.16.1.jar Ice and Fire {iceandfire@2.0.1-1.16.1 DONE}
		Hwyla-forge-1.10.10-B77_1.16.1.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
		ToastControl-1.16.1-4.1.1.jar Toast Control {toastcontrol@4.1.1 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		Quark-r2.2-264.jar Quark {quark@r2.2-264 DONE}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 DONE}
	Player Count: 1 / 20; [ServerPlayerEntity['PowerOutage'/168, l='ServerLevel[world]', x=535.12, y=74.52, z=-929.69]]
	Data Packs: vanilla, mod:repurposed_structures, mod:gentlefawn, mod:torchslabmod, mod:dogslie, mod:jei (incompatible), mod:enderitemod, mod:abnormals_core, mod:upgrade_aquatic, mod:craftable_saddles (incompatible), mod:gildedarmor, mod:extraboats, mod:placebo (incompatible), mod:citadel (incompatible), mod:autoreglib (incompatible), mod:doubleslabs, mod:lanterncolors, mod:bookshelf (incompatible), mod:endergetic (incompatible), mod:snowundertrees, mod:guardvillagers (incompatible), mod:saltoremod, mod:iceandfire, mod:waila, mod:toastcontrol (incompatible), mod:forge, mod:quark, mod:waddles (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AlexModGuy** [comment]
this bug was fixed in 2.0.2. please update your mod.
