### ISSUE TITLE
Lan Breeding Problem

### ISSUE THREAD

**Issue by zucaluca** [Alex-the-666/Ice_and_Fire#2887]
I play a lan server with my sibling (I host the lan world)  and they get kicked every time we try and breed 2 dragons together. The egg spawns in on the nest blocks but my friend gets kicked right as it happens and they cannot log on anymore (getting kicked as soon as they join).

This issue has happened on the 1.15.2 update of ice and fire and the same thing again with 1.16.1, using citadel 1.15.2 and 1.16.1 respectively. Breeding works fine on 1.12.2 on LAN.

iceandfire-2.0.2-1.16.1
citadel-1.2.0-1.16.1
Text when kicked: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by tygor** [comment]
I have a similar error except the server crashes. I'm not sure if these are the same issue but here is the stack trace:

[Server thread/ERROR] [minecraft/ChunkSerializer]: An Entity type net.minecraft.entity.EntityType@7d416122 has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1383) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_184198_c(Entity.java:1301) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1309) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:302) ~[?:?] {re:classloading}
        at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:684) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) [?:1.8.0_261] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_261] {}
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) [?:1.8.0_261] {}
        at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:338) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_217210_a(SourceFile:324) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:754) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:528) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:550) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
Caused by: java.lang.NullPointerException
        at com.github.alexthe666.iceandfire.entity.EntityDragonEgg.getOwnerId(EntityDragonEgg.java:88) ~[?:2.0.2-1.15.2] {re:classloading}
        at com.github.alexthe666.iceandfire.entity.EntityDragonEgg.func_213281_b(EntityDragonEgg.java:52) ~[?:2.0.2-1.15.2] {re:classloading}
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1362) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        ... 22 more

- forge-1.15.2-31.2.0
- minecraft_server.1.15.2

mods:

- citadel-1.1.11
- forgemod_VoxelMap-1.9.28_for_1.15.2
- iceandfire-2.0.2-1.15.2
- jei-1.15.2-6.0.3.15

PS: This attempt was for a lightning dragon. We've experience the same for a fire dragon too.

**Comment by tygor** [comment]
I'm a C# developer trying to read Java for the first time so please give me grace.

At this line: https://github.com/Alex-the-666/Ice_and_Fire/blob/d63624ca31c8041d53623b02c0c1dfbde60d8038/src/main/java/com/github/alexthe666/iceandfire/entity/EntityDragonEgg.java#L88

Since it seems to be a NullPointerException, shouldn't the method first check if `this.dataManager` is null?

Granted, I see this same code working in other parts of the code base. Also, the dragons seem to breed in a single player creative world so this could be limited to running servers locally as we do. For this reason I tried to find the difference between `this.dataManager` and `this.getDataManager()` thinking it might be related to data synchronization between client and server but I didn't learn much.

PS: My kids and I love this mod. You're doing a great job.

**Comment by AlexModGuy** [comment]
fixed
