### ISSUE TITLE
Fire Dragon Breeding Issue (1.16.1 - 2.0.2)

### ISSUE THREAD

**Issue by CrazyDemonicWolf** [Alex-the-666/Ice_and_Fire#2910]
Hi there,
Been having an issue on my modded server with breeding dragons, Breeding two ice dragons at the same stage was fine however breeding two fire dragons, Female Stage 5 and Male Stage 4, caused a client crash and now players that were in the area cannot log in as they get a nettie.io error. Other players are fine that were not present while breeding. Here is the logs from the server

An Entity type entity.iceandfire.dragon_egg has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1410) ~[?:?]
	at net.minecraft.entity.Entity.func_184198_c(Entity.java:1324) ~[?:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1332) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:303) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:688) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$save$9(ChunkManager.java:357) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:354) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(SourceFile:321) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:691) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:533) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:808) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at com.github.alexthe666.iceandfire.entity.EntityDragonEgg.getOwnerId(EntityDragonEgg.java:93) ~[?:2.0.2-1.16.1]
	at com.github.alexthe666.iceandfire.entity.EntityDragonEgg.func_213281_b(EntityDragonEgg.java:56) ~[?:2.0.2-1.16.1]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1389) ~[?:?]
	... 23 more

**Comment by AlexModGuy** [comment]
fixed
