### ISSUE TITLE
crash when loading.

### ISSUE THREAD

**Issue by lilmrmagoo** [Alex-the-666/Ice_and_Fire#3057]
latest log: https://pastebin.com/1PWQ2Q4T
crash log: https://pastebin.com/wGuKTCWR

**Comment by BugmanBugman** [comment]
https://hatebin.com/ffsevpjquj

Got this as well, I believe this is due to the new forge update

**Comment by brandonmaster590** [comment]
same here

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/27/20 9:50 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-8.0.5.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-8.0.5.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[forge:?] {re:classloading}
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_222] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_222] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_222] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_222] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_222] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_222] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_222] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_222] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_222] {}

	Mod File: iceandfire-2.1.0-1.16.3.jar
	Failure message: Ice and Fire (iceandfire) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 2.0.3-1.16.3
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[forge:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.func_236394_a_(IafWorldRegistry.java:150) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.<clinit>(IafWorldRegistry.java:50) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_222] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_222] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_222] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_222] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_222] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_222] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_222] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_222] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_222] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 4.4.0-157-generic
	Java Version: 1.8.0_222, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1340633408 bytes (1278 MB) / 1633157120 bytes (1557 MB) up to 1771044864 bytes (1689 MB)
	CPUs: 3
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx1900M -Xms950M
	ModLauncher: 8.0.5+84+master.3310fe0
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.32
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.32-server.jar                   |Minecraft                     |minecraft                     |1.16.3              |CREATE_REG|NOSIGNATURE
		tetra-1.16.3-3.1.0.jar                            |Tetra                         |tetra                         |3.1.0               |CREATE_REG|NOSIGNATURE
		Ma-Enchants-1.16.3-3.5.0.jar                      |Ma Enchants                   |ma-enchants                   |1.16.3-3.5.0        |CREATE_REG|NOSIGNATURE
		forge-1.16.3-34.1.32-universal.jar                |Forge                         |forge                         |34.1.32             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BetterCaves-1.16.2-1.0.3.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.2-1.0.3        |CREATE_REG|NOSIGNATURE
		WeaponThrow-1.16.X-2.2.jar                        |Weapon Throw                  |weaponthrow                   |1.16.X-2.2          |CREATE_REG|NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |CREATE_REG|NOSIGNATURE
		mgui-1.16.3-3.1.2.jar                             |mgui                          |mgui                          |3.1.2               |CREATE_REG|NOSIGNATURE
		citadel-1.4.1.jar                                 |Citadel                       |citadel                       |1.4.1               |CREATE_REG|NOSIGNATURE
		iceandfire-2.1.0-1.16.3.jar                       |Ice and Fire                  |iceandfire                    |2.0.3-1.16.3        |ERROR     |NOSIGNATURE
		jei-1.16.3-7.6.0.49.jar                           |Just Enough Items             |jei                           |7.5.0.43            |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 04e71ec3-d8fd-4f4b-8c1d-b35fabc95d65

**Comment by Okimo** [comment]
Yup its issue with Forge 34.1.27+ 
https://pastebin.com/1mT90H2h

> Build: 1.16.3-34.1.27 - Mon Oct 26 02:27:48 GMT 2020
	cpw:
		Rollback registries to vanilla state if something happens during loading, so subsequent activities can still run and not generate false reports..		
		Signed-off-by: cpw <cpw+github@weeksfamily.ca>
	cpw:
		Add signature reporting for mods, using new signature capture from ModLauncher. Need to figure out
		how to reflect Minecraft's JAR signatures into here.		
		Signed-off-by: cpw <cpw+github@weeksfamily.ca>
