### ISSUE TITLE
Forge update is crashing the mod 

### ISSUE THREAD

**Issue by Xevolt** [Alex-the-666/Ice_and_Fire#3062]
With the recent update on forge the mod crashes i was wondering when are you going to fix this.

**Comment by WenXin20** [comment]
Hello, I also had this crash with forge v34.1.33
<details>
  <summary>Error Log</summary>

```
[00:51:41] [modloading-worker-3/ERROR]: Failed to create mod instance. ModID: iceandfire, class com.github.alexthe666.iceandfire.IceAndFire
java.lang.ExceptionInInitializerError: null
	at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[?:2.1.0-1.16.3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) [?:34.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3108/1719999141.run(Unknown Source) [?:34.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3422/1010419513.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?]
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.func_236394_a_(IafWorldRegistry.java:150) ~[?:2.1.0-1.16.3]
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.<clinit>(IafWorldRegistry.java:50) ~[?:2.1.0-1.16.3]
	... 16 more
```
  
</details>

**Comment by kreezxil** [comment]
Issue:  iceandfire-2.1.0-1.16.3 crashes dedicated server Forge 1.16.3 build 34.1.33

Notes:
     looks like an npe, happens on forges above 34.1.25

crash report: 
http://paste.ubuntu.com/p/wgsvPFQPpr/

fml server latest: 
http://paste.ubuntu.com/p/zrctd6sgpK/

The higest forge I&F works on is 1.16.3-34.1.25, the forges between .26 to .28 or horribly broken. 29 is the first one that loads again and where I&F shows the same error on each thru to yesterdays release of 34.1.33.
