### ISSUE TITLE
Minecraft Launching Error

### ISSUE THREAD

**Issue by MasterCJ123** [Alex-the-666/Ice_and_Fire#3067]
I have this in my mod pack "Master Survival(MS Craft)" and it is required to stay as it's a huge part of the content. However, it won't load with the latest Forge update "forge-34.1.33

**Comment by BedrockLegends** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues/3070

**Comment by whorlbinder** [comment]
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

	Mod File: iceandfire-2.1.0-1.16.3.jar
	Failure message: Ice and Fire (iceandfire) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 2.0.3-1.16.3
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[forge:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.func_236394_a_(IafWorldRegistry.java:150) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.<clinit>(IafWorldRegistry.java:50) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

Having the same issue. Here's the relevant part of the trace

**Comment by MK105Cruiser** [comment]
I am getting the same issue. 
I have no programming experience and would appreciate help with this.
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

	Mod File: iceandfire-2.1.0-1.16.3.jar
	Failure message: Ice and Fire (iceandfire) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 2.0.3-1.16.3
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
Stacktrace:
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[forge:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?] {re:classloading}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.func_236394_a_(IafWorldRegistry.java:150) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.<clinit>(IafWorldRegistry.java:50) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:83) ~[iceandfire:2.1.0-1.16.3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4861706568 bytes (4636 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 2
	JVM Flags: 10 total; -Xmn128M -Xmx5113M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.5+84+master.3310fe0
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.3_HD_U_G4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.32
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.32-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |CREATE_REG|NOSIGNATURE
		forge-1.16.3-34.1.32-universal.jar                |Forge                         |forge                         |34.1.32             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.3-1.13.jar                |TLSkinCape                    |tlskincape                    |1.6                 |CREATE_REG|19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		citadel-1.4.0.jar
