### ISSUE TITLE
World gen deadlock in EntityHippogryph

### ISSUE THREAD

**Issue by IzzelAliz** [Alex-the-666/Ice_and_Fire#3222]
I'm running Minecraft 1.15.2 server, Forge 31.2.45, Ice and Fire 2.1.0

Here is a crash report https://paste.ubuntu.com/p/TCmtF9dSQ5/

With my debug-tools mod installed, a world during generation is leaked and `getChunk` is (not directly) called:

<pre>
[28/11/2020 18:12:23.220] [Server-Worker-14/WARN] [DebugTools/]: World gen deadlock occur at [39, -36]
[28/11/2020 18:12:23.223] [Server-Worker-14/WARN] [DebugTools/]: Thread is "Server-Worker-14" Id=181 RUNNABLE
	at sun.management.ThreadImpl.getThreadInfo1(Native Method)
	at sun.management.ThreadImpl.getThreadInfo(Unknown Source)
	at sun.management.ThreadImpl.getThreadInfo(Unknown Source)
	at net.minecraft.world.server.ServerChunkProvider.handler$bck000$debug$worldGenDeadlock(ServerChunkProviderMixin.java:1133)
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProviderMixin.java)
	at net.minecraft.world.World.func_217353_a(WorldMixin.java:149)
	at net.minecraft.world.IWorldReader.func_225526_b_(IWorldReader.java:43)
	at net.minecraft.world.biome.FuzzedBiomeMagnifier.func_225532_a_(SourceFile:66)
	at net.minecraft.world.biome.ColumnFuzzedBiomeMagnifier.func_225532_a_(SourceFile:8)
	at net.minecraft.world.biome.BiomeManager.func_226836_a_(SourceFile:21)
	at net.minecraft.world.IWorldReader.func_226691_t_(IWorldReader.java:34)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_213386_a(EntityHippogryph.java:655)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawnerMixin.java:263)
	at net.minecraft.world.gen.OverworldChunkGenerator.func_202093_c(SourceFile:56)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:86)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1637/1767806001.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195)
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManagerMixin.java:518)
	at net.minecraft.world.server.ChunkManager$$Lambda$10509/518102926.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManagerMixin.java:516)
	at net.minecraft.world.server.ChunkManager$$Lambda$10504/771715966.apply(Unknown Source)
	at net.minecraft.world.server.ChunkManager.md98b135$lambda$debug$guardGenerate$1$0(ChunkManagerMixin.java:1648)
	at net.minecraft.world.server.ChunkManager$$Lambda$10506/1028802426.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$10449/1497852494.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
</pre>

In EntityHippogryph the `getBiome` is called which loads the chunk, but that chunk is generating and here cause the deadlock.

**Comment by Bidgam** [comment]
And I thought this was just me. I generated dozens of worlds to figure out what was causing my world gen to fail at semi-random times. I tracked it down to something in Ice and Fire mod, but I wasn't sure what it was. I was confident it was something the world gen was trying to place and for some reasons it failed. 

It takes a while before it will fail though, so it seems some sort of special arrangement is required.

World gen failed consistent per run, but the point of crash sometime was tens of thousands of chunks before doing so (or about a 2000x2000+ grid).

It's a bit strange though, what in the world is world genning with Hippogryphs? I didn't think they have a cave or platform like a building.
