### ISSUE TITLE
Crash on 2.1.4

### ISSUE THREAD

**Issue by B-Wither** [Alex-the-666/Ice_and_Fire#3267]
![2020-12-11_09 28 14](https://user-images.githubusercontent.com/63962480/101846356-18128e80-3b94-11eb-82c8-7c2cac1da4e2.png)

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 20/12/11 9:33
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3992/438094511.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3762/1869544015.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.0.18.jar:35.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$434/1279469670.call(Unknown Source) [forge-1.16.4-35.0.18.jar:35.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexthe666.iceandfire.item.IafArmorMaterial.func_230304_f_(IafArmorMaterial.java:23) ~[?:2.1.4-1.16.4] {re:classloading}
-- MOD iceandfire --
Details:
	Mod File: iceandfire-2.1.4-1.16.4.jar
	Failure message: Ice and Fire (iceandfire) has failed to load correctly
		java.lang.NoSuchMethodError: com.github.alexthe666.citadel.server.item.CustomArmorMaterial.getKnockbackResistance()F
	Mod Version: 2.1.4-1.16.4
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.NoSuchMethodError: com.github.alexthe666.citadel.server.item.CustomArmorMaterial.getKnockbackResistance()F
Stacktrace:
	at com.github.alexthe666.iceandfire.item.IafArmorMaterial.func_230304_f_(IafArmorMaterial.java:23) ~[?:2.1.4-1.16.4] {re:classloading}
	at net.minecraft.item.ArmorItem.<init>(ArmorItem.java:66) ~[?:?] {re:classloading}
	at com.github.alexthe666.iceandfire.item.ItemSilverArmor.<init>(ItemSilverArmor.java:21) ~[?:2.1.4-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.item.IafItemRegistry.<clinit>(IafItemRegistry.java:74) ~[?:2.1.4-1.16.4] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$3149/1620154859.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[?:35.0] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3074/392760852.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3111/1326413897.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2765249328 bytes (2637 MB) / 6006243328 bytes (5728 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.0.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.0.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.0.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.0.18.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.0.18.jar fml TRANSFORMATIONSERVICE 
	FML: 35.0
	Forge: net.minecraftforge:35.0.18
	FML Language Providers: 
		javafml@35.0
		minecraft@1
	Mod List: 
		forge-1.16.4-35.0.18-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |CREATE_REG|NOSIGNATURE
		forge-1.16.4-35.0.18-universal.jar                |Forge                         |forge                         |35.0.18             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |CREATE_REG|NOSIGNATURE
		iceandfire-2.1.4-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.4-1.16.4        |ERROR     |NOSIGNATURE
		NaturesCompass-1.16.3-1.8.5.jar                   |Nature's Compass              |naturescompass                |1.16.3-1.8.5        |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 04ced943-b2b7-40f1-a755-e5c0af5caf9a

**Comment by Daejangnamu** [comment]
minecraft restart try and iceandfire config delete

**Comment by AlexModGuy** [comment]
hmm, try the latest forge

**Comment by B-Wither** [comment]
It looks like not working on latest Forge too...
