### ISSUE TITLE
Mineshaft chests are empty?

### ISSUE THREAD

**Issue by Amayapuppy** [Alex-the-666/Ice_and_Fire#3274]
I'm not entirely sure this is ice and fires doing, but it mentioned this mod under this

[11Dec2020 00:28:04.428] [Worker-Main-13/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table minecraft:chests/abandoned_mineshaft
--
  | java.lang.NullPointerException: null
  | at net.minecraft.loot.LootTable.lambda$addPool$2(LootTable.java:207) ~[?:?]
  | at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_275]
  | at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[?:1.8.0_275]
  | at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_275]
  | at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_275]
  | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_275]
  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
  | at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_275]
  | at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_275]
  | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275]
  | at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516) ~[?:1.8.0_275]
  | at net.minecraft.loot.LootTable.addPool(LootTable.java:207) ~[?:?]
  | at com.github.alexthe666.iceandfire.event.ServerEvents.onChestGenerated(ServerEvents.java:812) ~[iceandfire:2.1.4-1.16.4]
  | at net.minecraftforge.eventbus.ASMEventHandler_96_ServerEvents_onChestGenerated_LootTableLoadEvent.invoke(.dynamic) ~[?:?]

https://paste.gg/p/anonymous/09f7bc49158d4759b9ba1f75ce1cbdcd

**Comment by LannyE** [comment]
I am having the same problem.  I have Ice and Fire, Wyrmroost, and Citadel addons installed.  This is the error generated in the debug log
[11Dec2020 21:01:03.494] [Worker-Main-12/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2725/1880223456@fd2ebe0
		2: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@1bf2c04a onChestGenerated(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException
	at net.minecraft.loot.LootTable.lambda$addPool$2(LootTable.java:207)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at net.minecraft.loot.LootTable.addPool(LootTable.java:207)
	at com.github.alexthe666.iceandfire.event.ServerEvents.onChestGenerated(ServerEvents.java:812)
	at net.minecraftforge.eventbus.ASMEventHandler_56_ServerEvents_onChestGenerated_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:653)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:849)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.util.HashMap.forEach(Unknown Source)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53)
	at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

[11Dec2020 21:01:03.932] [Worker-Main-12/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table minecraft:chests/abandoned_mineshaft
java.lang.NullPointerException: null
	at net.minecraft.loot.LootTable.lambda$addPool$2(LootTable.java:207) ~[?:?]
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[?:1.8.0_211]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.loot.LootTable.addPool(LootTable.java:207) ~[?:?]
	at com.github.alexthe666.iceandfire.event.ServerEvents.onChestGenerated(ServerEvents.java:812) ~[iceandfire:2.1.4-1.16.4]
	at net.minecraftforge.eventbus.ASMEventHandler_56_ServerEvents_onChestGenerated_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:653) ~[forge:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:849) ~[forge:?]
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?]
	at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_211]

**Comment by LannyE** [comment]
Since I only have three mods installed I removed Wyrmroost and the server didn't error.  I added it back in and restarted the server and the error came back.  I removed the Ice and Fire and Citadel mods and just loaded Wrymroost and it loaded fine by itself.  Not sure which mod is culprit here.
