### ISSUE TITLE
Ticking entity crash regarding pixies

### ISSUE THREAD

**Issue by darthvader45** [Alex-the-666/Ice_and_Fire#336]
Got near a pixie to get my first instance of the achievement "How Quaint!"  Went to explore the nearby hut, heard a pixie taunt me "Nana-nana-na-na!"  Suddenly my game crashed.
```Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.7.2.jar)
  llibrary (llibrary-1.7.7-1.11.2.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.298-universal.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  SurgeLoadingPlugin (Surge-1.11.2-1.2.0.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.2.4.jar)
  BetterFontsCore (TTFR-1.11.2-1.7.4.jar)
  AstralCore (astralsorcery-1.4.5.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/8/17 12:44 PM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:125)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:895)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at com.github.alexthe666.iceandfire.entity.EntityPixie.func_70636_d(EntityPixie.java:215)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:125)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:895)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at com.github.alexthe666.iceandfire.entity.EntityPixie.func_70636_d(EntityPixie.java:215)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:if_pixie (com.github.alexthe666.iceandfire.entity.EntityPixie)
	Entity ID: 70767
	Entity Name: Pixie
	Entity's Exact location: -324.50, 74.00, 64.50
	Entity's Block location: World: (-325,74,64), Chunk: (at 11,4,0 in -21,4; contains blocks -336,0,64 to -321,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)```

**Comment by darthvader45** [comment]
@Alex-the-666 It's a continuing bug with the pixie's item theft.  Sometimes it's one item to trigger, sometimes several.  Always happens in survival.
