### ISSUE TITLE
Null Pointer - Entity being ticked - EntityMyrmexSentinel

### ISSUE THREAD

**Issue by Chasethechicken** [Alex-the-666/Ice_and_Fire#3394]
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 07.01.21 17:13
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:129) ~[?:?] {re:classloading}
	at net.minecraft.pathfinding.PathNavigator.func_241390_a_(PathNavigator.java:100) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.GatherPOITask.func_212831_a_(SourceFile:108) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.GatherPOITask.func_212831_a_(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:49) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218218_d(SourceFile:506) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:465) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:195) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:688) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1612) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2576) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217459_a(ServerWorld.java:638) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:618) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:129) ~[?:?] {re:classloading}
	at net.minecraft.pathfinding.PathNavigator.func_241390_a_(PathNavigator.java:100) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.GatherPOITask.func_212831_a_(SourceFile:108) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.GatherPOITask.func_212831_a_(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:49) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218218_d(SourceFile:506) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:465) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:195) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:688) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1612) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2576) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217459_a(ServerWorld.java:638) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:618) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:myrmex_sentinel (com.github.alexthe666.iceandfire.entity.EntityMyrmexSentinel)
	Entity ID: 533
	Entity Name: Myrmex Sentinel
	Entity's Exact location: 99.10, 72.00, 727.87
	Entity's Block location: World: (99,72,727), Chunk: (at 3,4,7 in 6,45; contains blocks 96,0,720 to 111,255,735), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [VillagerEntity['Nitwit'/534, l='ServerLevel[world]', x=98.91, y=71.95, z=726.64]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Voltolos'/413, l='ServerLevel[world]', x=-35.42, y=65.34, z=846.41]]
	Chunk stats: ServerChunkCache: 4579
	Level dimension: minecraft:overworld
	Level spawn location: World: (-765,71,341), Chunk: (at 3,4,5 in -48,21; contains blocks -768,0,336 to -753,255,351), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 341614 game time, 4627 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 33978 (now: false), thunder time: 138761 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
```

Minecraft Version: 1.16.4

**Comment by Chasethechicken** [comment]
Maybe its related to https://github.com/Alex-the-666/Ice_and_Fire/issues/3208?

**Comment by TheBv** [comment]
Actually it's probably the "same" as ~~#3394~~  #3393
Although this time it's not the villager looking for a bed to sleep in but instead looking for a... point of interest? So possibly a block that determines the job it has or something similar

**Comment by Chasethechicken** [comment]
Im assuming you meant to link to https://github.com/Alex-the-666/Ice_and_Fire/issues/3393?

**Comment by TheBv** [comment]
Yeah I did my mistake sorry ^^"
