### ISSUE TITLE
NullPointerException OnPlayerAttackEntity

### ISSUE THREAD

**Issue by Blackpinned** [Alex-the-666/Ice_and_Fire#3407]
I'm fighting a sea serpent and every time I hit it this error pops into my log causing a lag spike. 

java.lang.NullPointerException
	at commoble.entitydetectors.EntityDetectors.onPlayerAttackEntity(EntityDetectors.java:64)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:732)
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1044)
	at com.github.alexthe666.iceandfire.event.ServerEvents.onPlayerAttackMob(ServerEvents.java:265)
	at net.minecraftforge.eventbus.ASMEventHandler_1578_ServerEvents_onPlayerAttackMob_AttackEntityEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:732)
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1044)
	at net.minecraft.client.multiplayer.PlayerController.func_78764_a(PlayerController.java:352)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1305)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by DenilsonNM** [comment]
can you specify what version of ice and fire it is?

**Comment by Blackpinned** [comment]
This is the version that just came out. The current release version.
Downloaded it earlier today.

Op za 9 jan. 2021 16:53 schreef Denilson Nuñez <notifications@github.com>:

**Comment by TheBv** [comment]
Are you possibly using this mod as well ?
https://www.curseforge.com/minecraft/mc-mods/entity-detectors
Since the first line `commoble.entitydetectors.EntityDetectors.onPlayerAttackEntity(EntityDetectors.java:64)` appears to be from that mod.
Either they need to make sure to check [here](https://github.com/Commoble/entity-detectors/blob/1feb74ac07bb43e1d288735719f294aef9a31281/src/main/java/commoble/entitydetectors/EntityDetectors.java#L64)  if the entity is null or Ice and Fire needs to check that the entity isn't null ([here](https://github.com/Alex-the-666/Ice_and_Fire/blob/22bcd94fb80799525e53f839ca5b1c773f51944c/src/main/java/com/github/alexthe666/iceandfire/event/ServerEvents.java#L265)) before parsing it to the function.
But since this isn't causing any issues in vanilla minecraft/with most mods I'd argue that they need to add a null check. But I'm not an expert on that stuff.

**Comment by Blackpinned** [comment]
Oh seems I am. I thought it was a function from Ice & Fire. They came with the pack I'm using... I didn't even know it was in there. There's no detectors placed anywhere as far as I can tell.... I'll just try tossing it out and see what it gives.
