### ISSUE TITLE
Ice and Fire 1.12.2 Crash

### ISSUE THREAD

**Issue by dfghjklghjkiuy** [Alex-the-666/Ice_and_Fire#3487]
I try to run it and Minecraft tells me that the mod file is incomplete and is searching for something that doesn't exist

**Comment by dfghjklghjkiuy** [comment]
Here is the stack trace 
16:42:06.763
append_frame(@70,Object[#4])
16:42:06.763
16:42:06.763
at net.minecraft.client.Minecraft.<init>(Minecraft.java:335) ~[bib.class:?]
16:42:06.763
at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
16:42:06.763
... 6 more
16:42:06.763
Exception in thread "Client thread" [16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
16:42:06.763
[16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
16:42:06.763
[16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
16:42:06.763
[16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
16:42:06.763
[16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
16:42:06.763
[16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
16:42:06.763
[16:42:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
16:42:06.944
Process crashed with exit code 1
