### ISSUE TITLE
Dread horse player crash loop

### ISSUE THREAD

**Issue by MrSkittlesROTR** [Alex-the-666/Ice_and_Fire#3514]
[19:00:53] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID f3a8a745-85a8-4636-a952-835a29595b77
[19:00:53] [Server thread/ERROR] [minecraft/ChunkSerializer]: An Entity type entity.iceandfire.dread_horse has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1433) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_184198_c(Entity.java:1347) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1355) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:303) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:682) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.lambda$save$9(ChunkManager.java:351) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?] {}
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:348) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:307) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:698) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:531) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.NullPointerException
	at com.github.alexthe666.iceandfire.entity.EntityDreadHorse.getCommanderId(EntityDreadHorse.java:96) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityDreadHorse.func_213281_b(EntityDreadHorse.java:57) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1412) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 23 more
	
	
iceandfire-2.1.5-1.16.4.jar throws any player who goes near the loaded chunk into a crash loop

**Comment by MrSkittlesROTR** [comment]
Entity couldnt be deleted or removed, chunk couldnt be replaced or fixed via mcedit or python region replacement. Had to remove the mod from the server to allow players to log back in.

**Comment by TheBv** [comment]
I implemented a fix for this in #3412 so it'll will be fixed in the next public release.
