### ISSUE TITLE
CRASH AT LAUNCH [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by MrSherlockyX** [Alex-the-666/Ice_and_Fire#3695]
When i play start, its crash.

Log:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 14/03/21 23:20
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at doggytalents.ModBlocks.registerBlockColours(ModBlocks.java:46) ~[?:1.15.2.3] {re:classloading,pl:object_holder_definalize:A}
	at doggytalents.DoggyTalentsMod$$Lambda$3270/1843866330.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2132/63636701.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$5288/1925281265.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading,xf:fml:vampirism:get_all_scan_data}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.49.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1140448598.call(Unknown Source) [forge-1.15.2-31.2.49.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at doggytalents.ModBlocks.registerBlockColours(ModBlocks.java:46)
	at doggytalents.DoggyTalentsMod$$Lambda$3270/1843866330.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2132/63636701.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$5288/1925281265.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1140448598.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2816583224 bytes (2686 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.49.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.15.2_HD_U_G6_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.49.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.49
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		forge-1.15.2-31.2.49-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		astralsorcery-1.15.2-1.12.14.jar Astral Sorcery {astralsorcery@1.15.2-1.12.14 CREATE_REGISTRIES}
		ToolStats-1.15.2-1.0.2.jar ToolStats {toolstats@1.0.2 CREATE_REGISTRIES}
		Druidcraft-1.15-0.4.44.jar Druidcraft {druidcraft@0.4.44 CREATE_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 CREATE_REGISTRIES}
		jeiintegration_1.15.2-3.1.1.2.jar JEI Integration {jeiintegration@3.1.1.2 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 CREATE_REGISTRIES}
		create-mc1.15.2_v0.3c.jar Create {create@mc1.15.2_v0.3c CREATE_REGISTRIES}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 CREATE_REGISTRIES}
		Xaeros_Minimap_21.4.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@21.4.1 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 CREATE_REGISTRIES}
		gravestone-1.17.6.jar Gravestone Mod {gravestone@1.17.6 CREATE_REGISTRIES}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 CREATE_REGISTRIES}
		citadel-1.1.11-deobf.jar Citadel {citadel@1.1.11 CREATE_REGISTRIES}
		appliedenergistics2-7.0.5.jar Applied Energistics 2 {appliedenergistics2@7.0.5 CREATE_REGISTRIES}
		TravelersBackpack-1.15.2-4.0.8.jar Traveler's Backpack {travelersbackpack@4.0.8 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 CREATE_REGISTRIES}
		betteranimals-1.15.2-5.5.0.jar Cyber's Better Animal Models {betteranimals@5.5.0 CREATE_REGISTRIES}
		Artifacts-1.15.2-2.5.1.jar Artifacts {artifacts@1.15.2-2.5.1 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.75-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.75 CREATE_REGISTRIES}
		midnight-0.5.11.jar The Midnight {midnight@0.5.11 CREATE_REGISTRIES}
		jei-1.15.2-6.0.2.13.jar Just Enough Items {jei@6.0.2.13 CREATE_REGISTRIES}
		TerraForged-1.15.2-0.1.3.jar TerraForged {terraforged@0.1.3 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-2.2.4.jar Dungeon Crawl {dungeoncrawl@2.2.4 CREATE_REGISTRIES}
		structurize-0.13.109-ALPHA-universal.jar Structurize {structurize@0.13.109-ALPHA CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 CREATE_REGISTRIES}
		BedBenefits-1.15.2-1.0.4.jar BedBenefits {bedbenefits@1.0.4 CREATE_REGISTRIES}
		minecolonies-0.13.645-RELEASE-universal.jar MineColonies {minecolonies@0.13.645-RELEASE CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		Vampirism-1.15.2-1.7.0.jar Vampirism {vampirism@1.7.0 CREATE_REGISTRIES, teamlapenlib@1.7.0 CREATE_REGISTRIES}
		observerlib-1.15.2-1.3.2.jar ObserverLib {observerlib@1.15.2-1.3.2 CREATE_REGISTRIES}
		iceandfire-2.0.3-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 ERROR}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version CREATE_REGISTRIES}
		BackTools-1.15.2-8.0.0.jar Back Tools {backtools@8.0.0 CREATE_REGISTRIES}
		walljump-forge-1.15.2-1.3.5.jar Wall-Jump! {walljump@1.15.2-1.3.5 CREATE_REGISTRIES}
		inventorypets-2.0.12.jar Inventory Pets {inventorypets@2.0.12 CREATE_REGISTRIES}
		iChunUtil-1.15.2-8.0.3.jar iChunUtil {ichunutil@8.0.3 CREATE_REGISTRIES}
		byg-1.0.11.jar Oh The Biomes You'll Go {byg@1.0.11 CREATE_REGISTRIES}
		forge-1.15.2-31.2.49-universal.jar Forge {forge@31.2.49 CREATE_REGISTRIES}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 CREATE_REGISTRIES}
		Atum-1.15.2-2.1.12.jar Atum 2 {atum@1.15.2-2.1.12 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.23.jar Aquaculture 2 {aquaculture@1.15.2-2.0.23 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.15.2-1.2.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.2 CREATE_REGISTRIES}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
	Launched Version: 1.15.2-forge-31.2.49
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 570 Series GL version 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 6x AMD Ryzen 5 3500X 6-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 19
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-v1.0.1.zip
	OpenGlVersion: 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by TheBv** [comment]
This has nothing to do with ice and fire. But instead with "doggytalents.DoggyTalentsMod"

**Comment by MrSherlockyX** [comment]
But, when i remove i&f, the game works. I think they are not campatible
