### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by MEULIEN** [Alex-the-666/Ice_and_Fire#3744]
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/client/model/IFChainBuffer

Full report:
java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/client/model/IFChainBuffer
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.<init>(EntityDragonBase.java:248) ~[?:2.1.6-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.<init>(EntityFireDragon.java:55) ~[?:2.1.6-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafEntityRegistry$$Lambda$6092/639706573.create(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:445) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.EntityType.func_200719_a(EntityType.java:467) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.EntityType.func_200717_a(EntityType.java:451) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147281_a(ClientPlayNetHandler.java:856) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:betterendforge.mixins.json:ClientPlayNetHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$14058/1891836736.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.54.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/740735495.call(Unknown Source) [forge-1.16.5-36.0.54.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.client.model.IFChainBuffer
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 29 more
	Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for com.github.alexthe666.iceandfire.client.model.IFChainBuffer
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
		at com.github.alexthe666.iceandfire.entity.EntityDragonBase.<init>(EntityDragonBase.java:248) ~[?:2.1.6-1.16.4] {re:classloading}
		at com.github.alexthe666.iceandfire.entity.EntityFireDragon.<init>(EntityFireDragon.java:55) ~[?:2.1.6-1.16.4] {re:classloading}
		at com.github.alexthe666.iceandfire.entity.IafEntityRegistry$$Lambda$6092/639706573.create(Unknown Source) ~[?:?] {}
		at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:445) ~[?:?] {re:mixin,re:classloading}
		at net.minecraft.entity.EntityType.func_200719_a(EntityType.java:467) ~[?:?] {re:mixin,re:classloading}
		at net.minecraft.entity.EntityType.func_200717_a(EntityType.java:451) ~[?:?] {re:mixin,re:classloading}
		at net.minecraft.client.network.play.ClientPlayNetHandler.func_147281_a(ClientPlayNetHandler.java:856) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:betterendforge.mixins.json:ClientPlayNetHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:90) ~[?:?] {re:classloading}
		at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:14) ~[?:?] {re:classloading}
		at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
		at net.minecraft.network.PacketThreadUtil$$Lambda$14058/1891836736.run(Unknown Source) ~[?:?] {}
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
		at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
		at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.54.jar:36.0] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/740735495.call(Unknown Source) [forge-1.16.5-36.0.54.jar:36.0] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	Caused by: java.nio.channels.ClosedChannelException
		at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:109) ~[?:1.8.0_51] {}
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:275) ~[?:1.8.0_51] {}
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:49) ~[?:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:952) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:945) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem.getDataPos(ZipFileSystem.java:931) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem.access$400(ZipFileSystem.java:80) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.<init>(ZipFileSystem.java:1472) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem.getInputStream(ZipFileSystem.java:1402) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:547) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_51] {}
		at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_51] {}
		at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.ModJarURLHandler$ModJarURLConnection.getInputStream(ModJarURLHandler.java:87) ~[forge-1.16.5-36.0.54.jar:36.0] {}
		at cpw.mods.modlauncher.TransformingClassLoader$AutoURLConnection.<init>(TransformingClassLoader.java:174) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-8.0.9.jar:?] {}
		... 32 more

**Comment by tweakbsd** [comment]
I have the same error currently:

java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/client/model/IFChainBuffer

And It is in EntityDragonBase.java

`
        if (world.isRemote) {
            roll_buffer = new IFChainBuffer();  // Crash is here. 
            pitch_buffer = new IFChainBuffer();
            pitch_buffer_body = new IFChainBuffer();
            turn_buffer = new ReversedBuffer();
            tail_buffer = new ChainBuffer();
        }
`

**Comment by TheBv** [comment]
Does this happen on a dedicated server or locally?
Also any mods being used? I see @Aryashian is using OptiFine any more?
I was pretty certain that most of this is related to how IaF registers resources. If one of you could send me their complete mod list (shorter is of course better) so I can replicate the issue that'd be awesome since then I can try fix things.
I've never been able to recreate this or similar issues with just IaF installed + OptiFine :/

**Comment by MEULIEN** [comment]
It happens locally. It happened when I tried attacking a stage 4 dragon and now I get this error when trying to load the world. I tried unistalling and reinstalling the mod but it didn't work.

The mods that I am using are:
HT's TreeChop
Not Enough Crashes 
Wyrmroost
Prefab
ToroHealth
TerraForged
Placebo 
Citadel 
Alex's Mobs
YUNG's API  
Wither Skeleton Tweaks 
Mutant Beasts   
Cartographer
Sophisticated Backpacks
Guard Villagers
Apotheosis 
Sword Displays  
FPS Reducer 
Lost Trinkets 
BetterEnd Forge
Structure Gel API 
Repurposed Structures
Biomes O' Plenty 
Project: Vibrant Journeys
End Remastered
Valhelsia Structures
Lollipop 
Dungeons Plus
Macaw's Fences and Walls

**Comment by MEULIEN** [comment]
and 
Advanced Combat Remade  
Curios API 
Eidolon 
Collective
Camera Mod 
extraspace
Unbreakable
Mushroom Quest
Desolation
Passive Shield 
Majrusz's Progressive Difficulty
Project MMO  
Architectury 
FTB GUI Library
AI-Improvements
BetterBurning
YUNG's Better Mineshafts
GeckoLib
Neko’s Enchanted Books
Save My Stronghold
Mowzie's Mobs
Tons Of Enchantments
Spiders 2.0
Easy Magic 
Just Enough Items
Item Filters
Lithium
The Conjurer
Abnormals Core
Bayou Blues
Reap Mod 
Waystones
Comforts 
Artifacts
Configured
Dungeon Crawl 
Curio of Undying
Ice and Fire
Forge 
Bountiful 
Off Hand Combat
Subterranean Wilderness
Antique Atlas
CoFH Core
Ensorcellation
SwingThroughGrass
FTB Quests
Abundance
Easy Updates
Towers Of The Wild
Endless Oceans
Atmospheric
Glow Bats
Majrusz Library
Evolved RPG
Whisperwoods
Savage & Ravage
FastWorkbench
Polymorph  
Inventory HUD+
Caged Mobs
DropOff
FastFurnace
Feudal Weaponry
Vampirism
Enhanced Celestials
Aquaculture 2 
CosmeticArmorReworked

**Comment by TheBv** [comment]
Is this easily re-creatable? E.g if you load up a new world and spawn in a dragon and punch him does it happen again?

**Comment by MEULIEN** [comment]
For me yes, I tried going to a back-up and creating a new world, and the same this happened when I attacked the dragon, however the stage 1-3 dragons don't cause this issue.

**Comment by MEULIEN** [comment]
And also, 
When switching from peaceful to another difficulty, the lich, gordon, cyclops, and hydra do not spawn in their respective 'dungeons' in chunks that have already been generated.

**Comment by TheBv** [comment]
> 
> 
> And also,
> When switching from peaceful to another difficulty, the lich, gordon, cyclops, and hydra do not spawn in their respective 'dungeons' in chunks that have already been generated.

That's because they are a generation feature and generation only happens once. 

I wasn't able to recreate the crash you've been experiencing sadly...  I pretty much installed every mod you mentioned (there were some which I couldn't find immediately) but I had no luck so far. 
There is a PR over at alex' rats [mod](https://github.com/Alex-the-666/Rats/pull/595) which changes some things related to the pathfinding-threading but since all this code is based on the MineColonies mod and they haven't implemented such a workaround/fix I doubt that this is causing the issue... 
I'm a bit at a loss... Maybe @tweakbsd has more insights/ideas?

**Comment by tweakbsd** [comment]
@TheBv I'm also lost at the moment. I play with my own version of Ice and Fire everyday and that java.lang.NoClassDefFoundError came yesterday when I updated my codebase to reflect a more recent version of Alex repo. I have to go back 2 commits in my repository and then see what code I did update then I will know more and hopefully can contribute a fix via PR soon.

**Comment by MEULIEN** [comment]
I installed a few more performance enhancing mods, and now it works normally. I think the crash might just have been my computer not being able to handle the mods.

**Comment by TheBv** [comment]
@Aryashian I think this only switched in which order the mods are being loaded and that resolved the issue with the class not being found.
@tweakbsd one thing which would be cool if you could check would be changing things in the main IceAndFire.java file. You could look at my current [fork](https://github.com/TheBv/Ice_and_Fire/blob/3435d608b4298dd6405af718aff0c41e846cdb1a/src/main/java/com/github/alexthe666/iceandfire/IceAndFire.java) but the main interesting things would be changing [this](https://github.com/Alex-the-666/Ice_and_Fire/blob/da802ec910cd8026009e938a08a421ea9b29e11e/src/main/java/com/github/alexthe666/iceandfire/IceAndFire.java#L81) to safeRunForDist and in the setup() void using the already used event.enqueue function for everything else as well. No idea if that resolves the issue but those changes are what I believe to be possible causes.

**Comment by tweakbsd** [comment]
@TheBv I have gone back 2 commits before I had the issue today and imported small code changes step after step. But I couldn't reproduce it anymore which is strange. But I changed my player position in that world where it happened and that's probably why it doesn't trigger anymore. On new worlds I never had that. But I'm on your page, changes you mentioned are a good measure to prevent such crashes by enqueuing work on the correct queue.

**Comment by taz4270** [comment]
The same happens here https://pastebin.com/Za4K4Puj

**Comment by AlexModGuy** [comment]
#3938
