### ISSUE TITLE
Crash when hit enemy (dragon or cyclop) [iceandfire-2.1.5-1.16.4]

### ISSUE THREAD

**Issue by Sher997** [Alex-the-666/Ice_and_Fire#3760]
When i hit a enemy (dead dragon too) Minecraft crash

CRASHLOG HERE

java.lang.NullPointerException: Unexpected error
	at vazkii.ambience.Util.Handlers.EventHandlers.playInstant(EventHandlers.java:194) ~[?:1.16.4-1.0.1] {re:classloading}
	at vazkii.ambience.Util.Handlers.EventHandlersServer.onPlayerAttackEvent(EventHandlersServer.java:260) ~[?:1.16.4-1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_244_EventHandlersServer_onPlayerAttackEvent_AttackEntityEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2593/1436728668.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:765) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1044) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:fml:backpacked:player_init,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimapfair:xaero_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimapfair:xaero_playerentity_iswearing,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_78764_a(PlayerController.java:352) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:twoplayersonehorse.mixins.json:PlayerControllerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1305) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.4.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$458/1105958076.call(Unknown Source) [forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

**Comment by Sher997** [comment]
UPDATE CRASH WHEN HIT EVERY ENEMY

**Comment by TheBv** [comment]
This has something to do with a mod from [vazkii](https://www.curseforge.com/members/vazkii/projects) and probably not with ice and fire.

**Comment by AlexModGuy** [comment]
> vazkii.ambience
not my mod crashing
