### ISSUE TITLE
Console spam error[latest iceandfire-2.1.6-1.16.4]

### ISSUE THREAD

**Issue by Jordan231111** [Alex-the-666/Ice_and_Fire#3761]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
When loading new chunks that have dragons. Console spam occurs.
**To Reproduce**
1. create any multiplayer world
2.  load chunks where there are dragons
3. Console spam on server. 

**Expected behavior**
No console spam or weird errors
**Screenshots**
[03Apr2021 07:56:45.233] [Ice and Fire Pathfinding Worker #0/INFO] [com.github.alexthe666.iceandfire.IceAndFire/]: Pathfinding from [-681,182,-4605] away from [-681,182,-4605]
[03Apr2021 07:56:45.283] [Server thread/ERROR] [com.github.alexthe666.iceandfire.IceAndFire/CATCHING]: Catching
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_282]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_282]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.processCompletedCalculationResult(AdvancedPathNavigate.java:387) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75501_e(AdvancedPathNavigate.java:211) ~[iceandfire:2.1.6-1.16.4]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:831) ~[iceandfire:2.1.6-1.16.4]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:1002) ~[iceandfire:2.1.6-1.16.4]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.StackOverflowError
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.isPassable(AbstractPathJob.java:1127) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.isPassableBB(AbstractPathJob.java:1097) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.checkHeadBlock(AbstractPathJob.java:994) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.getGroundHeight(AbstractPathJob.java:828) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:706) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.performJumpPointSearch(AbstractPathJob.java:776) ~[iceandfire:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:770) ~[iceandfire:2.1.6-1.16.4]

**Additional context**

**Comment by AlexModGuy** [comment]
fixed in dev
