### ISSUE TITLE
[1.12.2] Ice and Fire Dragon Base Issue

### ISSUE THREAD

**Issue by RexNanorum** [Alex-the-666/Ice_and_Fire#3808]
Following issue: I am playing on a Server with my Friends and we were searching for Dragons, (yes we found one after some time) when we got kicked one by one and we can't rejoin the server anymore. After looking into the Crash Log, it said something about EntityDragonBase. I can't find a way to "show" what the issue is with a screenshot, it just keeps on kicking me before I can see a thing. 

Time: 4/18/21 10:54 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.isSleeping(EntityDragonBase.java:854)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.canMove(EntityDragonBase.java:957)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_191986_a(EntityDragonBase.java:1786)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1497)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.func_70636_d(EntityFireDragon.java:148)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1463)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.isSleeping(EntityDragonBase.java:854)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.canMove(EntityDragonBase.java:957)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_191986_a(EntityDragonBase.java:1786)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1497)
	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.func_70636_d(EntityFireDragon.java:148)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1463)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:firedragon (com.github.alexthe666.iceandfire.entity.EntityFireDragon)
	Entity ID: 946
	Entity Name: Fire Dragon
	Entity's Exact location: 40.71, 20.38, 488.53
	Entity's Block location: World: (40,20,488), Chunk: (at 8,1,8 in 2,30; contains blocks 32,0,480 to 47,255,495), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RexNanorum'/883, l='MpServer', x=-90.11, y=77.37, z=346.39]]
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-164,64,277), Chunk: (at 12,4,5 in -11,17; contains blocks -176,0,272 to -161,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 276456 game time, 276456 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 75 total; [EntityPlayerSP['RexNanorum'/883, l='MpServer', x=-90.11, y=77.37, z=346.39], EntityCrab['Crab'/896, l='MpServer', x=-110.48, y=72.00, z=404.28], EntitySheep['Sheep'/897, l='MpServer', x=-116.37, y=77.00, z=421.19], EntityChicken['Chicken'/899, l='MpServer', x=-165.82, y=72.00, z=423.73], EntityBat['Bat'/262, l='MpServer', x=-106.82, y=44.57, z=324.32], EntityCreeper['Creeper'/263, l='MpServer', x=-111.50, y=27.00, z=354.50], EntityCreeper['Creeper'/264, l='MpServer', x=-110.30, y=43.30, z=356.70], EntitySheep['Sheep'/265, l='MpServer', x=-99.25, y=75.00, z=356.77], EntityZombie['Zombie'/266, l='MpServer', x=-106.50, y=51.00, z=381.50], EntityCrab['Crab'/267, l='MpServer', x=-101.55, y=65.00, z=386.17], EntitySquid['Squid'/278, l='MpServer', x=-88.60, y=52.36, z=315.44], EntitySquid['Squid'/279, l='MpServer', x=-81.85, y=52.21, z=316.60], EntityZombie['Zombie'/280, l='MpServer', x=-94.65, y=24.00, z=332.90], EntityZombie['Zombie'/281, l='MpServer', x=-94.30, y=24.00, z=333.70], EntityZombie['Zombie'/282, l='MpServer', x=-94.50, y=24.00, z=330.50], EntityZombie['Zombie'/283, l='MpServer', x=-92.50, y=24.00, z=325.50], EntitySpider['Spider'/284, l='MpServer', x=-95.50, y=63.00, z=383.50], EntityBat['Bat'/288, l='MpServer', x=-82.99, y=37.71, z=307.00], EntitySquid['Squid'/289, l='MpServer', x=-84.71, y=57.40, z=311.42], EntityCreeper['Creeper'/290, l='MpServer', x=-74.20, y=74.00, z=353.50], EntitySheep['Sheep'/932, l='MpServer', x=-137.45, y=76.00, z=415.55], EntityBladeStand['entity.BladeStand.name'/167, l='MpServer', x=-228.79, y=67.00, z=363.84], EntitySquid['Squid'/297, l='MpServer', x=-50.94, y=55.80, z=294.60], EntityCrab['Crab'/298, l='MpServer', x=-48.50, y=63.00, z=373.50], EntityFireDragon['Fire Dragon'/946, l='MpServer', x=40.71, y=20.38, z=488.53], EntityZombieVillager['Zombie Villager'/307, l='MpServer', x=-42.50, y=33.00, z=317.24], EntityZombieVillager['Zombie Villager'/308, l='MpServer', x=-43.26, y=32.00, z=310.41], EntityBat['Bat'/309, l='MpServer', x=-36.47, y=26.54, z=372.33], EntitySquid['Squid'/310, l='MpServer', x=-37.24, y=50.48, z=371.18], EntitySquid['Squid'/311, l='MpServer', x=-39.61, y=50.81, z=378.04], EntityCorpse['Corpse'/184, l='MpServer', x=-195.00, y=48.00, z=220.50], EntitySquid['Squid'/312, l='MpServer', x=-36.37, y=59.60, z=385.81], EntityCreeper['Creeper'/1080, l='MpServer', x=-30.50, y=29.00, z=370.50], EntitySquid['Squid'/313, l='MpServer', x=-35.40, y=52.17, z=386.60], EntityCreeper['Creeper'/1081, l='MpServer', x=-29.50, y=32.00, z=370.50], EntityCreeper['Creeper'/1082, l='MpServer', x=-21.58, y=40.00, z=374.18], EntityCreeper['Creeper'/1090, l='MpServer', x=-24.01, y=39.33, z=366.50], EntityCreeper['Creeper'/1091, l='MpServer', x=-27.51, y=39.00, z=364.83], EntitySheep['Sheep'/1096, l='MpServer', x=-99.21, y=75.00, z=418.72], EntityZombie['Zombie'/1097, l='MpServer', x=-16.50, y=46.00, z=326.50], EntityBat['Bat'/330, l='MpServer', x=-35.26, y=27.61, z=327.84], EntitySpider['Spider'/1098, l='MpServer', x=-21.71, y=46.00, z=326.54], EntitySkeleton['Skeleton'/1099, l='MpServer', x=-20.70, y=45.64, z=326.30], EntityBladeStand['entity.BladeStand.name'/203, l='MpServer', x=-176.26, y=67.00, z=381.48], EntityBat['Bat'/1106, l='MpServer', x=-12.03, y=48.35, z=330.80], EntityChicken['Chicken'/214, l='MpServer', x=-160.44, y=72.00, z=396.15], EntityXPOrb['Experience Orb'/983, l='MpServer', x=-219.76, y=59.00, z=431.94], EntityBat['Bat'/222, l='MpServer', x=-146.43, y=29.10, z=323.25], EntitySkeleton['Skeleton'/223, l='MpServer', x=-146.88, y=26.00, z=324.44], EntityCreeper['Creeper'/224, l='MpServer', x=-150.50, y=30.00, z=327.50], EntityCreeper['Creeper'/225, l='MpServer', x=-149.61, y=30.00, z=328.01], EntityBat['Bat'/226, l='MpServer', x=-145.67, y=27.47, z=326.02], EntityBat['Bat'/227, l='MpServer', x=-149.50, y=30.00, z=326.35], EntityZombie['Zombie'/228, l='MpServer', x=-155.50, y=30.00, z=342.50], EntitySkeleton['Skeleton'/229, l='MpServer', x=-151.78, y=11.00, z=357.50], EntityCreeper['Creeper'/230, l='MpServer', x=-152.50, y=72.00, z=394.50], EntityItem['item.item.bone'/231, l='MpServer', x=-144.26, y=67.00, z=396.72], EntityItem['item.item.tconstruct.book'/236, l='MpServer', x=-130.68, y=68.00, z=301.35], EntityCreeper['Creeper'/237, l='MpServer', x=-138.50, y=34.00, z=316.30], EntityCreeper['Creeper'/238, l='MpServer', x=-136.30, y=33.00, z=315.86], EntityBat['Bat'/239, l='MpServer', x=-136.54, y=34.10, z=317.11], EntityZombie['Zombie'/240, l='MpServer', x=-141.30, y=19.59, z=323.39], EntitySheep['Sheep'/241, l='MpServer', x=-134.29, y=70.00, z=360.51], EntitySheep['Sheep'/242, l='MpServer', x=-141.52, y=70.00, z=373.80], EntityItem['item.item.arrow'/244, l='MpServer', x=-143.42, y=67.00, z=396.57], EntitySheep['Sheep'/884, l='MpServer', x=-135.33, y=77.00, z=422.80], EntityCreeper['Creeper'/247, l='MpServer', x=-118.50, y=11.00, z=361.50], EntityChicken['Chicken'/248, l='MpServer', x=-123.51, y=73.00, z=354.05], EntityItem['item.item.egg'/249, l='MpServer', x=-122.51, y=72.00, z=352.93], EntityChicken['Chicken'/250, l='MpServer', x=-123.85, y=74.00, z=373.74], EntityItem['item.item.egg'/251, l='MpServer', x=-124.51, y=74.00, z=374.15], EntityChicken['Chicken'/252, l='MpServer', x=-117.46, y=72.00, z=379.78], EntityChicken['Chicken'/253, l='MpServer', x=-116.67, y=73.00, z=391.18], EntityItem['item.item.egg'/254, l='MpServer', x=-121.12, y=74.00, z=386.31], EntitySpider['Spider'/255, l='MpServer', x=-114.50, y=72.00, z=394.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	
	
	I hope I can help others and the mod by submitting this, I don't have a clue how to solve this. Rex

**Comment by AlexModGuy** [comment]
Another mod is writing entity data trackers incorrectly - there is nothing we can do
