### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/Ice_and_Fire#3878]
This happened randomly when placing blocks in the game, but I wanted to post it.

[22:34:44] [Server thread/FATAL]: Preparing crash report with UUID 37c032d0-4b06-4f99-8294-caf863a632e8
[22:34:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$24750/1889961752.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/world/structure/GorgonTempleStructure$Start
	at com.github.alexthe666.iceandfire.world.structure.GorgonTempleStructure.func_214557_a(GorgonTempleStructure.java:38) ~[?:2.1.6-1.16.4]
	at net.minecraft.world.gen.feature.structure.Structure.func_236387_a_(Structure.java:217) ~[?:?]
	at net.minecraft.world.gen.feature.structure.Structure.func_236393_a_(Structure.java:107) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_235967_a_(ChunkSerializer.java:438) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222656_a(ChunkSerializer.java:170) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkLoad$14(ChunkManager.java:619) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$24955/1906082115.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:514) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:522) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:130) ~[?:?]
	at net.minecraft.world.chunk.AbstractChunkProvider.func_217205_a(SourceFile:16) ~[?:?]
	at net.minecraft.world.World.func_175647_a(World.java:766) ~[?:?]
	at net.minecraft.world.IEntityReader.func_217357_a(SourceFile:51) ~[?:?]
	at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforgeInput.lureDragons(TileEntityDragonforgeInput.java:89) ~[?:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforgeInput.func_73660_a(TileEntityDragonforgeInput.java:54) ~[?:2.1.6-1.16.4]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.world.structure.GorgonTempleStructure$Start
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at com.github.alexthe666.iceandfire.world.structure.GorgonTempleStructure.func_214557_a(GorgonTempleStructure.java:38) ~[?:2.1.6-1.16.4]
	at net.minecraft.world.gen.feature.structure.Structure.func_236387_a_(Structure.java:217) ~[?:?]
	at net.minecraft.world.gen.feature.structure.Structure.func_236393_a_(Structure.java:107) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_235967_a_(ChunkSerializer.java:438) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222656_a(ChunkSerializer.java:170) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkLoad$14(ChunkManager.java:619) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$24955/1906082115.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:514) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:522) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:130) ~[?:?]
	at net.minecraft.world.chunk.AbstractChunkProvider.func_217205_a(SourceFile:16) ~[?:?]
	at net.minecraft.world.World.func_175647_a(World.java:766) ~[?:?]
	at net.minecraft.world.IEntityReader.func_217357_a(SourceFile:51) ~[?:?]
	at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforgeInput.lureDragons(TileEntityDragonforgeInput.java:89) ~[?:2.1.6-1.16.4]
	at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforgeInput.func_73660_a(TileEntityDragonforgeInput.java:54) ~[?:2.1.6-1.16.4]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
	Suppressed: java.lang.ClassNotFoundException: Failed to find class bytes for com.github.alexthe666.iceandfire.world.structure.GorgonTempleStructure$Start
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:260) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
		at com.github.alexthe666.iceandfire.world.structure.GorgonTempleStructure.func_214557_a(GorgonTempleStructure.java:38) ~[?:2.1.6-1.16.4]
		at net.minecraft.world.gen.feature.structure.Structure.func_236387_a_(Structure.java:217) ~[?:?]
		at net.minecraft.world.gen.feature.structure.Structure.func_236393_a_(Structure.java:107) ~[?:?]
		at net.minecraft.world.chunk.storage.ChunkSerializer.func_235967_a_(ChunkSerializer.java:438) ~[?:?]
		at net.minecraft.world.chunk.storage.ChunkSerializer.func_222656_a(ChunkSerializer.java:170) ~[?:?]
		at net.minecraft.world.server.ChunkManager.lambda$chunkLoad$14(ChunkManager.java:619) ~[?:?]
		at net.minecraft.world.server.ChunkManager$$Lambda$24955/1906082115.get(Unknown Source) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?]
		at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:514) ~[?:?]
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?]
		at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:522) ~[?:?]
		at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) ~[?:?]
		at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:130) ~[?:?]
		at net.minecraft.world.chunk.AbstractChunkProvider.func_217205_a(SourceFile:16) ~[?:?]
		at net.minecraft.world.World.func_175647_a(World.java:766) ~[?:?]
		at net.minecraft.world.IEntityReader.func_217357_a(SourceFile:51) ~[?:?]
		at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforgeInput.lureDragons(TileEntityDragonforgeInput.java:89) ~[?:2.1.6-1.16.4]
		at com.github.alexthe666.iceandfire.entity.tile.TileEntityDragonforgeInput.func_73660_a(TileEntityDragonforgeInput.java:54) ~[?:2.1.6-1.16.4]
		at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
		at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
		at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
		at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
		at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
		at net.minecraft.server.MinecraftServer$$Lambda$24750/1889961752.run(Unknown Source) [?:?]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
	Caused by: java.nio.channels.ClosedChannelException
		at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:109) ~[?:1.8.0_51]
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:275) ~[?:1.8.0_51]
		at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:49) ~[?:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:952) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:945) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem.getDataPos(ZipFileSystem.java:931) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem.access$400(ZipFileSystem.java:80) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.<init>(ZipFileSystem.java:1472) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem.getInputStream(ZipFileSystem.java:1402) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:547) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_51]
		at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_51]
		at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_51]
		at net.minecraftforge.fml.loading.ModJarURLHandler$ModJarURLConnection.getInputStream(ModJarURLHandler.java:87) ~[forge-1.16.5-36.0.42.jar:36.0]
		at cpw.mods.modlauncher.TransformingClassLoader$AutoURLConnection.<init>(TransformingClassLoader.java:174) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-8.0.9.jar:?]
		... 31 more

**Comment by AlexModGuy** [comment]
#3938
