### ISSUE TITLE
java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.block.BlockGoldPile 1.16.5

### ISSUE THREAD

**Issue by PrimordialGod** [Alex-the-666/Ice_and_Fire#3885]
Help me, I have neither citadel or any of alex's mods in the mod folder and reset minecraft yet i keep getting this crash error

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/18/21 7:17 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/block/BlockGoldPile
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_51] {}
	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry$$Lambda$8513/14980151.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2900/1629241006.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2901/333447190.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.23.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/1480816641.call(Unknown Source) [forge-1.16.5-36.1.23.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.block.BlockGoldPile
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 36 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
		at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_51] {}
		at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_51] {}
		at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_51] {}
		at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
		at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
		at net.minecraftforge.registries.ObjectHolderRegistry$$Lambda$8513/14980151.accept(Unknown Source) ~[?:?] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
		at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2900/1629241006.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2901/333447190.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.23.jar:36.1] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/1480816641.call(Unknown Source) [forge-1.16.5-36.1.23.jar:36.1] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_51] {}
	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry$$Lambda$8513/14980151.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2900/1629241006.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2901/333447190.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.23.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$491/1480816641.call(Unknown Source) [forge-1.16.5-36.1.23.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
Mod List: 
		naturesminerals-0.8-1.16.5-36.1.0.jar             |Nature's Minerals             |natureminerals                |0.8.0               
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              
		moremcmeta-1.16.4-2.1.0.jar                       |MoreMcmeta                    |moremcmeta                    |1.16.4-2.1.0        
		randomloot-1.16.5-2.3.9.jar                       |Random Loot Mod               |randomloot                    |1.16.5-2.3.9        
		UnionLib-1.16.5-3.3.2.jar                         |UnionLib                      |unionlib                      |3.3.2               
		TonsOfEnchants-0.6v.jar                           |Tons Of Enchantments          |tonsofenchants                |1.16.5-0.6          
		jei-1.16.5-7.7.0.98.jar                           |Just Enough Items             |jei                           |7.7.0.98            
		prefab-1.6.5.3.jar                                |Prefab                        |prefab                        |1.6.5.3             
		AttributeFix-1.16.5-10.1.2.jar                    |AttributeFix                  |attributefix                  |10.1.2              
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             
		wonderful-enchantments-1.16.4-1.3.0.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.3.0               
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        
		shockmetal-1.16.5-1.2.0.jar                       |Shock Metal                   |shockmetal                    |1.2.0               
		Clumps-6.0.0.22.jar                               |Clumps                        |clumps                        |6.0.0.22            
		OresAboveDiamonds-1.16.4-v6.3.3.jar               |Ores Above Diamonds           |oresabovediamonds             |6.3.3               
		mgui-1.16.5-3.2.0.jar                             |mgui                          |mgui                          |3.2.0               
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               
		Placebo-1.16.4-4.4.5.jar                          |Placebo                       |placebo                       |4.4.5               
		TravelersBackpack-1.16.5-5.4.1.jar                |Traveler's Backpack           |travelersbackpack             |5.4.1               
		Bookshelf-1.16.5-10.0.8.jar                       |Bookshelf                     |bookshelf                     |10.0.8              
		BadMobs-1.16.5-9.0.3.jar                          |BadMobs                       |badmobs                       |9.0.3               
		sophisticatedbackpacks-1.16.4-2.4.0.259.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        
		u_team_core-1.16.5-3.2.1.195.jar                  |U Team Core                   |uteamcore                     |3.2.1.195           
		LimitMobSpawn-16.6.jar                            |Limit Mob Spawn               |limit-mob-spawn               |16.6                
		oreUnify-1.0.1(1.16.4)(1.16.5).jar                |Ore Unify                     |ore_unify                     |1.0.0               
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  
		WAWLA-1.16.5-8.0.3.jar                            |WAWLA                         |wawla                         |8.0.3               
		JustEnoughResources-1.16.4-0.12.0.107.jar         |Just Enough Resources         |jeresources                   |0.12.0.107          
		gems-1.16.5-1.7.2.jar                             |The Gems Project              |gems                          |1.16.5-1.7.2        
		forge-1.16.5-36.1.23-universal.jar                |Forge                         |forge                         |36.1.23             
		shetiphiancore-1.16-3.8.5.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.5               
		LostTrinkets-1.16.5-0.1.27.jar                    |Lost Trinkets                 |losttrinkets                  |0.1.27              
		blame-1.16.5-3.0.2-forge.jar                      |Blame!                        |blame                         |1.16.5-3.0.2-forge  
		twilightforest-1.16.5-4.0.435-universal.jar       |The Twilight Forest           |twilightforest                |NONE                
		refinedstorage-1.9.12.jar                         |Refined Storage               |refinedstorage                |1.9.12              
		Upgraded+Netherite+1.16.5+-+1.9.3.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               
		GeoSmelt-2.83.jar                                 |GeoSmelt                      |geosmelt                      |2.82                
		dungeonsarise1.16.5-1.2.72a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.72a             
		ZonisMod-1.16.5-BETA-1.0.9.jar                    |Zoni's Mod                    |zoni_mod                      |1.1.0               
		forge-1.16.5-36.1.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               
		thermal_foundation-1.16.4-1.2.0.jar               |Thermal Series                |thermal                       |1.2.0               
		TConstruct-1.16.5-3.0.3.152.jar                   |Tinkers' Construct            |tconstruct                    |3.0.3.152           
		EnchantmentDescriptions-1.16.5-7.0.8.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.8               
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                
		silent-lib-1.16.3-4.9.6.jar                       |Silent Lib                    |silentlib                     |4.9.6               
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             
		allthemodium-1.4.5-1.16.5-36.1.0.jar              |Allthemodium                  |allthemodium                  |1.4.5-1.16.5-36.1.0 
		rpgbackpacks-1.16.5-1.0.2.jar                     |RPG Backpacks                 |rpg_backpacks                 |1.0.2               
		Piggybanks-1.16.5-1.0.2.jar                       |Piggy Banks                   |piggybanks                    |$1.16.5-1.0.2       
		HealthCanisters+1.2.2.jar                         |Heart Canisters               |heartcanisters                |1.2.2               
		storage_overhaul-1.16.5-1.0.4.jar                 |Storage Overhaul              |storage_overhaul              |1.16.5-1.0.4        
		majrusz-library-1.16.4-1.5.0.jar                  |Majrusz Library               |majrusz_library               |1.5.0               
		easy_villagers-1.16.5-1.0.10.jar                  |Easy Villagers                |easy_villagers                |1.16.5-1.0.10       
		EnchantmentMachine-1.16.4-1.0.1.jar               |Enchantment machine           |enchantmentmachine            |1.0.1               
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      
		Artifacts-1.16.5-2.8.4.jar                        |Artifacts                     |artifacts                     |1.16.5-2.8.4        
		relics-0.1.14.jar                                 |Relics                        |relics                        |0.1.14              
		omnis-1.16.5-1.1.2.jar                            |Omnis                         |omnis                         |1.16.5-1.0          
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           
		Mantle-1.16.5-1.6.97.jar                          |Mantle                        |mantle                        |1.6.97              
		armorpointspp-1.16.5-2.0.0-rc1.jar                |ArmorPoints++                 |armorpointspp                 |1.16.5-2.0.0-rc1    
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        
		collective-1.16.5-2.25.jar                        |Collective                    |collective                    |2.25                
		multibeds-1.16-1.7.9.jar                          |Multi-Beds                    |multibeds                     |1.7.9               
		thermal_expansion-1.16.4-1.2.0.jar                |Thermal Expansion             |thermal_expansion             |1.2.0               
		lostcities-1.16-4.0.9-beta.jar                    |LostCities                    |lostcities                    |1.16-4.0.9-beta     
		Gobber2-Forge-1.16.5-2.3.50.jar                   |Gobber 2                      |gobber2                       |2.3.48              
		obfuscate-0.6.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.0               
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               
		ModernUI-1.16.5-2.5.1.86-universal.jar            |Modern UI                     |modernui                      |2.5.1.86            
		Babel-1.0.5.jar                                   |Babel                         |babel                         |1.0.5               
		geckolib-forge-1.16.5-3.0.35.jar                  |GeckoLib                      |geckolib3                     |3.0.35              
		lootbagmod-1.16.5-2.2.0.jar                       |Loot Bag Mod                  |lootbagmod                    |1.16.5-2.2.0        
		treasure-bags-1.16.3-1.4.0.jar                    |Treasure Bags                 |treasurebags                  |1.4.0

**Comment by AlexModGuy** [comment]
#3938
