### ISSUE TITLE
Server crashing due to a pixie (apparently) [2.1.6]

### ISSUE THREAD

**Issue by Vravinite** [Alex-the-666/Ice_and_Fire#3910]
**Describe the bug**
I open my server, and after a while (since I can't monitor all players so IDK exactly what happened) it just kills itself.

**To Reproduce**
1. Start server
2. Load a certain area
3. See error

**Expected behavior**
Not crashing

**Screenshots**
`
-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.ai.PixieAIPickupItem.<init>(PixieAIPickupItem.java:39) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.ai.PixieAIPickupItem.<init>(PixieAIPickupItem.java:33) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.ai.PixieAIPickupItem.<init>(PixieAIPickupItem.java:29) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityPixie.func_184651_r(EntityPixie.java:270) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:120) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.AgeableEntity.<init>(SourceFile:28) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.<init>(AnimalEntity.java:37) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.passive.TameableEntity.<init>(SourceFile:31) ~[?:?] {re:mixin,re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityPixie.<init>(EntityPixie.java:82) ~[iceandfire:2.1.6-1.16.4] {re:classloading}
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:445) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityType.func_220337_b_(EntityType.java:456) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraft.entity.EntityType.func_220330_a(EntityType.java:455) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityType.func_220343_b(EntityType.java:513) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.entity.EntityType.func_220335_a(EntityType.java:495) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:384) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222648_b(ChunkSerializer.java:133) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:457) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorldChunk,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.func_219237_a_(ChunkManager.java:582) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.entity_sync.MixinThreadedAnvilChunkStorage_E,pl:mixin:APP:imm_ptl_mixins.json:common.chunk_sync.MixinThreadedAnvilChunkStorage_C,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?] {re:classloading,re:mixin}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:569) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.entity_sync.MixinThreadedAnvilChunkStorage_E,pl:mixin:APP:imm_ptl_mixins.json:common.chunk_sync.MixinThreadedAnvilChunkStorage_C,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_221] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:514) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:267) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerChunkManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:722) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Vravinite'/179, l='ServerWorld minecraft:overworld world', x=-853.38, y=83.03, z=281.61]]
	Chunk stats: ServerChunkCache: 4690
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,68,153), Chunk: (at 0,4,9 in -12,9; contains blocks -192,0,144 to -177,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1053250 game time, 932262 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 98850 (now: false), thunder time: 81045 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}
`

**Additional context**
Sorry

**Comment by joeyjumper94** [comment]
this looks like the crash was from a pixie

**Comment by AlexModGuy** [comment]
#3938
