### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION]

### ISSUE THREAD

**Issue by Donnythedealer17** [Alex-the-666/Ice_and_Fire#3983]
Apologies if this has been discussed before but ive been searching all day and havent found a solution, im running a fair sized modpack for LAN games and on startup Ice and fire will crash, not sure if its the version of forge or even the mod itself that im using thats the problem but I would definitely appreciate some help! Crash report is below

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/17/21 7:52 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.32-launcher.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_291] {}
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/github/alexthe666/citadel/server/entity/EntityPropertiesHandler
		at com.github.alexthe666.iceandfire.entity.IafEntityRegistry.setup(IafEntityRegistry.java:100) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
		at com.github.alexthe666.iceandfire.CommonProxy.setup(CommonProxy.java:175) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
		at com.github.alexthe666.iceandfire.IceAndFire.setup(IceAndFire.java:165) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:mixin,re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

	Mod File: Ice-and-Fire-Mod-1.16.5.jar
	Failure message: Ice and Fire (iceandfire) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: com/github/alexthe666/citadel/server/entity/EntityPropertiesHandler
	Mod Version: 2.1.5-1.16.4
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.ClassNotFoundException: com.github.alexthe666.citadel.server.entity.EntityPropertiesHandler
Stacktrace:
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] {}
	at com.github.alexthe666.iceandfire.entity.IafEntityRegistry.setup(IafEntityRegistry.java:100) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.CommonProxy.setup(CommonProxy.java:175) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at com.github.alexthe666.iceandfire.IceAndFire.setup(IceAndFire.java:165) ~[iceandfire:2.1.5-1.16.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:mixin,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3798434656 bytes (3622 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5120m -Xmx5120m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.32-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.1.32-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.32-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.32-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.32
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.12.1
	Mod List: 
		mowziesmobs-1.5.18.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.18              |SIDED_SETU|Manifest: NOSIGNATURE
		ftb-janitor-1604.1.1.19.jar                       |FTB Janitor                   |ftbjanitor                    |1604.1.1.19         |SIDED_SETU|Manifest: NOSIGNATURE
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |SIDED_SETU|Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		ftb-essentials-1604.1.0.13.jar                    |FTB Essentials                |ftbessentials                 |1604.1.0.13         |SIDED_SETU|Manifest: NOSIGNATURE
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |SIDED_SETU|Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |SIDED_SETU|Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |SIDED_SETU|Manifest: NOSIGNATURE
		wonderful-enchantments-1.16.4-1.3.3.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.3.3               |SIDED_SETU|Manifest: NOSIGNATURE
		KleeSlabs_1.16.5-9.2.1.jar                        |KleeSlabs                     |kleeslabs                     |9.2.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |SIDED_SETU|Manifest: NOSIGNATURE
		All+the+Woods-1.16.5-0.1.jar                      |All the Woods                 |allthewoods                   |1                   |SIDED_SETU|Manifest: NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Controlling-7.0.0.22.jar                          |Controlling                   |controlling                   |7.0.0.22            |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.7.1-1.16.5.jar                          |Citadel                       |citadel                       |1.7.1               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.10.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.1              |SIDED_SETU|Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |SIDED_SETU|Manifest: NOSIGNATURE
		configured-1.1.0-1.16.5.jar                       |Configured                    |configured                    |1.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |SIDED_SETU|Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Coins-1.16.5-6.0.2.jar                            |Coins                         |coins                         |6.0.2               |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		reliquary-1.16.5-1.3.5.1098.jar                   |Reliquary                     |xreliquary                    |1.16.5-1.3.5.1098   |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-doors-1.0.3-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |SIDED_SETU|Manifest: NOSIGNATURE
		Ice-and-Fire-Mod-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |ERROR     |Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.2.0-beta.3.jar              |Paraglider                    |paraglider                    |1.3.2.0-beta.3      |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.32-universal.jar                |Forge                         |forge                         |36.1.32             |SIDED_SETU|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |SIDED_SETU|Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.13.0.jar                 |Supplementaries               |supplementaries               |1.16.5-0.13.0       |SIDED_SETU|Manifest: NOSIGNATURE
		corpse-1.16.5-1.0.5.jar                           |Corpse                        |corpse                        |1.16.5-1.0.5        |SIDED_SETU|Manifest: NOSIGNATURE
		CraftingTweaks_1.16.3-12.2.0.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.0              |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.32-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |SIDED_SETU|Manifest: NOSIGNATURE
		ensorcellation-1.16.4-1.2.0.jar                   |Ensorcellation                |ensorcellation                |1.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-bridges-1.0.5-mc1.16.5-4.jar                  |Macaw's Bridges               |mcwbridges                    |1.0.5               |SIDED_SETU|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.4        |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.8.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.8               |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		ftb-ranks-1604.1.1.11.jar                         |FTB Ranks                     |ftbranks                      |1604.1.1.11         |SIDED_SETU|Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |SIDED_SETU|Manifest: NOSIGNATURE
		rpgbackpacks-1.16.5-1.1.2.jar                     |RPG Backpacks                 |rpg_backpacks                 |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		CreativeCore_v2.2.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.2-mc1.16.5.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		archers_paradox-1.16.4-1.2.0.jar                  |Archer's Paradox              |archers_paradox               |1.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |SIDED_SETU|Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |SIDED_SETU|Manifest: NOSIGNATURE
		majrusz-library-1.16.4-1.7.0.jar                  |Majrusz Library               |majrusz_library               |1.7.0               |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |SIDED_SETU|Manifest: NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |SIDED_SETU|Manifest: NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |SIDED_SETU|Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |SIDED_SETU|Manifest: NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |SIDED_SETU|Manifest: NOSIGNATURE
		horse_colors-1.16.5-1.6.0.2.jar                   |Realistic Horse Genetics      |horse_colors                  |1.16.5-1.6.0.2      |SIDED_SETU|Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |SIDED_SETU|Manifest: NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |SIDED_SETU|Manifest: NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |SIDED_SETU|Manifest: NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.50.jar                   |Gobber 2                      |gobber2                       |2.3.48              |SIDED_SETU|Manifest: NOSIGNATURE
		structurize-0.13.177-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.177-ALPHA      |SIDED_SETU|Manifest: NOSIGNATURE
		jeilotr-2.0.0-BETA.jar                            |JEI LOTR                      |jeilotr                       |2.0.0-BETA          |SIDED_SETU|Manifest: NOSIGNATURE
		minecolonies-0.14.221-BETA-universal.jar          |MineColonies                  |minecolonies                  |0.14.221-BETA       |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Project_MMO-1.16.5-3.58.2.jar                     |Project MMO                   |pmmo                          |1.16.5-3.58.2       |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-1.11.144-forge.jar                   |Architectury                  |architectury                  |1.11.144            |SIDED_SETU|Manifest: NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |SIDED_SETU|Manifest: NOSIGNATURE
		ftb-teams-1604.1.0.16-forge.jar                   |FTB Teams                     |ftbteams                      |1604.1.0.16         |SIDED_SETU|Manifest: NOSIGNATURE
		ftb-chunks-1605.2.3-build.75.jar                  |FTB Chunks                    |ftbchunks                     |1605.2.3-build.75   |SIDED_SETU|Manifest: NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |SIDED_SETU|Manifest: NOSIGNATURE
		ferritecore-2.0.4-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.4               |SIDED_SETU|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |SIDED_SETU|Manifest: NOSIGNATURE
		moredragoneggs-1.4.jar                            |More Dragon Eggs              |moredragoneggs                |1.4                 |SIDED_SETU|Manifest: NOSIGNATURE
		byg-1.2.9.jar                                     |Oh The Biomes You'll Go       |byg                           |1.2.9               |SIDED_SETU|Manifest: NOSIGNATURE
		lotr-1.16-renewed-4.3.jar                         |The Lord of the Rings Mod     |lotr                          |Renewed-4.3         |SIDED_SETU|Manifest: NOSIGNATURE
		smallships-1.16.5-1.8.4.jar                       |Small Ships Mod               |smallships                    |1.8.4               |SIDED_SETU|Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v3.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v3           |SIDED_SETU|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |SIDED_SETU|Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.2.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.2        |SIDED_SETU|Manifest: NOSIGNATURE
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.41.jar                  |GeckoLib                      |geckolib3                     |3.0.41              |SIDED_SETU|Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.18.6.jar                     |Ars Nouveau                   |ars_nouveau                   |1.18.6              |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 8eb056fa-6def-463d-959e-cfb7da759540

**Comment by Donnythedealer17** [comment]
I am also using the technic launcher as the platform for the modpack if that helps any

**Comment by TheBv** [comment]
If you want to run Ice and Fire version 2.1.5 you need a different older version of citadel. I don't exactly remember which one but I think you want version 1.6.2 or older.

**Comment by Donnythedealer17** [comment]
I solved this forge was just running funny with that particular version of Citadel and ice and fire I was running switched the versions and it runs great !
