### ISSUE TITLE
Pixie Crash ConcurrentModificationException

### ISSUE THREAD

**Issue by katubug** [Alex-the-666/Ice_and_Fire#401]
[crash-2018-01-03_16.01.47-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1601709/crash-2018-01-03_16.01.47-server.txt)

When this happened, I had just released a pixie from the Extra Utilities Golden Lasso, and was attempting to Lasso a Fire Dragon (smallish black one, 215hp).

**Comment by naqaden** [comment]
I can reproduce this by breaking a filled pixie jar block. If I'm standing adjacent to the jar and I have something they can steal, I'll crash the moment they're free. If I'm too far to immediately steal from, or I have nothing to steal, no crash.
<details>
<summary>Error:</summary><p>

```
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_192]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_192]
	at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:125) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678) ~[vq.class:?]
	at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178) ~[vd.class:?]
	at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43) ~[zv.class:?]
->	at com.github.alexthe666.iceandfire.entity.EntityPixie.onLivingUpdate(EntityPixie.java:231) ~[EntityPixie.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377) ~[vq.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zbb000(World.java:4117) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1759) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```
</p></details>
