### ISSUE TITLE
[ICE AND FIRE VERSION 2.1.8-1.16.5 (w/ Forge Magic Modpack)] Mod loading error has occurred 

### ISSUE THREAD

**Issue by Mewcenary** [Alex-the-666/Ice_and_Fire#4038]
![image](https://user-images.githubusercontent.com/85654348/123736706-7ebc7880-d856-11eb-9c39-50fde032d46e.png)

I had to delete 2.1.8 and go back to 2.1.7 to be able to play.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/28/21 9:10 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6722/1843794118.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6463/1891984436.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.29.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$473/1167916234.call(Unknown Source) [forge-1.16.4-35.1.29.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityAttributeCreationEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51] {}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51] {}
		at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51] {}
		at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51] {}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-3.0.5-service.jar:?] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$3164/1772641455.accept(Unknown Source) ~[?:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[?:35.1] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3034/521207494.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3144/1641677843.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	**Mod File: iceandfire-2.1.8-1.16.5.jar
	Failure message: Ice and Fire (iceandfire) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityAttributeCreationEvent
	Mod Version: 2.1.8-1.16.5**
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.EntityAttributeCreationEvent
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51] {}
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$3164/1772641455.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3034/521207494.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3144/1641677843.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 357827968 bytes (341 MB) / 2459959296 bytes (2346 MB) up to 5607784448 bytes (5348 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6016m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.29.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.29
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.29-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |CREATE_REG|NOSIGNATURE
		QuarkOddities-1_16_5.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |CREATE_REG|NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |CREATE_REG|NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|NOSIGNATURE
		Cucumber-1.16.4-4.1.5.jar                         |Cucumber Library              |cucumber                      |4.1.5               |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |CREATE_REG|NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |CREATE_REG|NOSIGNATURE
		Jade-1.16.4-2.7.1.jar                             |Jade                          |jade                          |2.7.1               |CREATE_REG|NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |CREATE_REG|NOSIGNATURE
		Botania-1.16.4-410.jar                            |Botania                       |botania                       |1.16.4-410          |CREATE_REG|NOSIGNATURE
		DoggyTalents-1.16.4-2.0.1.2.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.2             |CREATE_REG|NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |CREATE_REG|NOSIGNATURE
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |CREATE_REG|NOSIGNATURE
		Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimap                  |21.10.0.3           |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |CREATE_REG|NOSIGNATURE
		XaerosWorldMap_1.14.1_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.14.1              |CREATE_REG|NOSIGNATURE
		citadel-1.7.1-1.16.5.jar                          |Citadel                       |citadel                       |1.7.1               |CREATE_REG|NOSIGNATURE
		alexsmobs-1.8.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.8.1               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |CREATE_REG|NOSIGNATURE
		sit-1.16.2-v1.3.jar                               |Sit                           |sit                           |v1.3                |CREATE_REG|NOSIGNATURE
		Vampirism-1.16.4-1.7.12.jar                       |Vampirism                     |vampirism                     |1.7.12              |CREATE_REG|NOSIGNATURE
		iceandfire-2.1.8-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.8-1.16.5        |ERROR     |NOSIGNATURE
		BackTools-1.16.3-10.0.0.jar                       |Back Tools                    |backtools                     |10.0.0              |CREATE_REG|NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.27.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.27            |CREATE_REG|NOSIGNATURE
		iChunUtil-1.16.3-10.0.0.jar                       |iChunUtil                     |ichunutil                     |10.0.0              |CREATE_REG|NOSIGNATURE
		dynviewdist-1.7.jar                               |Dynamic view distance         |dynview                       |1.7                 |CREATE_REG|NOSIGNATURE
		mysticalworld-1.16.4-0.3.1.4.jar                  |Mystical World                |mysticalworld                 |1.16.4-0.3.1.4      |CREATE_REG|NOSIGNATURE
		forge-1.16.4-35.1.29-universal.jar                |Forge                         |forge                         |35.1.29             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |CREATE_REG|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |CREATE_REG|NOSIGNATURE
		BloodMagic-1.16.3-3.0.3-8.jar                     |Blood Magic                   |bloodmagic                    |1.16.3-3.0.3-8      |CREATE_REG|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |CREATE_REG|NOSIGNATURE
		veinmining-forge-1.16.5-0.11.jar                  |Vein Mining                   |veinmining                    |1.16.5-0.11         |CREATE_REG|NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |CREATE_REG|NOSIGNATURE
		ars_nouveau-1.16.4-1.10.6.jar                     |Ars Nouveau                   |ars_nouveau                   |1.10.6              |CREATE_REG|NOSIGNATURE
		GodlyVampirism-1.16.4-1.0.1.jar                   |Godly Vampirism               |godly-vampirism               |1.0.1               |CREATE_REG|NOSIGNATURE
		Dynamic-Surroundings-Mod-1.16.5.jar               |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |CREATE_REG|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		MysticalAgriculture-1.16.4-4.1.4.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.4               |CREATE_REG|NOSIGNATURE
		MysticalAgradditions-1.16.4-4.1.3.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.3               |CREATE_REG|NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 60e4312a-1cc6-4fd7-a657-ea9e06ad9ad5

**Comment by TheBv** [comment]
Update forge that should fix it!

**Comment by Mewcenary** [comment]
> Update forge that should fix it!

Ty! I wasn't sure lol.  Hopefully, Alex will update the Modpack to 16.5 on the Forge app since all the mods work on 16.5 just fine (my experience)
