### ISSUE TITLE
minecraft:pixie_house support block removal casues local server crash.

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Alex-the-666/Ice_and_Fire#406]
[Error Log Here](https://pastebin.com/ztEG8n7K)
_StackTrace_
`Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1008)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)`

**Steps to Reproduce**
@Alex-the-666 Destroy the block below any `minecraft:pixie_house` and the local server with shutdown with this error. This can be the player or by another entity via mob grief.

**Comment by BeardStroker** [comment]
Destroying the house itself will also cause a crash

**Comment by AlexModGuy** [comment]
dupe
