### ISSUE TITLE
Relentless log spam relating to Citadel and Chains (I think) [2.1.8]

### ISSUE THREAD

**Issue by Neko2n** [Alex-the-666/Ice_and_Fire#4080]
**Describe the bug**
After hanging around in a world for a little bit and flying around in creative, the game randomly freezes and crashes. My latest.log file is filled up with so much log spam it's reached 35,000kb. The log mentions Citadel and Ice and Fire, as well as... chains? It gets even weirder for me when I check the crash report and it doesn't mention any of this; it's purely in the latest.log file. This leads me to think that it might not have anything to do with ice and fire, but regardless if it is or not there's still a log spam issue that causes a lot of lag.
The crash report mentions "rendering screen", it can be seen below.

**To Reproduce**
1. Enter a world with ice and fire installed. Might be a mod incompatibility, so you'll need roughly 294 other mods installed if it is.
2. Fly around for a bit and pray for the game to smite you
3. Game freezes, crashes, and your log file fills up with spam.

**Expected behavior**

**Screenshots**
Error thrown from the launcher:
![image](https://user-images.githubusercontent.com/43053729/126084517-4b8137c6-0c49-4a6f-81f0-e72b90358ef5.png)

**Additional context**
Crash report:
https://pastebin.com/4t1nQ3mz

What gets spammed in latest.log:
`[18Jul2021 15:36:12.009] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[?:1.7.2-1.16.5]
	at com.github.alexthe666.iceandfire.entity.props.ChainEntityProperties.loadNBTData(ChainEntityProperties.java:54) ~[?:2.1.8-1.16.5]
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.loadTrackingSensitiveData(EntityProperties.java:112) ~[?:1.7.2-1.16.5]
	at com.github.alexthe666.citadel.ClientProxy.handlePropertiesPacket(ClientProxy.java:126) ~[?:1.7.2-1.16.5]
	at com.github.alexthe666.citadel.server.message.PropertiesMessage$Handler.lambda$handle$0(PropertiesMessage.java:50) ~[?:1.7.2-1.16.5]
	at com.github.alexthe666.citadel.server.message.PropertiesMessage$Handler$$Lambda$28671/1426652051.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.github.alexthe666.citadel.server.message.PropertiesMessage$Handler.handle(PropertiesMessage.java:48) ~[?:1.7.2-1.16.5]
	at com.github.alexthe666.citadel.Citadel$$Lambda$20119/514694156.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$27705/1946876684.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2884/963636917.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2886/328984689.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2481/340932477.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$27692/919305902.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$28007/1663941053.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.61.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/1117719720.call(Unknown Source) [forge-1.16.5-36.1.61.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]`

There's a possibility this is just a mod incompatibility or a datapack issue, and if it is I'd like someone to point that out to me so I can fix it and close the issue. Thanks.

Edit: I also have Optifine installed, so I'd honestly be relieved to know it's that. Then at least it's not a problem with my modpack I have to spend 10 hours fixing, and rather just Optifine doing what Optifine does.

**Comment by Neko2n** [comment]
The crash is unrelated to the log spam. Log spam happens independent of the crash, and actually happens the entire time the game is up.

Just ignore the crash log and focus on what's being printed in my latest.log. Sorry for the confusion.

**Comment by Kutomi1** [comment]
I have the same issue with the newest Citadel version, and my game would freeze (I can wait like an hour and wouldn't unfreeze). I downgraded to the previous version and it doesn't happen anymore.
