### ISSUE TITLE
crash when fight with ice dragon

### ISSUE THREAD

**Issue by Mayouchan1023** [Alex-the-666/Ice_and_Fire#4085]
I am playing this mod in server today and when we fight with ice dragon,when the ice dragon breath, then the server crash. We try many time but it also crash and the health of ice dragon and the treasure in the chest was refresh. It also happen in singleplayer.

The mod list of server:
Better cave
Better mineshaft
Better stronghold
Curioofundying
Farmer delight
Greek fantasy
Ice and fire
Mowzie monster
Spartan weapons
Spartan shield
Stoneholm
Terraforge
Useful backpack
Waystone
Wyrmroost

Crash Report:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/19/21 8:28 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[citadel:1.7.2-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.props.FrozenEntityProperties.setFrozenFor(FrozenEntityProperties.java:48) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.lambda$destroyAreaIce$5(IafDragonDestructionManager.java:172) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_292] {}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.destroyAreaIce(IafDragonDestructionManager.java:167) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.stimulateFire(EntityIceDragon.java:481) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.shootIceAtMob(EntityIceDragon.java:389) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:212) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1592) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[citadel:1.7.2-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.props.FrozenEntityProperties.setFrozenFor(FrozenEntityProperties.java:48) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.lambda$destroyAreaIce$5(IafDragonDestructionManager.java:172) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_292] {}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.destroyAreaIce(IafDragonDestructionManager.java:167) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.stimulateFire(EntityIceDragon.java:481) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.shootIceAtMob(EntityIceDragon.java:389) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:212) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1592) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:ice_dragon (com.github.alexthe666.iceandfire.entity.EntityIceDragon)
	Entity ID: 40
	Entity Name: Ice Dragon
	Entity's Exact location: -803.65, 62.08, 4148.72
	Entity's Block location: World: (-804,62,4148), Chunk: (at 12,3,4 in -51,259; contains blocks -816,0,4144 to -801,255,4159), Region: (-2,8; contains chunks -64,256 to -33,287, blocks -1024,0,4096 to -513,255,4607)
	Entity's Momentum: -0.08, -0.28, 0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Mayouchan1023'/34, l='ServerLevel[world]', x=-799.52, y=62.14, z=4146.24]]
	Chunk stats: ServerChunkCache: 3342
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,66,61), Chunk: (at 0,4,13 in 15,3; contains blocks 240,0,48 to 255,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 267269 game time, 291873 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 153623 (now: false), thunder time: 30966 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-72-generic
	Java Version: 1.8.0_292, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1369169016 bytes (1305 MB) / 2307915776 bytes (2201 MB) up to 2307915776 bytes (2201 MB)
	CPUs: 3
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx2300M -Xms1150M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.62
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.62-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.5.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.5        |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-11.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-11     |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.90.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.90           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		stoneholm-1.2.2.jar                               |Stoneholm                     |stoneholm                     |1.2                 |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		curioofundying-forge-1.16.5-5.2.0.0.jar           |Curio of Undying              |curioofundying                |1.16.5-5.2.0.0      |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2          |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		greekfantasy-16.4.18.jar                          |Greek Fantasy                 |greekfantasy                  |16.4.18             |DONE      |Manifest: NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.110.jar                          |Just Enough Items             |jei                           |7.7.1.110           |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.62-universal.jar                |Forge                         |forge                         |36.1.62             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.12.jar                     |TerraForged                   |terraforged                   |0.2.12              |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		journeymap-1.16.5-5.7.2beta18.jar                 |Journeymap                    |journeymap                    |5.7.2beta18         |DONE      |Manifest: NOSIGNATURE
		citadel-1.7.2-1.16.5.jar                          |Citadel                       |citadel                       |1.7.2               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.8-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.8-1.16.5        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 3bc01501-c6e0-44e8-9da5-93887d7f15de
	Player Count: 1 / 10; [ServerPlayerEntity['Mayouchan1023'/34, l='ServerLevel[world]', x=-799.52, y=62.14, z=4146.24]]
	Data Packs: vanilla, mod:farmersdelight, mod:usefulbackpacks, mod:mowziesmobs (incompatible), mod:greekfantasy, mod:jei, mod:curios, mod:spartanshields, mod:bettercaves (incompatible), mod:waystones (incompatible), mod:terraforged, mod:journeymap (incompatible), mod:citadel (incompatible), mod:yungsapi, mod:curioofundying, mod:betterstrongholds, mod:uteamcore, mod:iceandfire (incompatible), mod:forge, mod:bettermineshafts, mod:spartanweaponry, mod:wyrmroost (incompatible), mod:stoneholm, mod:cloth-config (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
