### ISSUE TITLE
Serious bug on the server side! [ICE AND FIRE 1.16.5 2.1.8]

### ISSUE THREAD

**Issue by XionioXMaster** [Alex-the-666/Ice_and_Fire#4086]
**Describe the bug**
If you tame a dragon and use the control staff thereby forcing him to follow you to teleport to huge coordinates, the dragon instantly destroys the server, this happens only if there are 1-2 players near your dragon!

**To Reproduce**
If you tame a dragon and use the control staff thereby forcing him to follow you to teleport to huge coordinates, the dragon instantly destroys the server, this happens only if there are 1-2 players near your dragon!
![image](https://user-images.githubusercontent.com/86433158/126214549-3ae7990f-4231-46de-8d9b-74929c8bf16d.png)
CPU FULL RAM FULL
![image](https://user-images.githubusercontent.com/86433158/126214590-e7dce1a1-2cc7-441a-8cf7-200a19088a55.png)

**Additional context**
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 7/19/21, 7:06 PM
Description: Ticking entity

java.lang.OutOfMemoryError: Java heap space
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.ChunkCache.<init>(ChunkCache.java:56) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.<init>(AbstractPathJob.java:126) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.<init>(AbstractPathJob.java:100) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.PathJobMoveToLocation.<init>(PathJobMoveToLocation.java:39) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.moveToXYZ(AdvancedPathNavigate.java:277) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.tryMoveToBlockPos(AdvancedPathNavigate.java:284) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75497_a(AdvancedPathNavigate.java:346) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.ai.DragonAIEscort.func_75246_d(DragonAIEscort.java:34) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:392) ~[performant:1.16.2-5-3.66m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:752) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2862) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:543) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(AgeableEntity.java:142) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:54) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:AnimalEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1626) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:197) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2610) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:339) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1592) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:941) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$11564/0x0000000842480440.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:801) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:685) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1061) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:965) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer$$Lambda$9449/0x00000008418c7c40.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.ChunkCache.<init>(ChunkCache.java:56) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.<init>(AbstractPathJob.java:126) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.<init>(AbstractPathJob.java:100) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.PathJobMoveToLocation.<init>(PathJobMoveToLocation.java:39) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.moveToXYZ(AdvancedPathNavigate.java:277) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.tryMoveToBlockPos(AdvancedPathNavigate.java:284) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75497_a(AdvancedPathNavigate.java:346) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.ai.DragonAIEscort.func_75246_d(DragonAIEscort.java:34) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:392) ~[performant:1.16.2-5-3.66m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:752) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2862) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:543) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(AgeableEntity.java:142) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:54) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:AnimalEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1626) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:197) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2610) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:339) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1592) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:941) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$11564/0x0000000842480440.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:801) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:ice_dragon (com.github.alexthe666.iceandfire.entity.EntityIceDragon)
	Entity ID: 2589
	Entity Name: Ice Dragon
	Entity's Exact location: -55.09, 81.32, 55.74
	Entity's Block location: World: (-56,81,55), Chunk: (at 8,5,7 in -4,3; contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.69, -0.06, -0.21
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:804) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:685) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1061) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:965) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['DeZoWaRe'/283, l='ServerLevel[world]', x=5000000.50, y=90.00, z=5000000.50](TextComponent{text='DeZoWaRe', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 5000000.5,90.0,5000000.5), ServerPlayerEntity['Zireael'/801, l='ServerLevel[world]', x=-54.99, y=73.69, z=70.22](TextComponent{text='Zireael', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at -54.99279929001094,73.69104743268886,70.22351452012859)]
	Chunk stats: ServerChunkCache: 4056
	Level dimension: minecraft:overworld
	Level spawn location: World: (9000033,69,898561), Chunk: (at 1,4,1 in 562502,56160; contains blocks 9000032,0,898560 to 9000047,255,898575), Region: (17578,1755; contains chunks 562496,56160 to 562527,56191, blocks 8999936,0,898560 to 9000447,255,899071)
	Level time: 8276503 game time, 8345659 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 21182 (now: false), thunder time: 152330 (now: false)... (осталось: 40 кб)

**Comment by XionioXMaster** [comment]
that a huge array is trying to allocate here.
https://github.com/Alex-the-666/Ice_and_Fire/blob/383935d745e45da2d3342e2f1024f94229130a61/src/main/java/com/github/alexthe666/iceandfire/pathfinding/raycoms/ChunkCache.java#L56
