### ISSUE TITLE
Crash Report? [main/FATAL] java.lang.NullPointerException

### ISSUE THREAD

**Issue by AndresCycloid** [Alex-the-666/Ice_and_Fire#4098]
```
[25Jul2021 07:24:41.018] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.lang.NullPointerException: null
	at com.github.alexthe666.iceandfire.config.BiomeConfig.test(BiomeConfig.java:86) ~[iceandfire:2.1.8-1.16.5]
        at com.github.alexthe666.iceandfire.entity.IafEntityRegistry.onBiomesLoad(IafEntityRegistry.java:199) ~[iceandfire:2.1.8-1.16.5]
	at com.github.alexthe666.iceandfire.IceAndFire.onBiomeLoadFromJSON(IceAndFire.java:117) ~[iceandfire:2.1.8-1.16.5]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
```

Look, I don't know where the thing is, I tried to check in the configuration files but i dont think the answer is in those jsons. I got this just by attempting run this for first time the forge server on 1.16.5, on linux if it helps. Here you go with the log, no crash report i dont know why. The mod looks incredible so far and me and my friends really want to play it, so if its an error on my side or another mod let me know please.
[2021-07-25-3.log](https://github.com/Alex-the-666/Ice_and_Fire/files/6873587/2021-07-25-3.log)

**Comment by AndresCycloid** [comment]
Nevermind, it made it to work, i think it was just when creating the world for first time.
But you may need to fix this:
![screenshot](https://user-images.githubusercontent.com/66335002/126928239-87523354-a646-42a6-a3e9-7d343fa042a0.png)
