### ISSUE TITLE
Crash server 1.16.5 (Ticking entity)

### ISSUE THREAD

**Issue by GorillaArnold** [Alex-the-666/Ice_and_Fire#4114]
I was running around the world and met an ice dragon when he started breathing ice into me and after that the game froze and crashed.

Here is the crash log:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 31.07.21 22:20
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[?:1.7.2-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.props.FrozenEntityProperties.setFrozenFor(FrozenEntityProperties.java:48) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.lambda$destroyAreaIce$5(IafDragonDestructionManager.java:172) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager$$Lambda$25654/913475159.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.destroyAreaIce(IafDragonDestructionManager.java:167) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.stimulateFire(EntityIceDragon.java:481) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.shootIceAtMob(EntityIceDragon.java:389) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:212) ~[?:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1592) ~[?:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$25452/1748901697.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$23473/778864544.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[?:1.7.2-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.props.FrozenEntityProperties.setFrozenFor(FrozenEntityProperties.java:48) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.lambda$destroyAreaIce$5(IafDragonDestructionManager.java:172) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager$$Lambda$25654/913475159.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at com.github.alexthe666.iceandfire.entity.IafDragonDestructionManager.destroyAreaIce(IafDragonDestructionManager.java:167) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.stimulateFire(EntityIceDragon.java:481) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.shootIceAtMob(EntityIceDragon.java:389) ~[?:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.func_70636_d(EntityIceDragon.java:212) ~[?:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1592) ~[?:2.1.8-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$25452/1748901697.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:ice_dragon (com.github.alexthe666.iceandfire.entity.EntityIceDragon)
	Entity ID: 399
	Entity Name: Ледяной дракон
	Entity's Exact location: -231.64, 4.00, -26.06
	Entity's Block location: World: (-232,4,-27), Chunk: (at 8,0,5 in -15,-2; contains blocks -240,0,-32 to -225,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.01, -0.08, -0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['9G9'/2, l='ServerLevel[Новый мир]', x=-208.77, y=4.00, z=-37.69]]
	Chunk stats: ServerChunkCache: 2216
	Level dimension: minecraft:overworld
	Level spawn location: World: (-160,4,64), Chunk: (at 0,0,0 in -10,4; contains blocks -160,0,64 to -145,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1094 game time, 1094 day time
	Level name: Новый мир
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 112803 (now: false), thunder time: 17119 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$23473/778864544.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2256606752 bytes (2152 MB) / 5469372416 bytes (5216 MB) up to 5469372416 bytes (5216 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx5208M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.65.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.65
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		TreeChop-1.16.4-0.14.4.jar                        |HT's TreeChop                 |treechop                      |0.14.4              |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		torchslabmod-1.16.4_v1.6.19.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.116.jar                          |Just Enough Items             |jei                           |7.7.1.116           |DONE      |Manifest: NOSIGNATURE
		Druidcraft-1.16.5-0.4.52.jar                      |Druidcraft                    |druidcraft                    |0.4.52              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |DONE      |Manifest: NOSIGNATURE
		Space-Bosstools-1.16.5-5.3.jar                    |Space-Bosstools               |boss_tools                    |5.3                 |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |Manifest: NOSIGNATURE
		PassableFoliage-1.16.5-2.3.1.jar                  |Passable Foliage              |passablefoliage               |2.3.1               |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.25.jar                               |Clumps                        |clumps                        |6.0.0.25            |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.15.0.1_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.15.0.1            |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.1.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.1      |DONE      |Manifest: NOSIGNATURE
		citadel-1.7.2-1.16.5.jar                          |Citadel                       |citadel                       |1.7.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.2.jar                |Traveler's Backpack           |travelersbackpack             |5.4.2               |DONE      |Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.9.3.jar                        |Artifacts                     |artifacts                     |1.16.5-2.9.3        |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-11.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-11     |DONE      |Manifest: NOSIGNATURE
		champions-forge-1.16.5-2.0.1.7.jar                |Champions                     |champions                     |1.16.5-2.0.1.7      |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.2.15.jar                      |Bookshelf                     |bookshelf                     |10.2.15             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyPots-1.16.5-7.1.23.jar                      |BotanyPots                    |botanypots                    |7.1.23              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		villagersleashed-1.16.5-1.2.0.jar                 |Villagers Leashed!            |villagersleashed              |1.2.0               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.8-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.8-1.16.5        |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |DONE      |Manifest: NOSIGNATURE
		Hwyla-Mod-1.16.3.jar                              |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		FpsReducer-mc1.16.5-1.20.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.5-1.20       |DONE      |Manifest: NOSIGNATURE
		mininggadgets-1.7.5.jar                           |Mining Gadgets                |mininggadgets                 |1.7.5               |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.16.5-1.3.2.0.jar                     |Paraglider                    |paraglider                    |1.3.2.0             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.65-universal.jar                |Forge                         |forge                         |36.1.65             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		twilightforest-1.16.5-4.0.515-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		refinedstorage-1.9.15.jar                         |Refined Storage               |refinedstorage                |1.9.15              |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.47              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.65-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cavebiomes-2.0.jar                                |CaveBiomeAPI                  |cavebiomes                    |2.0                 |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.1.0.231.jar                   |Tinkers' Construct            |tconstruct                    |3.1.0.231           |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-1.0.6-mc1.16.5.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.6               |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.3-9.jar        |Industrial Foregoing          |industrialforegoing           |3.2.14.3            |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.5.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.5        |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.0.1+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.0.1+1.16.5        |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.14.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.14              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.4-10.jar                    |Titanium                      |titanium                      |3.2.8.4             |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.481-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.481   |DONE      |Manifest: NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.2.0BETA2.jar      |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.2.0BETA2   |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |DONE      |Manifest: NOSIGNATURE
		Blur-1.1.0-1.jar                                  |Blur                          |blur                          |1.1.0-1             |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.16.5-2.6.9.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.9               |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-419.jar                            |Botania                       |botania                       |1.16.5-419          |DONE      |Manifest: NOSIGNATURE
		CavesAndCliffsBackport-6.1.jar                    |Caves & Cliffs Backport       |cavesandcliffs                |6.1                 |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.16.3-16.2.5.jar                 |Solar Flux Reborn             |solarflux                     |16.2.5              |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.1.1.jar                           |Flywheel                      |flywheel                      |1.16-0.1.1          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2b.jar                       |Create                        |create                        |v0.3.2b for 1.16.5  |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		omnis-1.16.5-1.1.2.3.jar                          |Omnis                         |omnis                         |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.1.jar                         |Patchouli                     |patchouli                     |1.16.4-53.1         |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.115.jar                         |Mantle                        |mantle                        |1.6.115             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.14.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.14.0             |DONE      |Manifest: NOSIGNATURE
		omnis_backpacks-1.2.1.jar                         |Omnis Backpacks               |omnis_backpacks               |1.2.1               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		Simple-Sitting-1.16.5-1.2.1.jar                   |Simple Sitting                |sit                           |1.2.1               |DONE      |Manifest: NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		BetterStrongholds-1.16.4-1.2.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2          |DONE      |Manifest: NOSIGNATURE
		structurize-0.13.205-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.205-ALPHA      |DONE      |Manifest: NOSIGNATURE
		minecolonies-0.14.314-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.14.314-ALPHA      |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.1.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.1.0      |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |Manifest: NOSIGNATURE
		NefsMedievalPub+v0.9(1.16.5).jar                  |Nef Deco Mod                  |nefdecomod                    |0.9                 |DONE      |Manifest: NOSIGNATURE
		FriendlyFire-1.16.5-7.0.4.jar                     |FriendlyFire                  |friendlyfire                  |7.0.4               |DONE      |Manifest: NOSIGNATURE
		expandability-2.0.1-forge.jar                     |ExpandAbility                 |expandability                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		exoticbirds-1.16.4-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.4.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.4        |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2d0a7e17-f341-402a-8062-c2c77ece840e
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['9G9'/2, l='ServerLevel[Новый мир]', x=-208.77, y=4.00, z=-37.69]]
	Data Packs: vanilla, mod:treechop, mod:quarkoddities (incompatible), mod:mowziesmobs (incompatible), mod:torchslabmod (incompatible), mod:jei, mod:druidcraft (incompatible), mod:abnormals_core, mod:mekanism, mod:boss_tools, mod:bettercaves (incompatible), mod:waystones (incompatible), mod:passablefoliage, mod:clumps, mod:xaeroworldmap, mod:comforts, mod:citadel (incompatible), mod:alexsmobs, mod:travelersbackpack (incompatible), mod:artifacts, mod:yungsapi, mod:champions (incompatible), mod:betteranimalsplus (incompatible), mod:bookshelf, mod:botanypots, mod:villagersleashed, mod:iceandfire (incompatible), mod:mekanismgenerators, mod:waila, mod:fpsreducer, mod:mininggadgets (incompatible), mod:paraglider, mod:forge, mod:twilightforest, mod:tlskincape (incompatible), mod:refinedstorage, mod:betterendforge, mod:structure_gel, mod:dungeons_arise, mod:cavebiomes, mod:upgrade_aquatic, mod:tconstruct, mod:mcwbridges (incompatible), mod:industrialforegoing (incompatible), mod:farmersdelight, mod:repurposed_structures, mod:enchdesc, mod:mousetweaks, mod:titanium (incompatible), mod:biomesoplenty, mod:projectvibrantjourneys, mod:mekanismadditions, mod:blur (incompatible), mod:ironfurnaces, mod:dungeons_plus, mod:creativecore, mod:botania, mod:cavesandcliffs (incompatible), mod:solarflux, mod:flywheel, mod:create, mod:curios, mod:omnis, mod:patchouli (incompatible), mod:mantle (incompatible), mod:xaerominimap, mod:omnis_backpacks, mod:autoreglib (incompatible), mod:quark (incompatible), mod:sit, mod:betteranimals (incompatible), mod:obfuscate (incompatible), mod:betterstrongholds, mod:structurize, mod:minecolonies (incompatible), mod:mekanismtools, mod:appleskin, mod:itemphysic, mod:nefdecomod, mod:friendlyfire (incompatible), mod:expandability, mod:exoticbirds, mod:valhelsia_core, mod:valhelsia_structures, mod:bettermineshafts
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 8
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Inferius77** [comment]
I have this same crash. 
[crash-2021-08-25_17.47.17-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/7050296/crash-2021-08-25_17.47.17-server.txt)

**Comment by AlexModGuy** [comment]
fixed in 2.1.9
