### ISSUE TITLE
NullPointerException in ClientProxy Init (ClientProxy.java:192) when IaF is mod dependency [iceandfire-2.1.8-1.16.5]

### ISSUE THREAD

**Issue by XxInvictus** [Alex-the-666/Ice_and_Fire#4124]
**Describe the bug**
Trying to update SpartanFire for 1.16.5 I am experiencing the below error during the automatic subscribers stage:
```
[07:26:52] [modloading-worker-6/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: iceandfire, class com.github.alexthe666.iceandfire.IceAndFire
java.lang.NullPointerException: null
	at com.github.alexthe666.iceandfire.ClientProxy.init(ClientProxy.java:192) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:104) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_292] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_292] {}
```

**To Reproduce**
Steps to reproduce the behavior (In dev environment):
1. Load Ice and Fire as a dependency to another mod
2. Attempt to run any of the gradle "run" tasks (runClient, runData, runServer) or Build the dependant mod and run the mods in a Client
3. See error

**Expected behavior**
For initialisation events to occur without error.

**Additional context**
This by itself may not be of much concern but I am trying to clean up all errors while chasing an issue with Model Providers and the below error in SF which again seems to involve IaF items
```
[07:26:52] [modloading-worker-7/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: spartanfire, class com.chaosbuffalo.spartanfire.SpartanFire
java.lang.ExceptionInInitializerError: null
	at com.github.alexthe666.iceandfire.client.render.tile.IceAndFireTEISR.<init>(IceAndFireTEISR.java:26) ~[iceandfire:2.1.8-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.DistExecutor.unsafeCallWhenOn(DistExecutor.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.callWhenOn(DistExecutor.java:65) ~[forge:?] {re:classloading}
	at net.minecraft.item.Item.<init>(Item.java:82) ~[forge:?] {re:classloading,xf:fml:forge:crossbows.8}
	at com.github.alexthe666.iceandfire.item.ItemGorgonHead.<init>(ItemGorgonHead.java:38) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.item.IafItemRegistry.<clinit>(IafItemRegistry.java:195) ~[iceandfire:2.1.8-1.16.5] {re:classloading}
	at com.chaosbuffalo.spartanfire.init.ItemRegistrySFire.<clinit>(ItemRegistrySFire.java:45) ~[?:?] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_292] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_292] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_292] {}
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.tileentity.PistonTileEntityRenderer.<init>(PistonTileEntityRenderer.java:25) ~[forge:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.<init>(TileEntityRendererDispatcher.java:40) ~[forge:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.<clinit>(TileEntityRendererDispatcher.java:29) ~[forge:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 20 more
```

**Comment by TheBv** [comment]
The registration code has changed a lot so I'm not sure if this still applies. 
Removed the item that could've been causing the first crash though.
