### ISSUE TITLE
Game Crash Upon First Initialization (Phase 2)

### ISSUE THREAD

**Issue by silvercirrus** [Alex-the-666/Ice_and_Fire#4157]
**Describe the bug**
Game Crashed Error Code

"The Game Crashed whilst initializing the game
Error: java.lang.VerifyError: Expecting a stackmap frame at branch target 461
Exit Code: -1"

**To Reproduce**
Load custom modpack

**Expected behavior**
The game to properly load in for the first time

**Screenshots**

Screenshot of Game Crash
https://media.discordapp.net/attachments/782027635252920322/877992955330318376/unknown.png

Screenshots of Crash Log 
https://cdn.discordapp.com/attachments/782027635252920322/877993280221118474/unknown.png
https://cdn.discordapp.com/attachments/782027635252920322/877993655825219644/unknown.png

**Additional context**
This is a problem with a custom modpack I just made that includes Ice and Fire. Unsure how to proceed. 

Here is the Crash Report Unscreenshotted

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  LibLoader (# LibLoader.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CoreMod (TickProfiler-1.12-0.0.10.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.62_mc1.12.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  Snow! Real Magic! (SnowRealMagic-1.12.2-0.4.4.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.34_mc1.12.2.jar)
  LevelUpCore (levelup2-1.5.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 8/19/21 3:39 PM
Description: Initializing game

java.lang.VerifyError: Expecting a stackmap frame at branch target 461
Exception Details:
  Location:
    com/github/alexthe666/iceandfire/entity/EntityDragonBase.breakBlock()V @457: goto
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 0791 9d00 0cb2 04d6 b407 949a 01d8
    0x0000010: 2a59 b407 9104 64b5 0791 043c 2ab6 03b5
    0x0000020: 9900 0e2a b604 94c6 0007 02a7 0004 043d
    0x0000030: 2ab4 0791 9900 0cb2 04d6 b407 949a 01a8
    0x0000040: 2ab4 01d5 2ab8 0798 9901 9db2 04d6 b407
    0x0000050: 9b05 9f01 932a b603 a799 000c b204 d6b4
    0x0000060: 079e 9901 83b2 04d6 b407 9b04 9f00 0b2a
    0x0000070: b602 6706 a300 070d a700 0613 079f 462a
    0x0000080: b601 e49a 0162 2ab6 0267 06a1 015a 2ab6
    0x0000090: 0780 9a00 0a2a b604 abc6 014c 2ab6 0720
    0x00000a0: b407 28b8 07a3 8e1b 6436 0415 042a b607
    0x00000b0: 20b4 0725 b807 a68e 1b60 a301 2b2a b607
    0x00000c0: 20b4 072e b807 a38e 1c60 3605 1505 2ab6
    0x00000d0: 0720 b407 2bb8 07a6 8e1b 6004 60a3 0102
    0x00000e0: 1505 107f a300 fb2a b607 20b4 0734 b807
    0x00000f0: a38e 1b64 3606 1506 2ab6 0720 b407 31b8
    0x0000100: 07a6 8e1b 60a3 00d4 b207 acbb 07ae 592a
    0x0000110: 1504 8715 0587 1506 87b7 07b1 b607 b799
    0x0000120: 0006 a700 b1bb 01f9 5915 0415 0515 06b7
    0x0000130: 044a 3a07 2ab4 01d5 1907 b602 553a 0819
    0x0000140: 08b9 07bb 0100 b607 c099 008a 1908 2ab4
    0x0000150: 01d5 1907 b907 c403 000b 959b 0078 1908
    0x0000160: 2ab4 01d5 1907 b907 c403 0025 969d 0066
    0x0000170: 1908 b902 5b01 00b8 07ca 9900 592a 1907
    0x0000180: b607 cc99 0050 2a59 b407 cf14 07d0 6bb5
    0x0000190: 07cf 2a59 b407 d414 07d0 6bb5 07d4 2ab4
    0x00001a0: 01d5 b402 179a 002e 2ab4 01d5 1907 2ab4
    0x00001b0: 02b4 b602 c68d b204 d6b4 07d7 989d 000f
    0x00001c0: 1908 b807 db99 0007 04a7 0004 0319 05b8
    0x00001d0: 07e1 5784 0601 a7ff 2084 0501 a7fe f084
    0x00001e0: 0401 a7fe c9b1                         
  Stackmap Table:
    same_frame(@16)
    append_frame(@46,Integer)
    same_locals_1_stack_item_frame(@47,Integer)
    append_frame(@64,Integer)
    same_frame(@101)
    same_frame(@119)
    same_frame(@123)
    same_locals_1_stack_item_frame(@126,Float)
    append_frame(@156,Float)
    append_frame(@171,Integer)
    append_frame(@204,Integer)
    append_frame(@246,Integer)
    same_frame(@293)
    full_frame(@460,{Object[#2],Integer,Integer,Float,Integer,Integer,Integer,Object[#505],Object[#599]},{Object[#279],Object[#505]})
    chop_frame(@467,2)
    chop_frame(@473,1)
    chop_frame(@479,1)
    full_frame(@485,{Object[#2]},{})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:326)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:194)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:297)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:265)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:265)
	at com.github.alexthe666.iceandfire.CommonProxy.registerSpawnable(CommonProxy.java:151)
	at com.github.alexthe666.iceandfire.CommonProxy.registerEntities(CommonProxy.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_222_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:326)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:194)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:297)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:265)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:265)
	at com.github.alexthe666.iceandfire.CommonProxy.registerSpawnable(CommonProxy.java:151)
	at com.github.alexthe666.iceandfire.CommonProxy.registerEntities(CommonProxy.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_222_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1163202360 bytes (1109 MB) / 2111832064 bytes (2014 MB) up to 7486832640 bytes (7140 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8032m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                         | Signature                                |
	|:----- |:--------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCH   | mcp                   | 9.42                     | minecraft.jar                                  | None                                     |
	| LCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy     | 1.0.0                    | minecraft.jar                                  | None                                     |
	| LCH   | itemphysic            | 1.4.0                    | minecraft.jar                                  | None                                     |
	| LCH   | ivtoolkit             | 1.3.3-1.12               | minecraft.jar                                  | None                                     |
	| LCH   | tnt_utilities_core    | 1.2.3                    | minecraft.jar                                  | None                                     |
	| LCH   | aether_legacy         | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                     | None                                     |
	| LCH   | aether_legacy_addon   | 1.12.2-v1.3.0            | Aether Continuation v1.3.0.jar                 | None                                     |
	| LCH   | aireducer             | 0.2.1                    | AIReducer-1.12.2-0.2.1.jar                     | None                                     |
	| LCH   | alcatrazcore          | 1.0.4                    | alcatrazcore-1.0.4.jar                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | antiqueatlas          | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCH   | antiqueatlasoverlay   | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                  | None                                     |
	| LCH   | anvilpatch            | 1.1.0                    | anvilpatch-1.1.0.jar                           | None                                     |
	| LCH   | carrots               | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                | None                                     |
	| LCH   | armorunder            | 1.0.0                    | armorunder-mc1.12.2-1.0.0.jar                  | None                                     |
	| LCH   | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCH   | battletowers          | 1.6.5                    | BattleTowers-1.12.2.jar                        | None                                     |
	| LCH   | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | baubleshud            | 5.0.2                    | BaublesHud-1.12.2-5.0.2.jar                    | None                                     |
	| LCH   | bettercombatmod       | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                  | None                                     |
	| LCH   | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar              | None                                     |
	| LCH   | biomesoplenty         | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
	| LCH   | bloodmoon             | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bnbgaminglib          | 2.17.6                   | BNBGamingLib-1.12.2-2.17.6.jar                 | None                                     |
	| LCH   | bountifulbaubles      | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.6.jar             | None                                     |
	| LCH   | campfire              | 1.2                      | campfire-1.12-v1.2.jar                         | None                                     |
	| LCH   | chococraft            | 0.9.9.0                  | chococraft_1.12.2-0.9.9.0.jar                  | None                                     |
	| LCH   | chunkanimator         | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
	| LCH   | clumps                | 3.1.2                    | Clumps-3.1.2.jar                               | None                                     |
	| LCH   | toughasnails          | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar    | None                                     |
	| LCH   | comforts              | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | reskillable           | 1.12.2-1.13.0            | Reskillable-1.12.2-1.13.0.jar                  | None                                     |
	| LCH   | compatskills          | 1.12.2-1.17.0            | CompatSkills-1.12.2-1.17.0.jar                 | None                                     |
	| LCH   | coralreef             | 2.0                      | CoralReef-2.5-1.12.2.jar                       | None                                     |
	| LCH   | wearablebackpacks     | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar             | None                                     |
	| LCH   | corpsecomplex         | 1.0.12.0                 | corpsecomplex-1.12.2-1.0.12.0.jar              | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCH   | craftablechainmail    | 1.0                      | craftablechainmail-1.0.jar                     | None                                     |
	| LCH   | craftablehorsearmour  | 1.3                      | CraftableHorseArmour-1.3.0-1.12.jar            | None                                     |
	| LCH   | creativecore          | 1.10.0                   | CreativeCore_v1.10.62_mc1.12.2.jar             | None                                     |
	| LCH   | ctm                   | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCH   | defiledlands          | 1.4.3                    | defiledlands-1.12.2-1.4.3.jar                  | None                                     |
	| LCH   | disenchanter          | 1.7                      | disenchanter-[1.12]1.7.jar                     | None                                     |
	| LCH   | sereneseasons         | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar      | None                                     |
	| LCH   | orelib                | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround             | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | reccomplex            | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                   | None                                     |
	| LCH   | dynamictrees          | 1.12.2-0.9.24            | DynamicTrees-1.12.2-0.9.24.jar                 | None                                     |
	| LCH   | dynamictreesbop       | 1.12.2-1.5.1             | DynamicTreesBOP-1.12.2-1.5.1.jar               | None                                     |
	| LCH   | harvestcraft          | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                | None                                     |
	| LCH   | dynamictreesphc       | 1.12.2-2.0.5             | DynamicTreesPHC-1.12.2-2.0.5.jar               | None                                     |
	| LCH   | lost_aether           | 1.0.2                    | lost-aether-content-1.12.2-1.0.2.jar           | None                                     |
	| LCH   | dynamictreestheaether | 1.12.2-1.0.13            | dynamictreesTheAether-1.12.2-1.0.13.jar        | None                                     |
	| LCH   | twilightforest        | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCH   | dynamictreesttf       | 1.12.2-1.2.3             | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar | None                                     |
	| LCH   | enchdesc              | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | familiarfauna         | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                | None                                     |
	| LCH   | firstaid              | 1.6.16                   | firstaid-1.6.16.jar                            | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCH   | forgeendertech        | 1.12.2-4.5.5.0           | ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar   | None                                     |
	| LCH   | forgelin              | 1.8.4                    | Forgelin-1.8.4.jar                             | None                                     |
	| LCH   | friendlyendermite     | 1.0                      | FriendlyEndermite_v1.0.1_mc1.12.2.jar          | None                                     |
	| LCH   | cfm                   | 6.3.1                    | furniture-6.3.1-1.12.2.jar                     | None                                     |
	| LCH   | globalgamerules       | 2.2                      | GlobalGameRules-1.12.2-2.2.7.jar               | None                                     |
	| LCH   | grapplemod            | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                    | None                                     |
	| LCH   | llibrary              | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire            | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCH   | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | iseedragons           | 1.1                      | ISeeDragons-1.1.jar                            | None                                     |
	| LCH   | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCH   | levelup2              | ${version}               | levelup2-1.5.8.jar                             | None                                     |
	| LCH   | mobends               | 1.0.0-beta-20.06.20      | MoBends_1.12.2-1.0.0-beta-20.06.20.jar         | None                                     |
	| LCH   | mousetweaks           | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                  | None                                     |
	| LCH   | multimine             | 1.6.2                    | MultiMine-1.12.2.jar                           | None                                     |
	| LCH   | notreepunching        | 2.0.21                   | notreepunching-2.0.21.jar                      | None                                     |
	| LCH   | bonecraft             | 1.12.2b                  | Pam's BoneCraft 1.12.2b.jar                    | None                                     |
	| LCH   | brewcraft             | 1.12.2-1.0.2             | Pam's BrewCraft 1.12.2-1.0.2.jar               | None                                     |
	| LCH   | clayspawn             | 1.12a                    | Pam's ClaySpawn 1.12a.jar                      | None                                     |
	| LCH   | desertcraft           | 1.12.2b                  | Pam's DesertCraft 1.12.2c.jar                  | None                                     |
	| LCH   | spookytree            | 1.12.2a                  | Pam's Spooky Tree 1.12.2a.jar                  | None                                     |
	| LCH   | patchouli             | 1.0-23.6                 | Patchouli-1.0-23.6.jar                         | None                                     |
	| LCH   | potioncore            | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                  | None                                     |
	| LCH   | potionfingers         | r1.0-2                   | PotionFingers-r1.0-2.jar                       | None                                     |
	| LCH   | qualitytools          | 1.0.7_for_1.12.2         | QualityTools-1.0.7_for_1.12.2.jar              | None                                     |
	| LCH   | realistictorches      | 2.1.2                    | RealisticTorches-1.12.2-2.1.2.jar              | None                                     |
	| LCH   | reborncore            | 3.19.5                   | RebornCore-1.12.2-3.19.5-universal.jar         | None                                     |
	| LCH   | roguelike             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCH   | roughtweaks           | 1.0                      | roughTweaks0.2.4-1.12.2.jar                    | None                                     |
	| LCH   | ruins                 | 17.2                     | Ruins-1.12.2.jar                               | None                                     |
	| LCH   | silentlib             | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                | None                                     |
	| LCH   | scalinghealth         | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar            | None                                     |
	| LCH   | sit                   | v1.3                     | sit-1.12.2-v1.3.jar                            | None                                     |
	| LCH   | snowrealmagic         | 0.4.4                    | SnowRealMagic-1.12.2-0.4.4.jar                 | None                                     |
	| LCH   | somanyenchantments    | 0.5.2                    | SoManyEnchantments-0.5.2.jar                   | None                                     |
	| LCH   | soundfilters          | 0.12.1_for_1.12          | SoundFilters-0.12.1_for_1.12.jar               | None                                     |
	| LCH   | spartanweaponry       | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar          | None                                     |
	| LCH   | spartancompat         | @VERSION@                | spartancompat-1.2.3.jar                        | None                                     |
	| LCH   | spartanfire           | 0.08                     | spartanfire-0.08.jar                           | None                                     |
	| LCH   | spartanshields        | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCH   | spawnercontrol        | 1.6.3b                   | SpawnerControl-1.6.3b.jar                      | None                                     |
	| LCH   | stg                   | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LCH   | tickprofiler          | 1.12-0.0.10              | TickProfiler-1.12-0.0.10.jar                   | None                                     |
	| LCH   | tnt_utilities         | 1.2.3                    | tnt_utilities-mc1.12-1.2.3.jar                 | None                                     |
	| LCH   | toolbelt              | 1.9.13                   | ToolBelt-1.12.2-1.9.13.jar                     | None                                     |
	| LCH   | xat                   | 0.30                     | Trinkets and Baubles-0.30.1.jar                | None                                     |
	| LCH   | trumpetskeleton       | 1.12-1.0.2.1             | trumpetskeleton-1.12-1.0.2.1.jar               | None                                     |
	| LCH   | tschipplib            | 1.1.6                    | tschipplib-1.12.2-1.1.6.jar                    | None                                     |
	| LCH   | tumbleweed            | 1.12-0.4.7               | tumbleweed-1.12-0.4.7.jar                      | None                                     |
	| LCH   | waystones             | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                     | None                                     |
	| LCH   | wbpickup              | 1.0                      | wearabackpackspickup1.0.jar                    | None                                     |
	| LCH   | wolfarmor             | 3.7.5                    | wolfarmor-1.12.2-3.7.5-universal-signed.jar    | e94e38a605842477f3ec218e6fcf781f6b3f7f89 |
	| LCH   | xpfromharvest         | 1.2.0                    | XPFromHarvest-1.12.2-1.2.0.jar                 | None                                     |
	| LCH   | xpbook                | v2.0                     | xptome-1.12.2-v2.0.jar                         | None                                     |
	| LCH   | dshuds                | 3.6.0.0                  | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | phosphor-lighting     | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
LibLoader (# LibLoader.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
CoreMod (TickProfiler-1.12-0.0.10.jar)
  
CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
CreativePatchingLoader (CreativeCore_v1.10.62_mc1.12.2.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
Snow! Real Magic! (SnowRealMagic-1.12.2-0.4.4.jar)
  
WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.34_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
LevelUpCore (levelup2-1.5.8.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.92' Renderer: 'GeForce GTX 1660/PCIe/SSE2'
	No Tree Punching: You are not running an official build. This version will NOT be supported by the author.
	Patchouli open book context: n/a
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.5
		Runtime Debofucsation 1
		Invalid fingerprint detected for RebornCore!
		RenderEngine: 0
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.92, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

**Comment by silvercirrus** [comment]
Fixed: Removed ISeeDragons mod
