### ISSUE TITLE
Particles disappearing in this mod

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#425]
I encountered this issue back in 1.11.2 versions, but don't actually take it serious since i though it was because of my computer, but a lot of people have been getting this issue as well, despite using a good computer. Basically, particles will disappear completely after a while playing with this mod, meaning invisible dragon's blast, no pixie dust on pixies, etc..., the more laggy the modpack, the more likely it will happen, my experience is that it usually happen when using the dragon's blast. The only way to fix it is to exit our of your game then reopen it. Maybe it has something to do with a launcher update, i used to use native launcher when this happen, after i changed mine it stopped.

**Comment by OreCruncher** [comment]
I been chasing down this problem with a private pack I have which includes I&F.  The problems is not limited to particles from the mod - it's *all* particles.

@mser7 You wouldn't happen to have Dynamic Surroundings in your pack?  Right now looking for commonalities.

**Comment by mser7** [comment]
No, i does not have dynamic surroundings

**Comment by OreCruncher** [comment]
@Alex-the-666 Found the problem.  Wrote a shim for the ParticleManager and discovered this:
```
java.lang.RuntimeException: Die!
	at org.blockartistry.DynSurround.client.handlers.trace.TraceParticleManager.checkForClientThread(TraceParticleManager.java:61)
	at org.blockartistry.DynSurround.client.handlers.trace.TraceParticleManager.func_78873_a(TraceParticleManager.java:97)
	at com.github.alexthe666.iceandfire.ClientProxy.spawnParticle(ClientProxy.java:290)
	at com.github.alexthe666.iceandfire.entity.EntityPixie.func_70636_d(EntityPixie.java:220)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```
What the shim does is check to ensure the ParticleManager is being invoked from the client thread.  The callstack above indicates that the pixie code is trying to spawn a particle from the server thread.  Since the ParticleManager is not thread safe it's queues will get scrambled and no particles will spawn afterwards.

**Comment by AlexModGuy** [comment]
Good i was wondering what was doing this thanks
