### ISSUE TITLE
Failed to load correctly

### ISSUE THREAD

**Issue by martyw48** [Alex-the-666/Ice_and_Fire#4372]
**Describe the bug**
Ice and Fire (iceandfire) has failed to load correctly
java.lang.NoClassDefFoundError:net/minecraft/item/ItemGroup

**To Reproduce**
Fails after clicking play in the launcher

**Expected behavior**
Trying to load the game.  New to Mods.

**Screenshots**

**Additional context**
latest.log file

[16Jan2022 13:53:50.341] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, RavaLava48, --version, 1.18.1-forge-39.0.36, --gameDir, C:\Users\VICTO\AppData\Roaming\.minecraft, --assetsDir, C:\Users\VICTO\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, ead91eb1f9a640e4aad5798ff5269f90, --accessToken, ????????, --clientId, Mjc2YTMzZjgtYjBmNi00ZDBiLTg3YTktYTcyYjE5MDM1OTQw, --xuid, 2535462495377860, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.36, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[16Jan2022 13:53:50.341] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Microsoft
[16Jan2022 13:53:50.450] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/VICTO/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319! Service=ModLauncher Env=CLIENT
[16Jan2022 13:53:52.102] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[16Jan2022 13:53:52.118] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.1-forge-39.0.36, --gameDir, C:\Users\VICTO\AppData\Roaming\.minecraft, --assetsDir, C:\Users\VICTO\AppData\Roaming\.minecraft\assets, --uuid, ead91eb1f9a640e4aad5798ff5269f90, --username, RavaLava48, --assetIndex, 1.18, --accessToken, ????????, --clientId, Mjc2YTMzZjgtYjBmNi00ZDBiLTg3YTktYTcyYjE5MDM1OTQw, --xuid, 2535462495377860, --userType, msa, --versionType, release]
[16Jan2022 13:53:52.292] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/gen/feature/LakesFeature (java.lang.ClassNotFoundException: net.minecraft.world.gen.feature.LakesFeature)
[16Jan2022 13:53:52.292] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.gen.feature.LakesFeature was not found iceandfire.mixins.json:NoLakesInStructuresMixin
[13:53:58] [Render thread/WARN]: Assets URL 'union:/C:/Users/VICTO/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2355!/assets/.mcassetsroot' uses unexpected schema
[13:53:58] [Render thread/WARN]: Assets URL 'union:/C:/Users/VICTO/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2355!/data/.mcassetsroot' uses unexpected schema
[16Jan2022 13:53:58.393] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:53:59] [Render thread/INFO]: Setting user: RavaLava48
[13:53:59] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[13:54:00] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.36, for MC 1.18.1 with MCP 20211210.034407
[13:54:00] [modloading-worker-0/INFO]: MinecraftForge v39.0.36 Initialized
[16Jan2022 13:54:00.492] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: iceandfire, class com.github.alexthe666.iceandfire.IceAndFire
java.lang.NoClassDefFoundError: net/minecraft/item/ItemGroup
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.36.jar%2357!:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.36.jar%2356!:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.ItemGroup
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[16Jan2022 13:54:00.815] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[16Jan2022 13:54:00.978] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[16Jan2022 13:54:01.185] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[16Jan2022 13:54:01.189] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[16Jan2022 13:54:01.930] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[16Jan2022 13:54:02.002] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[16Jan2022 13:54:02.062] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[16Jan2022 13:54:02.063] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[16Jan2022 13:54:02.063] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[13:54:02] [Render thread/INFO]: Reloading ResourceManager: Default
[16Jan2022 13:54:02.701] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state
[16Jan2022 13:54:02.822] [Worker-Main-8/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:02.822] [Worker-Main-15/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:02.822] [Worker-Main-9/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:13.626] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:14.894] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:14.928] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:14.962] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:14.992] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:15.003] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16Jan2022 13:54:15.025] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[13:54:15] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers/Headphones (Realtek(R) Audio)
[13:54:15] [Render thread/INFO]: Sound engine started
[13:54:15] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16Jan2022 13:54:15.975] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:15] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[16Jan2022 13:54:15.977] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:15] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16Jan2022 13:54:15.982] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:15] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16Jan2022 13:54:15.988] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:15] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16Jan2022 13:54:15.990] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:15] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16Jan2022 13:54:15.993] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:15] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16Jan2022 13:54:15.995] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16Jan2022 13:54:16.384] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[16Jan2022 13:54:16.879] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[16Jan2022 13:54:18.706] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[13:54:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[16Jan2022 13:54:18.959] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[16Jan2022 13:54:18.963] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:18] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16Jan2022 13:54:18.967] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[13:54:19] [Render thread/FATAL]: Preparing crash report with UUID cafa5b77-d02a-4fa6-9184-1f6d679f8ce1
[13:54:19] [Render thread/FATAL]: Crash report saved to C:\Users\VICTO\AppData\Roaming\.minecraft\crash-reports\crash-2022-01-16_13.54.19-fml.txt
[13:54:19] [Render thread/FATAL]: Preparing crash report with UUID ddd85330-cdd0-4bfa-867c-78363b70571b

**Comment by AlexModGuy** [comment]
mods not out for 1.18
