### ISSUE TITLE
Issue desc [ICE AND FIRE VERSION] - Cyclops related crash error

### ISSUE THREAD

**Issue by GSharkGamer** [Alex-the-666/Ice_and_Fire#4445]
I need help with this mod error, I was told it was an Ice and Fire dragon mod problem and to contact the author, more info is here: https://forums.minecraftforge.net/topic/110500-my-minecraft-crashed-after-lookingcoming-close-to-fireandice-cyclop/

For more explanation, my game crashed after coming in contact with Cyclops

**Comment by GSharkGamer** [comment]
> I need help with this mod error, I was told it was an Ice and Fire dragon mod problem and to contact the author, more info is here: https://forums.minecraftforge.net/topic/110500-my-minecraft-crashed-after-lookingcoming-close-to-fireandice-cyclop/
> 
> For more explanation, my game crashed after coming in contact with Cyclops

This is some part of it: ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/17/22 6:38 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.util.math.shapes.EntitySelectionContext.<init>(EntitySelectionContext.java:41) ~[?:?] {re:classloading}
    at net.minecraft.util.math.shapes.ISelectionContext.func_216374_a(ISelectionContext.java:15) ~[?:?] {re:mixin,re:classloading}
    at net.minecraft.pathfinding.WalkNodeProcessor.mdab6d27$lambda$breakable$7$1(WalkNodeProcessor.java:635) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at net.minecraft.pathfinding.WalkNodeProcessor$$Lambda$17151/1832554646.apply(Unknown Source) ~[?:?] {}
    at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_51] {}
    at net.minecraft.pathfinding.WalkNodeProcessor.redirect$zoi000$breakable(WalkNodeProcessor.java:635) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at net.minecraft.pathfinding.WalkNodeProcessor.func_193577_a(WalkNodeProcessor.java:350) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at net.minecraft.pathfinding.WalkNodeProcessor.func_186319_a(WalkNodeProcessor.java:321) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops.isSafeToStandAt(PathNavigateCyclops.java:209) ~[?:2.1.9-1.16.5] {re:classloading}
    at com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops.func_75493_a(PathNavigateCyclops.java:148) ~[?:2.1.9-1.16.5] {re:classloading}
    at com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops.func_75508_h(PathNavigateCyclops.java:87) ~[?:2.1.9-1.16.5] {re:classloading}
    at net.minecraft.pathfinding.PathNavigator.func_75501_e(PathNavigator.java:189) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.PathNavigationMixin,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
    at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:980) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
    at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
    at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
    at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MonsterEntityMixin,pl:mixin:A}
    at com.github.alexthe666.iceandfire.entity.EntityCyclops.func_70636_d(EntityCyclops.java:254) ~[?:2.1.9-1.16.5] {re:classloading}
    at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
    at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
    at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}
    at net.minecraft.world.server.ServerWorld$$Lambda$15302/258873114.accept(Unknown Source) ~[?:?] {}
    at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
    at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
    at net.minecraft.server.MinecraftServer$$Lambda$14144/1509336518.run(Unknown Source) [?:?] {}
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.util.math.shapes.EntitySelectionContext.<init>(EntitySelectionContext.java:41) ~[?:?] {re:classloading}
    at net.minecraft.util.math.shapes.ISelectionContext.func_216374_a(ISelectionContext.java:15) ~[?:?] {re:mixin,re:classloading}
    at net.minecraft.pathfinding.WalkNodeProcessor.mdab6d27$lambda$breakable$7$1(WalkNodeProcessor.java:635) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at net.minecraft.pathfinding.WalkNodeProcessor$$Lambda$17151/1832554646.apply(Unknown Source) ~[?:?] {}
    at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_51] {}
    at net.minecraft.pathfinding.WalkNodeProcessor.redirect$zoi000$breakable(WalkNodeProcessor.java:635) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at net.minecraft.pathfinding.WalkNodeProcessor.func_193577_a(WalkNodeProcessor.java:350) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at net.minecraft.pathfinding.WalkNodeProcessor.func_186319_a(WalkNodeProcessor.java:321) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.GroundNodeMixin,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.performance.WalkNodeEvaluatorMixin,pl:mixin:APP:improvedmobs.mixins.compat.json:pathfinding.performance.WalkNodeStaticMixin,pl:mixin:A}
    at com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops.isSafeToStandAt(PathNavigateCyclops.java:209) ~[?:2.1.9-1.16.5] {re:classloading}
    at com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops.func_75493_a(PathNavigateCyclops.java:148) ~[?:2.1.9-1.16.5] {re:classloading}
    at com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops.func_75508_h(PathNavigateCyclops.java:87) ~[?:2.1.9-1.16.5] {re:classloading}
    at net.minecraft.pathfinding.PathNavigator.func_75501_e(PathNavigator.java:189) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:improvedmobs.mixins.json:pathfinding.PathNavigationMixin,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
    at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:980) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
    at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
    at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
    at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:MonsterEntityMixin,pl:mixin:A}
    at com.github.alexthe666.iceandfire.entity.EntityCyclops.func_70636_d(EntityCyclops.java:254) ~[?:2.1.9-1.16.5] {re:classloading}
    at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
    at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:library_of_exile-mixins.json:MobEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
    at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}
    at net.minecraft.world.server.ServerWorld$$Lambda$15302/258873114.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
    Entity Type: iceandfire:cyclops (com.github.alexthe666.iceandfire.entity.EntityCyclops)
    Entity ID: 292
    Entity Name: Cyclops
    Entity's Exact location: -471.50, 74.00, -775.50
    Entity's Block location: World: (-472,74,-776), Chunk: (at 8,4,8 in -30,-49; contains blocks -480,0,-784 to -465,255,-769), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Entity's Momentum: 0.00, -0.16, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A}

**Comment by TheBv** [comment]
I'm pretty sure this is a compatibility issue with the `improvedmobs` mod and ice and fire. (or other mobs that change how mobs move) was fixed [here](https://github.com/Alex-the-666/Ice_and_Fire/commit/362907e078c55b9c59969613a8b63f1c9e3ea7a0)
Although I think there's some weirdness going on so I'll further investigate.
If you don't want to wait for the next release I fear the only thing you can do is remove the `improvedmobs` mod or edit the config so that cylcops caves don't generate.
