### ISSUE TITLE
Cyclops or Cyclops eye may have made a fatal mistake in [version 1.16.5 server]

### ISSUE THREAD

**Issue by CauchyDOOM** [Alex-the-666/Ice_and_Fire#4565]
BUG CRASH 1:
```
-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.isRidingOrBeingRiddenBy(EntityMutlipartPart.java:250) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.lambda$collideWithNearbyEntities$0(EntityMutlipartPart.java:239) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.collideWithNearbyEntities(EntityMutlipartPart.java:239) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.func_70071_h_(EntityMutlipartPart.java:162) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:849) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:cylcops_multipart (com.github.alexthe666.iceandfire.entity.EntityCyclopsEye)
	Entity ID: 165512
	Entity Name: Cyclops Eye
	Entity's Exact location: 1809.58, 73.40, 4900.24
	Entity's Block location: World: (1809,73,4900), Chunk: (at 1,4,4 in 113,306; contains blocks 1808,0,4896 to 1823,255,4911), Region: (3,9; contains chunks 96,288 to 127,319, blocks 1536,0,4608 to 2047,255,5119)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:750) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:578) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['time_key3'/143901, l='ServerLevel[glance]', x=1965.20, y=69.52, z=4860.50](TextComponent{text='time_key3', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 1965.2008482750973,69.52172304021035,4860.496166508355), ServerPlayerEntity['Xing_Xiu'/154861, l='ServerLevel[glance]', x=7773.44, y=104.82, z=4002.26](TextComponent{text='Xing_Xiu', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 7773.4441842932865,104.82198824469064,4002.259116888924)]
	Chunk stats: ServerChunkCache: 8117
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,71,176), Chunk: (at 0,4,0 in 7,11; contains blocks 112,0,176 to 127,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3903343 game time, 4191747 day time
	Level name: glance
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 90329 (now: false), thunder time: 73152 (now: false)
	Known server brands: Mohist
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1090) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {}
```
BUG CRASH 2:
```
-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.isRidingOrBeingRiddenBy(EntityMutlipartPart.java:250) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.lambda$collideWithNearbyEntities$0(EntityMutlipartPart.java:239) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.collideWithNearbyEntities(EntityMutlipartPart.java:239) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityMutlipartPart.func_70071_h_(EntityMutlipartPart.java:162) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:849) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:cylcops_multipart (com.github.alexthe666.iceandfire.entity.EntityCyclopsEye)
	Entity ID: 202124
	Entity Name: Cyclops Eye
	Entity's Exact location: 1560.02, 73.40, 1866.60
	Entity's Block location: World: (1560,73,1866), Chunk: (at 8,4,10 in 97,116; contains blocks 1552,0,1856 to 1567,255,1871), Region: (3,3; contains chunks 96,96 to 127,127, blocks 1536,0,1536 to 2047,255,2047)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:750) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:578) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 6 total; [ServerPlayerEntity['time_key3'/198779, l='ServerLevel[glance]', x=5615.43, y=71.00, z=-1010.95](TextComponent{text='time_key3', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 5615.430832525762,71.0,-1010.9516164367261), ServerPlayerEntity['水纹霖霖'/198793, l='ServerLevel[glance]', x=39.08, y=150.56, z=577.40](TextComponent{text='水纹霖霖', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 39.07902689538788,150.5625,577.4048965448874), ServerPlayerEntity['DaoYe_'/198855, l='ServerLevel[glance]', x=36.87, y=150.00, z=578.68](TextComponent{text='DaoYe_', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 36.872788657528794,150.0,578.6795941505193), ServerPlayerEntity['daiyue'/198775, l='ServerLevel[glance]', x=44.97, y=150.94, z=581.02](TextComponent{text='daiyue', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 44.96599887309164,150.9375,581.0224070115933), ServerPlayerEntity['Glanceyu'/198774, l='ServerLevel[glance]', x=53.65, y=112.18, z=581.04](TextComponent{text='Glanceyu', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 53.650051288625164,112.17675927506424,581.0437282271904), ServerPlayerEntity['Xing_Xiu'/201784, l='ServerLevel[glance]', x=1560.01, y=71.20, z=1868.55](TextComponent{text='Xing_Xiu', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} at 1560.0070669893175,71.19999980926514,1868.5499252080917)]
	Chunk stats: ServerChunkCache: 7325
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,71,176), Chunk: (at 0,4,0 in 7,11; contains blocks 112,0,176 to 127,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1597551 game time, 1735768 day time
	Level name: glance
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 14175 (now: false), thunder time: 78554 (now: false)
	Known server brands: Mohist
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1090) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {}
```
Additional data:
```
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Mohist Version: 1.16.5-1040
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.15.1, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 1094735328 bytes (1044 MB) / 3823108096 bytes (3646 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 2 total; -XX:+UseG1GC -Xmx8G
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher启动目标: fmlserver
	ModLauncher命名: srg
	ModLauncher服务: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/mohist-1.16.5-1040-server.jar object_holder_definalize PLUGINSERVICE 
		/mohist-1.16.5-1040-server.jar runtime_enum_extender PLUGINSERVICE 
		/mohist-1.16.5-1040-server.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/mohist-1.16.5-1040-server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/mohist-1.16.5-1040-server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: com.mohistmc:36.2.39
	FML语言提供: 
		javafml@36.2
		minecraft@1
```

**Comment by 5stigma** [comment]
Did you use a specific modpack? I use Betterminecraft and the same thing happens to me.

I returned to version 2.1.9 and everything was normalized,
It remains to wait for them to fix it

**Comment by TheBv** [comment]
Will be fixed in the new version.
