### ISSUE TITLE
Mausoleum crashes with Cooking for Blockheads mod [2.1.10]

### ISSUE THREAD

**Issue by hegillespie** [Alex-the-666/Ice_and_Fire#4567]
Bug description:
While both Ice and Fire 2.1.10 and Cooking for Blockheads are installed, whenever a mausoleum attempts to generate, Minecraft crashes instead.

Have the mods Citadel 1.8.1, Ice and Fire 2.1.10, and Cooking for Blockheads 9.3.4 in your mods folder.
Generate a new world.
Find a mausoleum in a snowy biome. The command /locatebiome can assist in finding a snowy biome.

Expected behavior:
I expected a mausoleum to generate as it would when only Ice and Fire 2.1.10 is installed or when Ice and Fire 2.1.9 and Cooking for Blockheads 9.3.4 are installed together.

The crash report is below.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/10/22 7:46 PM
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47) ~[?:9.3.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_49_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3143/1154895182.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:583) ~[?:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:577) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:69) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:64) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34) ~[?:?] {re:classloading}
	at net.minecraft.tileentity.MobSpawnerTileEntity.<init>(SourceFile:43) ~[?:?] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.tile.TileEntityDreadSpawner.<init>(TileEntityDreadSpawner.java:45) ~[?:2.1.10-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.block.BlockDreadSpawner.func_196283_a_(BlockDreadSpawner.java:28) ~[?:2.1.10-1.16.5] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlock.createTileEntity(IForgeBlock.java:160) ~[?:?] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:106) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.WorldGenRegion.func_175625_s(WorldGenRegion.java:204) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:242) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.jigsaw.SingleJigsawPiece.func_230378_a_(SingleJigsawPiece.java:106) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.AbstractVillagePiece.func_237001_a_(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.AbstractVillagePiece.func_230383_a_(SourceFile:79) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.StructureStart.func_230366_a_(StructureStart.java:65) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.lambda$generate$20(Biome.java:234) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.biome.Biome$$Lambda$5999/1239301673.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at it.unimi.dsi.fastutil.longs.LongIterator$$Lambda$5990/429562180.accept(Unknown Source) ~[?:?] {}
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189) ~[?:1.8.0_51] {}
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2347/2040533564.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5977/793296787.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5962/715388647.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5975/129424353.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47) ~[?:9.3.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_49_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3143/1154895182.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:583) ~[?:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:577) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:69) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:64) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34) ~[?:?] {re:classloading}
	at net.minecraft.tileentity.MobSpawnerTileEntity.<init>(SourceFile:43) ~[?:?] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.tile.TileEntityDreadSpawner.<init>(TileEntityDreadSpawner.java:45) ~[?:2.1.10-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.block.BlockDreadSpawner.func_196283_a_(BlockDreadSpawner.java:28) ~[?:2.1.10-1.16.5] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlock.createTileEntity(IForgeBlock.java:160) ~[?:?] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:106) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.WorldGenRegion.func_175625_s(WorldGenRegion.java:204) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.template.Template.func_237146_a_(Template.java:242) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.jigsaw.SingleJigsawPiece.func_230378_a_(SingleJigsawPiece.java:106) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.AbstractVillagePiece.func_237001_a_(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.AbstractVillagePiece.func_230383_a_(SourceFile:79) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.StructureStart.func_230366_a_(StructureStart.java:65) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.lambda$generate$20(Biome.java:234) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.biome.Biome$$Lambda$5999/1239301673.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at it.unimi.dsi.fastutil.longs.LongIterator$$Lambda$5990/429562180.accept(Unknown Source) ~[?:?] {}
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189) ~[?:1.8.0_51] {}
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
-- Feature --
Details:
	Id: iceandfire:mausoleum
	Description: com.github.alexthe666.iceandfire.world.structure.DreadMausoleumStructure@2c9306d3
Stacktrace:
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B}

-- Generation --
Details:
	CenterX: 42
	CenterZ: -57
	Seed: 1157210004028266939
	Biome: net.minecraft.world.biome.Biome@39342614
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2347/2040533564.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}

-- Chunk to be generated --
Details:
	Location: 42,-57
	Position hash: -244813135830
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@6150eabb
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5977/793296787.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5962/715388647.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5975/129424353.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Heavy_Longsword'/274, l='ServerLevel[Mausoleum Test]', x=644.03, y=105.00, z=-626.57]]
	Chunk stats: ServerChunkCache: 4823
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,68,-96), Chunk: (at 0,4,0 in 2,-6; contains blocks 32,0,-96 to 47,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1369 game time, 1369 day time
	Level name: Mausoleum Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 41823 (now: false), thunder time: 134638 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5825/2136756216.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4637837600 bytes (4422 MB) / 7415529472 bytes (7072 MB) up to 12884901888 bytes (12288 MB)
	CPUs: 16
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		CookingForBlockheads_1.16.5-9.3.4.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.4               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.10-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.10-1.16.5       |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 724897ca-2a21-42b3-8069-2209dd3ed485
	Player Count: 1 / 8; [ServerPlayerEntity['Heavy_Longsword'/274, l='ServerLevel[Mausoleum Test]', x=644.03, y=105.00, z=-626.57]]
	Data Packs: vanilla, mod:forge, mod:cookingforblockheads (incompatible), mod:citadel (incompatible), mod:iceandfire (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by ModernGamingWorld** [comment]
Same Issue on our server

**Comment by TheBv** [comment]
Should be fixed with https://github.com/Alex-the-666/Ice_and_Fire/releases/tag/latest-snapshot
I guess I'll leave this issue up for now to avoid duplicates

**Comment by ModernGamingWorld** [comment]
@TheBv I cant do anything unless the fixed version is on Curseforge

**Comment by DrSigma4164** [comment]
I have a similar problem with the mausoleum in the cold biome. I wrote about it in #4579
