### ISSUE TITLE
2.1.10 addition of HomeDimension broke compatibility with pre-2.1.10 worlds, causing affected mobs to vanish (+crashes while riding)

### ISSUE THREAD

**Issue by Xeltalliv** [Alex-the-666/Ice_and_Fire#4597]
**Describe the bug**
Commit https://github.com/Alex-the-666/Ice_and_Fire/commit/0bb308bda406f7e1d3678da1d06f554b0aae485d , which made it's way into 2.1.10, added HomeDimension property to mobs with home position (only dragons and cockatrices). When entity is loaded, data about home position and dimension is read (provided that that data exists). In worlds that were created with versions of Ice and Fire before 2.1.10, entities don't have HomeDimension property, and since it doesn't exist, [dimension field](https://github.com/Alex-the-666/Ice_and_Fire/blob/1da2a4551b204759ea11eba7b304c14f2fbcf424/src/main/java/com/github/alexthe666/iceandfire/entity/util/HomePosition.java#L13) remains null. Because of it, when chunk gets unloaded, such mobs fail to save. When those chunks are loaded again those mobs are gone. 

Some other side effects:
1. Using `/data` command on mob throws an error
![iaf_data_error](https://user-images.githubusercontent.com/90340988/181290825-3da2bea4-2836-4584-b95b-5065348e54ce.png)
3. Glitched dragons can't be picked up with dragon horn
4. Launching minecraft with output log open, loading such mobs and pausing the game shows those errors:
```
[18:48:25] [Server thread/INFO]: Saving and pausing game...
[18:48:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[home dimension test]'/minecraft:overworld
[18:48:26] [Server thread/FATAL]: Preparing crash report with UUID 0de4b81f-770e-4eb1-9633-1c4bcfae1053
[18:48:26] [Server thread/INFO]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (0/24)
[18:48:26] [Server thread/ERROR]: An Entity type entity.iceandfire.fire_dragon has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1432)
	at net.minecraft.entity.Entity.func_184198_c(Entity.java:1346)
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70039_c(EntityDragonBase.java:2345)
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:303)
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:687)
	at net.minecraft.world.server.ChunkManager.func_222965_e(ChunkManager.java:351)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:348)
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:312)
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:698)
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:532)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:73)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException

[18:48:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[home dimension test]'/minecraft:the_nether
[18:48:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[home dimension test]'/minecraft:the_end
```
6. Pausing the game (or just waiting for an autosave) while riding a glitched mob crashes the game.

A workaround to this issue, is while the mob is still in the glitched state, remove it's home position and set it back again. (the simplest way to check in creative is to use `/data get entity <selector>` which should start working)

**To Reproduce**
1. Use Ice and Fire 2.1.9-1.16.5 (older versions should also work)
3. Create a world.
4. In some way get dragons or cockatrices with home position.
5. Try things from the list above to verify that it still works correctly.
7. Update Ice and Fire to version 2.1.10-1.16.5.
8. Load the world.
9. Check that it is now broken by using the list above.
10. Reload chunks containing glitched mobs.
11. They are gone.

**Additional context**
Tested on Forge 36.2.35 with just Citadel 1.8.1 and Ice and Fire 2.1.10-1.16.5.

**Comment by Xeltalliv** [comment]
Closing, since it got fixed in https://github.com/Alex-the-666/Ice_and_Fire/commit/92d9e327550100845283d66c9ce7d15f6bf8d260
