### ISSUE TITLE
Lightning dragon keep logging error at 2.1.10-1.16.5

### ISSUE THREAD

**Issue by GoForceX** [Alex-the-666/Ice_and_Fire#4624]
**Describe the bug**
Lighting dragon keeps logging error.

**Additional context**
Server log:
```
[11:11:25] [Server thread/ERROR] [minecraft/ChunkSerializer]: An Entity type entity.iceandfire.lightning_dragon has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1432) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bountifulbaubles.mixins.json:MixinEntity,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_fluid_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_184198_c(Entity.java:1346) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bountifulbaubles.mixins.json:MixinEntity,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_fluid_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:roadrunner.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70039_c(EntityDragonBase.java:2345) ~[iceandfire:2.1.10-1.16.5] {re:classloading}
        at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:303) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
        at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:687) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ChunkManager.func_219185_a(ChunkManager.java:406) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.world.server.ChunkManager.func_223155_b(ChunkManager.java:388) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ChunkManager.func_219204_a(ChunkManager.java:366) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.chunk_ticking.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:roadrunner.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:328) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_access.ServerChunkManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bountifulbaubles.mixins.json:MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NullPointerException
```

**Comment by TheBv** [comment]
Will be fixed in the upcoming version :)
