### ISSUE TITLE
Issues with Gradle Dependency Setup for Mod Integration [I&F 2.1.10 MC 1.16.5]

### ISSUE THREAD

**Issue by JayZX535** [Alex-the-666/Ice_and_Fire#4629]
I'm attempting to add Ice and Fire compatibility for one of my own mods, but I'm having an incredibly hard time setting it up as a gradle dependency.  I've managed to get Citadel functional with the following build.gradle setup, however Ice and Fire then throws errors upon launching Minecraft via Eclipse.

```
buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = '1.0'
group = 'modname.modname'
archivesBaseName = 'Modname'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))
minecraft {
    mappings channel: 'official', version: '1.16.5'

    runs {
        client {
            workingDirectory project.file('run')
			
	    property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            mods {
                modname {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
			
	    property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            mods {
                modname {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

	    property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            args '--mod', 'modname', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                modname {
                    source sourceSets.main
                }
            }
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {

    minecraft 'net.minecraftforge:forge:1.16.5-36.2.34'
    implementation fg.deobf("curse.maven:citadel-331936:3441028")
    implementation fg.deobf("curse.maven:iceandfire-264231:3441117")
}

// Example for how to get properties into the manifest for reading by the runtime..
jar {
    manifest {
        attributes([
            "Specification-Title": "modname",
            "Specification-Vendor": "JayZX535",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"JayZX535",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar') 

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
```

However, this leads to the following error--

```
-- MOD iceandfire --
Details:
	Mod File: iceandfire-264231-3441117_mapped_official_1.16.5.jar
	Failure message: Ice and Fire (iceandfire) has failed to load correctly
		java.lang.ClassFormatError: Duplicate method name "getScale" with signature "()F" in class file com/github/alexthe666/iceandfire/entity/EntityDeathWorm
	Mod Version: 2.1.9-1.16.5
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.ClassFormatError: Duplicate method name "getScale" with signature "()F" in class file com/github/alexthe666/iceandfire/entity/EntityDeathWorm
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.github.alexthe666.iceandfire.world.IafWorldRegistry.register(IafWorldRegistry.java:115) ~[iceandfire:2.1.9-1.16.5] {re:mixin,re:classloading}
	at com.github.alexthe666.iceandfire.IceAndFire.<init>(IceAndFire.java:105) ~[iceandfire:2.1.9-1.16.5] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?] {}
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.Class.newInstance(Class.java:645) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

I'm not positive if something is broken with Ice and Fire or if I've missed something about the Ice and Fire + Citadel combination in particular or if something has been going wrong on my end, but whatever the case may be, I figured this would be the best place to bring it up.  To repro, try and create a forge workspace with the above build.gradle file.  I've been using Eclipse.  Minecraft should launch, but display the "java.lang.ClassFormatError: Duplicate method name "getScale" with signature "()F" in class file com/github/alexthe666/iceandfire/entity/EntityDeathWorm" error before getting to the title screen.

Thanks in advance, and have a great day!

**Comment by TheBv** [comment]
That's an issue with the mappings.
Right now Ice and Fire like most 1.16.5 mods uses the unofficial mappings.
I think I was looking into upgrading to the official mappings but it didn't work since citadel uses the unofficial mappings as well and we need to directly refer to it.

So yeah this behavior most likely won't change for 1.16.

Edit: although if it's only complaining about those methods I might consider renaming them since we'll need to do that anyways at some point just don't bet on it happening...

**Comment by JayZX535** [comment]
Agh that's unfortunately, that's about what I figured :(  If you don't mind me asking here, is there any way I could revert back to the unofficial mappings on my end to get around this?  I don't mind being the one to apply a workaround if it means a workaround _does_ exist.

Completely fair-- and it _could_ be?  But, I'm not positive it isn't gonna be one of those "great!  you fixed one thing!  now you have a _new_ error :D" situations.  If it did work out I'd be stoked, but I'd hesitate to put too many eggs in that basket anyway-- that could just be the first error it hit and decided it couldn't continue from.

Thank you for your time!

**Comment by TheBv** [comment]
Yeah you can just refer to the ice and fire `build.gradle` for it more specifically this line: https://github.com/Alex-the-666/Ice_and_Fire/blob/e755d1f622092fc67f56d6fd58cbda6a4da18835/build.gradle#L51
Hopefully that should work right away :)

**Comment by JayZX535** [comment]
Oh!  Thank you so much, that branch wasn't showing up for me-- I'll go ahead and give it a shot!

**Comment by JayZX535** [comment]
Gonna go ahead and close this issue now-- I went ahead and set up again with the above mappings and they do work through 2.1.11, and it sounds like this is intended (or at least inevitable) behavior for the time being.  Thank you again for clearing this up!
