### ISSUE TITLE
Crash on load with Tinkers Defense

### ISSUE THREAD

**Issue by Biochao** [Alex-the-666/Ice_and_Fire#467]
```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ice and Fire (iceandfire)
Caused by: java.lang.NullPointerException
	at lance5057.tDefense.holiday.xmas.gumdropslime.GumDropSlimeRenderer.<init>(GumDropSlimeRenderer.java:18)
	at lance5057.tDefense.holiday.xmas.gumdropslime.GumDropSlimeRenderer$Factory.createRenderFor(GumDropSlimeRenderer.java:30)
	at com.github.alexthe666.iceandfire.event.EventClient.initializeStoneLayer(EventClient.java:60)
	at com.github.alexthe666.iceandfire.ClientProxy.postRender(ClientProxy.java:227)
	at com.github.alexthe666.iceandfire.IceAndFire.postInit(IceAndFire.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[crash-2018-02-11_11.54.19-client.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/1714619/crash-2018-02-11_11.54.19-client.txt)

**Comment by AlexModGuy** [comment]
try older or newer version

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by AlexModGuy** [comment]
fixed
