### ISSUE TITLE
Iceandfire (iceandfire) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by Nurb78** [Alex-the-666/Ice_and_Fire#4726]
![Captura](https://user-images.githubusercontent.com/123655828/214885999-7e3cbbda-a395-4d65-8867-f52cda032730.PNG)

I was trying to do a modpack to play with some friends of mine but when I try to open the game this thing appears, I've seen some people that got a similar issue to this one and I tried to downgrade the mod version and also this is the crash report that I got

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 26/01/23 11:05 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9315/1483208777.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9078/280925409.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/1750120280.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD iceandfire --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeSpawnEggItem
		at com.github.alexthe666.iceandfire.item.IafItemRegistry.registerItems(IafItemRegistry.java:398) ~[?:2.1.10-1.16.5] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_649_IafItemRegistry_registerItems_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2546/2140163850.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3179/1887922615.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:249) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2903/23604842.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2904/1348283308.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
		at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/1750120280.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

	Mod File: iceandfire-2.1.10-1.16.5.jar
	Failure message: Ice and Fire (iceandfire) encountered an error during the load_registries event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeSpawnEggItem
	Mod Version: 2.1.10-1.16.5
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.ForgeSpawnEggItem
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at com.github.alexthe666.iceandfire.item.IafItemRegistry.registerItems(IafItemRegistry.java:398) ~[?:2.1.10-1.16.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_649_IafItemRegistry_registerItems_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2546/2140163850.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3179/1887922615.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:249) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2903/23604842.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2904/1348283308.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/1750120280.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 561395472 bytes (535 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.4
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.90.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.90           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mowziesmobs-1.5.27.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.27              |COMMON_SET|Manifest: NOSIGNATURE
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.488-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.488   |COMMON_SET|Manifest: NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.2.11.jar          |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.2.11       |COMMON_SET|Manifest: NOSIGNATURE
		pitchperfect-1.0.2.jar                            |Pitch Perfect                 |pitchperfect                  |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Pirates_And_Looters_Kraken_Update.jar             |PiratesAndLootersReborn       |piratesandlootersreborn       |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.1004.jar                         |Just Enough Items             |jei                           |7.7.1.1004          |COMMON_SET|Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.16.jar                     |TerraForged                   |terraforged                   |0.2.16              |COMMON_SET|Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		EpicFight-16.6.4.jar                              |Epic Fight                    |epicfight                     |16.6.4              |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.16.5-FORGE-2.0.5.jar                  |Croptopia                     |croptopia                     |2.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-6.0.0.27.jar                               |Clumps                        |clumps                        |6.0.0.27            |COMMON_SET|Manifest: NOSIGNATURE
		camera-1.16.5-1.0.14.jar                          |Camera Mod                    |camera                        |1.16.5-1.0.14       |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.5.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.5      |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5 (1).jar                      |Citadel                       |citadel                       |1.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.127-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.127    |COMMON_SET|Manifest: NOSIGNATURE
		tombstone-1.16.5-6.5.5.jar                        |Corail Tombstone              |tombstone                     |6.5.5               |COMMON_SET|Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-11.0.10-forge.jar        |Better Animals Plus           |betteranimalsplus             |1.16.5-11.0.10      |COMMON_SET|Manifest: NOSIGNATURE
		Shark_Mod-0.2.jar                                 |Shark Mod                     |shark_mod                     |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		reliquary-1.16.5-1.3.5.1100.jar                   |Reliquary                     |xreliquary                    |1.16.5-1.3.5.1100   |COMMON_SET|Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.229.jar                  |U Team Core                   |uteamcore                     |3.2.1.229           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		lock-and-key-1.16.4-1.0.1.jar                     |Lock and Key                  |lock_and_key                  |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |COMMON_SET|Manifest: NOSIGNATURE
		iceandfire-2.1.10-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.10-1.16.5       |VALIDATE  |Manifest: NOSIGNATURE
		IronAgeFurniture-1.16.3-1.16.5-0.2.0.15.jar       |Iron Age Furniture            |ironagefurniture              |1.16.5-0.2.0.15     |COMMON_SET|Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |COMMON_SET|Manifest: NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |COMMON_SET|Manifest: NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-4.16.91-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.16.91             |COMMON_SET|Manifest: NOSIGNATURE
		NefsMedievalPub+v1.5(1.16.5).jar                  |Nef Deco Mod                  |nefdecomod                    |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.22.jar                      |Carry On                      |carryon                       |1.15.5.22           |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.16.5-2.11.6.jar                     |FallingTree                   |fallingtree                   |2.11.5              |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		smallships-1.16.5-1.10.1.jar                      |Small Ships Mod               |smallships                    |1.10.1              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-universal.jar                 |Forge                         |forge                         |36.2.4              |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |COMMON_SET|Manifest: NOSIGNATURE
		CAC+MOD+[1.16.5]+[2021.2-pre4].jar                |Caves And Cliffs mod [1.16.4] |caves_and_cliffs_mod          |MOD                 |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |COMMON_SET|Manifest: NOSIGNATURE
		antiqueatlas-6.2.3-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.2.3-forge-mc1.16.5|COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.49-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.49              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: a2a40e48-de53-4942-9792-194d03802f70
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4229
	OpenGlRenderer: Intel(R) HD Graphics 2000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Nurb78** [comment]
My Bad, I already solved it was only upgrade the forge versión to 39
