### ISSUE TITLE
[1.10.2] java.lang.Integer can not be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by kd8lvt** [Alex-the-666/Ice_and_Fire#474]
This crash only occurs on one of my computers, the other one is unaffected.
Crashlog: [Gist](https://gist.github.com/kd8lvt/0b7d4b90ac94675b22aac6c7e504ac57)
The only thing I could think of that is different (and matters) between the two computers is the CPU, which the one that works has an ADM Ryzen 5, and the one that doesn't has a Intel i5-6200U. The one that crashes has integrated graphics, the one that does work has dedicated, but I don't think that matters. My brother and I are playing on a LAN server, which might cause the issue as well.

**Comment by kd8lvt** [comment]
Update: Happens to any client of any server, not just integrated LAN. Switched to a dedicated server, and I am still encountering this issue.

**Comment by ddelaparte** [comment]
I get this similar error when connecting to a server running the mod:

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isHovering(EntityHippogryph.java:457)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:856)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by EPIICTHUNDERCAT** [comment]
put what version of MC in your title please ex: [1.12.2] IN FRONT of your title

**Comment by EPIICTHUNDERCAT** [comment]
gunna tell you right now, they arent working on 1.10.2 at all anymore.

**Comment by kd8lvt** [comment]
Well then. Good to know! I figured 1.10.2 was recent enough most people would still be fixing bugs at the very least. I guess I'll just wait for a couple more mods to update to 1.12 before messing about with dragons haha

**Comment by AlexModGuy** [comment]
1.10.2 issue
