### ISSUE TITLE
¡Help! Armor crash

### ISSUE THREAD

**Issue by Monrax25** [Alex-the-666/Ice_and_Fire#4750]
About a week ago I started playing the Ice And Fire mod with no problems on version 1.10.2, I was able to find several dragons and everything was fine. But it turns out that shortly after I killed one and removed the scales to make armor, everything started to slow me down to the point of collapsing. I checked by noticing that the FPS went down only when I turned my sight towards the armor mounts, I removed them and everything was fine, but if I put them back, either on the armor shelf or in my inventory, it happens again the same . I use TLauncher and I have already installed and tried other launchers such as SKLauncher and/or LauncherFenix, also, thinking that there was a compatibility problem with some file, I factory reset my PC, and nothing. It should be noted that I have already tried other versions of Minecraft and the same thing continues to happen to me. I have the OptiFine setting at minimum.
I have an Athlon 3000G processor with 8GB of RAM and a 240GB SSD where I have the game installed, plus a 1TB HDD.
I copied and pasted the ".minecraft" folder onto an old laptop I have and it works fine. I would greatly appreciate if someone can tell me what it is due to at least, and more give a solution.

Here is the crash code:

---- Minecraft Crash Report ----

WARNING: coremods are present:
   library (library-1.7.2-1.10.2.jar)
   TLSkinCapeHookLoader (tlskincape_1.10.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 02/22/23 14:10
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ice And Fire (iceandfire)
c
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:521)
at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-------------------------------------------------- -------------------------------------

Thanks in advance!

**Comment by TheBv** [comment]
Old versions are no longer actively maintained.
