### ISSUE TITLE
Pathfinding null pointer crash

### ISSUE THREAD

**Issue by bobafett155** [Alex-the-666/Ice_and_Fire#4757]
**NO SUGGESTIONS AT ALL**
This is not a repository for suggestions or issues not pertaining to the mod's code or gameplay.

**Describe the bug**
i go near a mob from the mod and the game crashes eg; death worm, somtimes dragons the most notiable been a green midium sized dragon.
**To Reproduce**
3. See error
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/27/23 5:19 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.processCompletedCalculationResult(AdvancedPathNavigate.java:549) ~[?:2.1.11-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75501_e(AdvancedPathNavigate.java:271) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:spartanweaponry.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:werewolves.mixins.json:LivingEntityInvoker,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexSentinel.func_70636_d(EntityMyrmexSentinel.java:78) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:spartanweaponry.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:werewolves.mixins.json:LivingEntityInvoker,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexBase.func_70071_h_(EntityMyrmexBase.java:217) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:tombstone.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$12536/519442243.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:tombstone.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$11738/1451529159.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.processCompletedCalculationResult(AdvancedPathNavigate.java:549) ~[?:2.1.11-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75501_e(AdvancedPathNavigate.java:271) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:spartanweaponry.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:werewolves.mixins.json:LivingEntityInvoker,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexSentinel.func_70636_d(EntityMyrmexSentinel.java:78) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:spartanweaponry.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:werewolves.mixins.json:LivingEntityInvoker,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at com.github.alexthe666.iceandfire.entity.EntityMyrmexBase.func_70071_h_(EntityMyrmexBase.java:217) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:tombstone.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$12536/519442243.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:myrmex_sentinel (com.github.alexthe666.iceandfire.entity.EntityMyrmexSentinel)
	Entity ID: 683
	Entity Name: Myrmex Sentinel
	Entity's Exact location: 224.50, 41.00, -943.50
	Entity's Block location: World: (224,41,-944), Chunk: (at 0,2,0 in 14,-59; contains blocks 224,0,-944 to 239,255,-929), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:tombstone.mixins.json:ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['SATURN_mike'/535, l='ServerLevel[hopeful no ocean]', x=180.46, y=68.02, z=-872.04]]
	Chunk stats: ServerChunkCache: 3417
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,64,192), Chunk: (at 0,4,0 in 1,12; contains blocks 16,0,192 to 31,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 64052 game time, 64052 day time
	Level name: hopeful no ocean
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 76838 (now: false), thunder time: 4562 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$11738/1451529159.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 481662232 bytes (459 MB) / 2435317760 bytes (2322 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		dynamiclightsreforged-mc1.16.5_v1.0.1.jar         |Dynamic Lights Reforged       |dynamiclightsreforged         |mc1.16.5_v1.0.1     |DONE      |Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.1.jar                   |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		TRansliterationLib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.1.jar                   |Abnormals Core                |abnormals_core                |3.3.1               |DONE      |Manifest: NOSIGNATURE
		stalwart-dungeons-1.16.5-1.1.7.jar                |Stalwart Dungeons             |stalwart_dungeons             |1.1.7               |DONE      |Manifest: NOSIGNATURE
		rubidium-0.2.11.jar                               |Rubidium                      |rubidium                      |0.2.11              |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.28.9_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.9              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.5.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.5      |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		OuterEnd-0.2.14.jar                               |The Outer End                 |outer_end                     |0.2.9               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.9.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.9               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.11-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.11-1.16.5       |DONE      |Manifest: NOSIGNATURE
		3dSkinLayers-forge-1.1.0.jar                      |3dSkinLayers                  |skinlayers3d                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		endergetic-1.16.5-3.0.2.jar                       |The Endergetic Expansion      |endergetic                    |3.0.2               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.5.jar                 |Supplementaries               |supplementaries               |0.18.2              |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		[Forge] Wildfire Female Gender Mod-2.8.jar        |Wildfire's Female Gender Mod  |wildfire_gender               |2.8                 |DONE      |Manifest: NOSIGNATURE
		Jade-1.16.4-2.8.3.jar                             |Jade                          |jade                          |2.8.3               |DONE      |Manifest: NOSIGNATURE
		FirstPersonMod-2.0.1.jar                          |FirstPersonModel Mod          |firstpersonmod                |2.0.1               |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		UnusualEnd1.16_V1.3.0.jar                         |Unusual End                   |unusualend                    |1.3.0               |DONE      |Manifest: NOSIGNATURE
		BRVSB-1.0.3-Hotfix-mc1.16.5.jar                   |Better Rubidium Video Settings|bsvsb                         |1.0.3-Hotfix-mc1.16.|DONE      |Manifest: NOSIGNATURE
		YungsBridges-Forge-1.16.4-1.0.1.jar               |YUNG's Bridges                |yungsbridges                  |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		weaponmaster-multi-forge-1.16.5-3.0.4.jar         |YDM's Weapon Master           |weaponmaster                  |3.0.4               |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.16.5-1.8.2.jar                |Dungeons Enhanced             |dungeons_enhanced             |1.8.2               |DONE      |Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.4-mc1.16.5.jar        |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.4-mc1.16.5      |DONE      |Manifest: NOSIGNATURE
		mostructures-forge-1.2.0-1.16.5.jar               |Mo' Structures                |mostructures                  |1.2.0-1.16.5        |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-1.2.4.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.2.4               |DONE      |Manifest: NOSIGNATURE
		rubidium-extra-0.4.14+mc1.16.5-build.52.jar       |Rubidium Extra                |sodiumextra                   |0.4.14+mc1.16.5-buil|DONE      |Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |DONE      |Manifest: NOSIGNATURE
		tombstone-6.8.10-1.16.5.jar                       |Corail Tombstone              |tombstone                     |6.8.10              |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		swiaf-1.16.5-1.1.2.jar                            |Spartan Weaponry: Ice and Fire|swiaf                         |1.16.5-1.1.2        |DONE      |Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.5-2.2.0-rc-2.jar             |Spartan Weaponry              |spartanweaponry               |2.2.0 Release Candid|DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.9.2.jar                        |Vampirism                     |vampirism                     |1.9.2               |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.16.5-1.1.0.0.jar                     |Werewolves                    |werewolves                    |1.1.0.0             |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.15.jar                        |Valhelsia Core                |valhelsia_core                |16.0.15             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 10bfb181-35c2-4f8a-a83f-f3baafa1832a
	Player Count: 1 / 8; [ServerPlayerEntity['SATURN_mike'/535, l='ServerLevel[hopeful no ocean]', x=180.46, y=68.02, z=-872.04]]
	Data Packs: vanilla, mod:dynamiclightsreforged, mod:betterdungeons, mod:wildfire_gender, mod:jade, mod:transliterationlib (incompatible), mod:firstpersonmod (incompatible), mod:dungeons_plus, mod:unusualend, mod:jei, mod:bsvsb (incompatible), mod:yungsbridges, mod:weaponmaster (incompatible), mod:abnormals_core, mod:dungeons_enhanced, mod:reeses_sodium_options (incompatible), mod:stalwart_dungeons, mod:rubidium (incompatible), mod:mostructures, mod:notenoughanimations (incompatible), mod:bettercaves (incompatible), mod:waystones (incompatible), mod:sodiumextra (incompatible), mod:clumps, mod:comforts, mod:citadel (incompatible), mod:alexsmobs, mod:yungsextras, mod:yungsapi, mod:outer_end, mod:tombstone, mod:dungeoncrawl, mod:betterstrongholds, mod:swiaf, mod:spartanweaponry, mod:cfm (incompatible), mod:vampirism, mod:werewolves, mod:iceandfire, mod:skinlayers3d, mod:forge, mod:endergetic, mod:appleskin, mod:valhelsia_core, mod:valhelsia_structures, mod:supplementaries, mod:bettermineshafts, mod:structure_gel, mod:selene, mod:xaeroworldmap
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
**Expected behavior**
it should not crash and should work with ease
**Screenshots**

**Additional context**
i go near a death worm or any mob from the mod pack and somtimes it crashes

**Comment by Cobyt3** [comment]
Same problem here
