### ISSUE TITLE
[Crash]: Siren ticking entity server crash [1.9.1-1.12.2]

### ISSUE THREAD

**Issue by Silivek** [Alex-the-666/Ice_and_Fire#4759]
### What happened?

My server was running and suddenly crashed. I do not know how to replicate it.
I am unsure if 1.12.2 is still supported but I'm making this bug report in case that it is.
I only have the crash report, not the log for the server.

### Minecraft Version

1.12.2

### Ice and Fire version

1.9.1-1.12.2

### LLib version

1.7.20-1.12.2

### Relevant log output

```shell
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.5-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-2.0.4.jar)
  TickCentral (TickCentral-3.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  ChunkGenLimiterCoremod (chunkgenlimiter-1.1-core.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.1.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.9.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2/28/23 1:53 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.entity.EntitySiren.func_70636_d(EntitySiren.java:203)
	at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.TickCentral_TrueOnUpdateTick(EntityMob.java:50)
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
	at com.github.terminatornl.tickcentral.api.TickInterceptor.redirectOnUpdate(TickInterceptor.java:28)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntitySiren.func_70636_d(EntitySiren.java:203)
	at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.TickCentral_TrueOnUpdateTick(EntityMob.java:50)
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
	at com.github.terminatornl.tickcentral.api.TickInterceptor.redirectOnUpdate(TickInterceptor.java:28)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:siren (com.github.alexthe666.iceandfire.entity.EntitySiren)
	Entity ID: 1345384
	Entity Name: Siren
	Entity's Exact location: 247.22, 56.52, -307.46
	Entity's Block location: World: (247,56,-308), Chunk: (at 7,3,12 in 15,-20; contains blocks 240,0,-320 to 255,255,-305), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.30, -0.01, 0.32
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 4 total; [EntityPlayerMP['WorbleWobble'/922004, l='world', x=-65.59, y=62.00, z=241.70], EntityPlayerMP['Chiberty'/920782, l='world', x=-370.17, y=29.00, z=930.80], EntityPlayerMP['ElasticBossCyrus'/6653, l='world', x=-378.70, y=29.00, z=928.30], EntityPlayerMP['StyrkerBlade'/1100876, l='world', x=246.27, y=54.75, z=-308.45]]
	Chunk stats: ServerChunkCache: 1324 Drop: 0
	Level seed: -169829230054689956
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-16,64,248), Chunk: (at 0,4,8 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 263536 game time, 397635 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 4272 (now: false), thunder time: 159992 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1637558136 bytes (1561 MB) / 9537323008 bytes (9095 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx12288M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 95 mods loaded, 95 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version           | Source                                        | Signature                                |
	|:------ |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore              | 7.7.4             | minecraft.jar                                 | None                                     |
	| LCHIJA | tickcentral              | 3.2               | TickCentral-3.2.jar                           | None                                     |
	| LCHIJA | additionalbanners        | 1.1.77            | AdditionalBanners-1.12.2-1.1.77.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | aether_legacy            | 1.5.3.2           | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LCHIJA | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
	| LCHIJA | jei                      | 4.16.1.1001       | jei_1.12.2-4.16.1.1001.jar                    | None                                     |
	| LCHIJA | appleskin                | 1.0.14            | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCHIJA | aroma1997core            | 2.0.0.2.b167      | Aroma1997Core-1.12.2-2.0.0.2.b167.jar         | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackup              | 3.0.0.0.b135      | AromaBackup-1.12.2-3.0.0.0.b135.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackuprecovery      | 3.0.0.0.b135      | AromaBackup-1.12.2-3.0.0.0.b135.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | artifacts                | 1.12.2-1.2.3      | Artifacts-1.12.2-1.2.3.jar                    | None                                     |
	| LCHIJA | astralsorcery            | 1.10.27           | astralsorcery-1.12.2-1.10.27.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | atum                     | 2.0.20            | Atum-1.12.2-2.0.20.jar                        | None                                     |
	| LCHIJA | tombstone                | 4.6.1             | tombstone-4.6.1-1.12.2.jar                    | None                                     |
	| LCHIJA | quark                    | r1.6-179          | Quark-r1.6-179.jar                            | None                                     |
	| LCHIJA | autoreglib               | 1.3-32            | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | bettercaves              | 1.12.2            | bettercaves-1.12.2-2.0.4.jar                  | None                                     |
	| LCHIJA | bettermineshafts         | 1.12.2-2.2.1      | BetterMineshaftsForge-1.12.2-2.2.1.jar        | None                                     |
	| LCHIJA | llibrary                 | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs              | 1.5.8             | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHIJA | patchouli                | 1.0-23.6          | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCHIJA | thaumcraft               | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | bewitchment              | 0.22.63           | bewitchment-1.12.2-0.0.22.64.jar              | None                                     |
	| LCHIJA | bibliocraft              | 2.4.6             | BiblioCraft[v2.4.6][MC1.12.2].jar             | None                                     |
	| LCHIJA | byg                      | 1.7.1             | BiomesYouGo1.7.1.jar                          | None                                     |
	| LCHIJA | guideapi                 | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
	| LCHIJA | bloodmagic               | 1.12.2-2.4.3-105  | BloodMagic-1.12.2-2.4.3-105.jar               | None                                     |
	| LCHIJA | bloodmoon                | 1.5.3             | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bountifulbaubles         | 0.0.1             | Bountiful Baubles-1.12.2-0.1.8.jar            | None                                     |
	| LCHIJA | forgelin                 | 1.8.4             | Forgelin-1.8.4.jar                            | None                                     |
	| LCHIJA | bountiful                | 2.2.3             | Bountiful-1.12.2-2.2.3.jar                    | None                                     |
	| LCHIJA | champions                | 1.12.2-1.0.11.10  | champions-1.12.2-1.0.11.10.jar                | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | clumps                   | 3.1.2             | Clumps-3.1.2.jar                              | None                                     |
	| LCHIJA | collective               | 3.0               | collective-1.12.2-3.0.jar                     | None                                     |
	| LCHIJA | cyclepaintings           | 2.0               | cyclepaintings_1.12.2-2.0.jar                 | None                                     |
	| LCHIJA | fantasticlib             | 1.12.2.047        | FantasticLib-1.12.2.047.jar                   | None                                     |
	| LCHIJA | dynamicstealth           | 1.12.2.114        | DynamicStealth-1.12.2.114.jar                 | None                                     |
	| LCHIJA | erebus                   | 1.0.32            | Erebus-1.0.32.jar                             | None                                     |
	| LCHIJA | fastfurnace              | 1.3.1             | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
	| LCHIJA | fastleafdecay            | v14               | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA | fastbench                | 1.7.4             | FastWorkbench-1.12.2-1.7.4.jar                | None                                     |
	| LCHIJA | foamfix                  | @VERSION@         | foamfix-0.10.15-1.12.2.jar                    | None                                     |
	| LCHIJA | ftblib                   | 5.4.7.2           | FTBLib-5.4.7.2.jar                            | None                                     |
	| LCHIJA | ftbutilities             | 5.4.1.131         | FTBUtilities-5.4.1.131.jar                    | None                                     |
	| LCHIJA | futuremc                 | 0.2.6             | future-mc-0.2.11.jar                          | None                                     |
	| LCHIJA | gokistats                | 1.2.10            | GokiStats-1.2.10.jar                          | None                                     |
	| LCHIJA | waila                    | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | iceandfire               | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHIJA | inventorysorter          | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar          | None                                     |
	| LCHIJA | journeymap               | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | libraryex                | 1.2.2             | LibraryEx-1.12.2-1.2.2.jar                    | None                                     |
	| LCHIJA | livingenchantment        | 3.2.3             | living_enchantment-3.2.3.jar                  | None                                     |
	| LCHIJA | timecore                 | 1.0.1.1           | TimeCore-1.12.2-1.0.1.1.jar                   | None                                     |
	| LCHIJA | lootgames                | 1.0.3.1           | LootGames-1.12.2-1.0.3.1.jar                  | None                                     |
	| LCHIJA | mcwbridges               | 1.0.6             | mcw-bridges-1.0.6b-mc1.12.2.jar               | None                                     |
	| LCHIJA | mcwpaintings             | 1.0.4             | mcw-paintings-1.0.4-mc1.12.2.jar              | None                                     |
	| LCHIJA | testdummy                | 1.12              | MmmMmmMmmMmm-1.12-1.14.jar                    | None                                     |
	| LCHIJA | morpheus                 | 1.12.2-3.5.106    | Morpheus-1.12.2-3.5.106.jar                   | None                                     |
	| LCHIJA | naturescompass           | 1.8.5             | NaturesCompass-1.12.2-1.8.5.jar               | None                                     |
	| LCHIJA | netherex                 | 2.2.5             | NetherEx-1.12.2-2.2.5.jar                     | None                                     |
	| LCHIJA | placebo                  | 1.6.0             | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCHIJA | progressivebosses        | 1.5.4             | ProgressiveBosses-1.5.4-mc1.12.x.jar          | None                                     |
	| LCHIJA | quarkoddities            | 1                 | QuarkOddities-1.12.2.jar                      | None                                     |
	| LCHIJA | xreliquary               | 1.12.2-1.3.4.796  | Reliquary-1.12.2-1.3.4.796.jar                | None                                     |
	| LCHIJA | roguelike                | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCHIJA | jeid                     | 2.0.4             | RoughlyEnoughIDs-2.0.4.jar                    | None                                     |
	| LCHIJA | rustic                   | 1.1.7             | rustic-1.1.7.jar                              | None                                     |
	| LCHIJA | savemystronghold         | 1.12.2-1.0.0      | savemystronghold-1.12.2-1.0.0.jar             | None                                     |
	| LCHIJA | snad                     | 1.12.1-1.7.09.16a | Snad-1.12.1-1.7.09.16a.jar                    | None                                     |
	| LCHIJA | spark                    | 1.6.3             | spark-forge.jar                               | None                                     |
	| LCHIJA | spartanbewitchment       | 1.0               | spartanbewitchment-1.0.jar                    | None                                     |
	| LCHIJA | xat                      | 0.31.4            | Trinkets and Baubles-0.31.4.jar               | None                                     |
	| LCHIJA | spartanweaponry          | 1.5.1             | SpartanWeaponry-1.12.2-1.5.1.jar              | None                                     |
	| LCHIJA | spartanfire              | 0.08              | spartanfire-0.08.jar                          | None                                     |
	| LCHIJA | spartanshields           | 1.5.5             | SpartanShields-1.12.2-1.5.5.jar               | None                                     |
	| LCHIJA | twilightforest           | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | spartantwilight          | 1.2.0             | spartantwilight-1.12.2-1.2.0.jar              | None                                     |
	| LCHIJA | spartanweaponryarcana    | beta 1.0.3        | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar   | None                                     |
	| LCHIJA | stg                      | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCHIJA | teamsync                 | 1.0.1             | teamsync-1.0.1.jar                            | None                                     |
	| LCHIJA | thaumicaugmentation      | 1.12.2-2.1.9      | ThaumicAugmentation-1.12.2-2.1.9.jar          | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCHIJA | tcinventoryscan          | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar    | None                                     |
	| LCHIJA | waystones                | 4.1.0             | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCHIJA | phosphor-lighting        | 1.12.2-0.2.7      | phosphor-forge-mc1.12.2-0.2.7-universal.jar   | None                                     |
	| LCHIJA | thebetweenlands          | 3.9.5             | TheBetweenlands-3.9.5-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.5-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  
PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-2.0.4.jar)
  org.dimdev.jeid.JEIDTransformer
TickCentral (TickCentral-3.2.jar)
  com.github.terminatornl.tickcentral.asm.BlockTransformer
  com.github.terminatornl.tickcentral.asm.ITickableTransformer
  com.github.terminatornl.tickcentral.asm.EntityTransformer
  com.github.terminatornl.tickcentral.asm.HubAPITransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
ChunkGenLimiterCoremod (chunkgenlimiter-1.1-core.jar)
  io.github.barteks2x.chunkgenlimiter.coremod.ChunkGenLimitTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.1.jar)
  
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.9.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
	Profiler Position: N/A (disabled)
	Player Count: 4 / 20; [EntityPlayerMP['WorbleWobble'/922004, l='world', x=-65.59, y=62.00, z=241.70], EntityPlayerMP['Chiberty'/920782, l='world', x=-370.17, y=29.00, z=930.80], EntityPlayerMP['ElasticBossCyrus'/6653, l='world', x=-378.70, y=29.00, z=928.30], EntityPlayerMP['StyrkerBlade'/1100876, l='world', x=246.27, y=54.75, z=-308.45]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Silivek** [comment]
I see now that 1.12.2 is not supported.
