### ISSUE TITLE
[Bug]: Game crashing the exact moment I load into any world

### ISSUE THREAD

**Issue by LokaleChinees** [Alex-the-666/Ice_and_Fire#4763]
### What happened?

I have recently installed the mod (ice&fire, citadel, forge), and the game starts just fine. However, when I generate a new world, as soon as it joins, it crashes (it loads in for like a frame). After that, it displays "saving world", followed by a Microsoft error stating that the game has stopped responding. 

I did not receive a log, but the code I received was: -805306369

I have tried clearing my config multiple times, I've thoroughly searched for a fix on any platform possible, and I have restarted my device and game multiple times. 

When opening my logbook, it shows a normal startup right up until it starts going into a loop of:

[22:04:09] [main/ERROR] [minecraft/MainWindow]: ########## GL ERROR ##########
[22:04:09] [main/ERROR] [minecraft/MainWindow]: @ Render
[22:04:09] [main/ERROR] [minecraft/MainWindow]: 65540: Invalid time inf

It infinitely continues, or at least it has for over a million lines within a few minutes.

^ THIS IS WHY I HAVENT BEEN ABLE TO LIST THE FULL LOG OUTPUT, SIMPLY IMPOSSIBLE

It also seems that the mod is somehow having trouble loading its config. 

### Minecraft Version

1.16

### Ice and Fire version

2.1.11

### Citadel version

1.8.1

### Relevant log output

```shell
Version does not support log configuration, will assume one plaintext entry per line
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by LokaleChinees** [comment]
Update: I have gotten a crash report.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2-3-23 23:25
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3638/772791273.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3417/998004967.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/501036152.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
-- MOD iceandfire --
Details:
	Mod File: iceandfire-2.1.11-1.16.5.jar
	Failure message: Mod iceandfire requires citadel between 1.8.1 and 1.8.99 (inclusive)
		Currently, citadel is 1.7.0
	Mod Version: 2.1.11-1.16.5
	Mod Issue URL: https://github.com/Alex-the-666/ice-and-fire/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.CrashReportExtender$$Lambda$3668/347239869.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3638/772791273.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3417/998004967.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/501036152.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3954103992 bytes (3770 MB) / 4496293888 bytes (4288 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |NONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |NONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

**Comment by TheBv** [comment]
Upgrade your citadel version to this one: https://www.curseforge.com/minecraft/mc-mods/citadel/files/3441028
That should fix it :)

**Comment by LokaleChinees** [comment]
> Upgrade your citadel version to this one: https://www.curseforge.com/minecraft/mc-mods/citadel/files/3441028 That should fix it :)

It already is on that version; 1.8.1.

**Comment by TheBv** [comment]
It literally states otherwise in the crash log you provided
```
Failure message: Mod iceandfire requires citadel between 1.8.1 and 1.8.99 (inclusive)
Currently, citadel is 1.7.0
```

**Comment by LokaleChinees** [comment]
> It literally states otherwise in the crash log you provided
> 
> ```
> Failure message: Mod iceandfire requires citadel between 1.8.1 and 1.8.99 (inclusive)
> Currently, citadel is 1.7.0
> ```

that is incredibly weird, I will download a different version and reach back to you

**Comment by LokaleChinees** [comment]
> It literally states otherwise in the crash log you provided
> 
> ```
> Failure message: Mod iceandfire requires citadel between 1.8.1 and 1.8.99 (inclusive)
> Currently, citadel is 1.7.0
> ```

No idea why it states this, but the citadel that I have installed is 1.8.1 1.16.5, if have reinstalled all mods multiple times without effect.

here is the most recent crash log
[crash-2023-03-02_23.25.46-fml.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/10882377/crash-2023-03-02_23.25.46-fml.txt)

**Comment by TheBv** [comment]
Still the same. You must have installed it in the wrong folder.

**Comment by LokaleChinees** [comment]
> Still the same. You must have installed it in the wrong folder.

download 1.8.1 1.16.5 --> move from downloads to "Mods" folder (along with fire & ice dragons mod)
download forge --> install client

open game with forge 1.16.5

did I miss anything?

**Comment by TheBv** [comment]
Make sure you move them in the right mods folder. You could have multiple depending on how you installed forge previously.
Try deleting all the mods in the mods folder and see if the game launches then. That would be an easy way to test.

**Comment by LokaleChinees** [comment]
> Make sure you move them in the right mods folder. You could have multiple depending on how you installed forge previously. Try deleting all the mods in the mods folder and see if the game launches then. That would be an easy way to test.

it launches normally w/o the mods

However, even without the mods, it still fails to spawn into a world. 

In other words: I think forge is the issue here.

**Comment by TheBv** [comment]
Oh maybe the crash-log is out of date here as well.
Could you try uploading your latest.log/debug.log instead? That would help a lot!

**Comment by LokaleChinees** [comment]
> Oh maybe the crash-log is out of date here as well. Could you try uploading your latest.log/debug.log instead? That would help a lot!
[debug-1.log.gz](https://github.com/AlexModGuy/Ice_and_Fire/files/10882728/debug-1.log.gz)

[2023-03-03-12.log.gz](https://github.com/AlexModGuy/Ice_and_Fire/files/10882726/2023-03-03-12.log.gz)

here are both my latest logs and debug logs

the latest debug log is from ~5 minutes ago
the latest log is from a few hours ago

**Comment by TheBv** [comment]
Yeah okay no idea what is going on here. Definitely not an Ice and Fire issue and I've never seen this before.
```
java.lang.ArithmeticException: / by zero
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:945) ~[?:?]
```
Would be the reason why it crashes.
And then there's a bunch of OpenGL errors
```
[03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: ########## GL ERROR ##########
[03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: @ Render
[03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: 65540: Invalid time inf
```
I think they are related to the previous error though.

Quickly looked at the forge minecraft code. The lines sadly don't match up but the only divide operation I can find is related to "this.mc.gameSettings.framerateLimit;" Any chance you've somehow set that to the value `0`?
No idea how that's even possible but yeah that's my best guess.
I must admit I prolly won't look any further into this anymore...

**Comment by LokaleChinees** [comment]
> Yeah okay no idea what is going on here. Definitely not an Ice and Fire issue and I've never seen this before.
> 
> ```
> java.lang.ArithmeticException: / by zero
> 	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:945) ~[?:?]
> ```
> 
> Would be the reason why it crashes. And then there's a bunch of OpenGL errors
> 
> ```
> [03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: ########## GL ERROR ##########
> [03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: @ Render
> [03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: 65540: Invalid time inf
> ```
> 
> I think they are related to the previous error though.
> 
> Quickly looked at the forge minecraft code. The lines sadly don't match up but the only divide operation I can find is related to "this.mc.gameSettings.framerateLimit;" Any chance you've somehow set that to the value `0`? No idea how that's even possible but yeah that's my best guess. I must admit I prolly won't look any further into this anymore...

I have decided to contact the forge tech support instead as this seems to be their issue, thanks for your time anyway

**Comment by LokaleChinees** [comment]
> Yeah okay no idea what is going on here. Definitely not an Ice and Fire issue and I've never seen this before.
> 
> ```
> java.lang.ArithmeticException: / by zero
> 	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:945) ~[?:?]
> ```
> 
> Would be the reason why it crashes. And then there's a bunch of OpenGL errors
> 
> ```
> [03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: ########## GL ERROR ##########
> [03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: @ Render
> [03mrt2023 14:28:10.191] [main/ERROR] [net.minecraft.client.MainWindow/]: 65540: Invalid time inf
> ```
> 
> I think they are related to the previous error though.
> 
> Quickly looked at the forge minecraft code. The lines sadly don't match up but the only divide operation I can find is related to "this.mc.gameSettings.framerateLimit;" Any chance you've somehow set that to the value `0`? No idea how that's even possible but yeah that's my best guess. I must admit I prolly won't look any further into this anymore...

You were correct! My max framerate limit was on 0fps for some reason (never touched it), and it works now. Thank you so much!
