### ISSUE TITLE
[Bug]: Pathfinding exception with Rubidium 0.2.11 (no crash)

### ISSUE THREAD

**Issue by wasdspace** [Alex-the-666/Ice_and_Fire#4767]
### What happened?

```
[04Mar2023 22:30:53.779] [Ice and Fire Pathfinding Worker #0/WARN] [com.github.alexthe666.iceandfire.IceAndFire/]: Pathfinding Exception
java.lang.IllegalStateException: Unable to get Y-rotated facing of down
	at net.minecraft.util.Direction.func_176746_e(Direction.java:170) ~[?:?]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.isPassableBBDown(AbstractPathJob.java:1381) ~[iceandfire:2.1.12-1.16.5-SNAPSHOT+build.2023-02-28]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walkCurrentNode(AbstractPathJob.java:663) ~[iceandfire:2.1.12-1.16.5-SNAPSHOT+build.2023-02-28]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.search(AbstractPathJob.java:596) ~[iceandfire:2.1.12-1.16.5-SNAPSHOT+build.2023-02-28]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.PathJobMoveToLocation.search(PathJobMoveToLocation.java:62) ~[iceandfire:2.1.12-1.16.5-SNAPSHOT+build.2023-02-28]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.call(AbstractPathJob.java:541) [iceandfire:2.1.12-1.16.5-SNAPSHOT+build.2023-02-28]
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.call(AbstractPathJob.java:46) [iceandfire:2.1.12-1.16.5-SNAPSHOT+build.2023-02-28]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
Unlike https://github.com/AlexModGuy/Ice_and_Fire/issues/4746, I have no crashes. And I think should open an issue,cus it's not like a Rubidium problem after all.

### Minecraft Version

1.16

### Ice and Fire version

Development Build 2023-02-28

### Citadel version

1.8.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Shouldn't be anything to worry about.
Most likely a modded block that can't be rotated which is need to test for some pass-ability. 
I still would like to look into this, since it might flag some areas as not passable even though it should be.

**Comment by Kasualix** [comment]
https://github.com/Asek3/Rubidium/issues/418

**Comment by wasdspace** [comment]
Is it time to reevaluate the priority of this issue? It seems to be prone to serious log pollution and causes lag. One time my lastlog even reached 5mb.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/236596683-b4558061-2461-4a39-b78a-568e2bb5d792.png)


it should definitely be reevaluated

**Comment by itsdinkd** [comment]
happening on 1.18.2

**Comment by I2pRandom** [comment]
I'm having the same error. I can stop it be killing either the Dragon, or SeaSerpent mobs. 
I have not had a chance to test it with the other mobs.
