### ISSUE TITLE
[Bug]: pathfinding crash id code -1 Dragon ploblem

### ISSUE THREAD

**Issue by Chewbacca3105** [Alex-the-666/Ice_and_Fire#4771]
### What happened?

Well I have been playing this Minecraft world for 48 hours and I had excellent stuff in it once I tried to fight a 5-6 stage lighting dragon and as soon as I started my game crashed and I cant get into the world whenever I try, i have put the crash report in this so try to make sense of this. also, I am running the curse forge app

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.11-1.16.5.jar

### Citadel version

citadel-1.8.1-1.16.5.jar

### Relevant log output

```shell
java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.processCompletedCalculationResult(AdvancedPathNavigate.java:549) ~[?:2.1.11-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75501_e(AdvancedPathNavigate.java:271) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading,re:mixin}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1728) ~[?:2.1.11-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityLightningDragon.func_70636_d(EntityLightningDragon.java:235) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1688) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.server.ServerWorld$$Lambda$7749/1284751628.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$7319/1018099286.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.processCompletedCalculationResult(AdvancedPathNavigate.java:549) ~[?:2.1.11-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75501_e(AdvancedPathNavigate.java:271) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading,re:mixin}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1728) ~[?:2.1.11-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityLightningDragon.func_70636_d(EntityLightningDragon.java:235) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1688) ~[?:2.1.11-1.16.5] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.world.server.ServerWorld$$Lambda$7749/1284751628.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: iceandfire:lightning_dragon (com.github.alexthe666.iceandfire.entity.EntityLightningDragon)
	Entity ID: 142
	Entity Name: Lightning Dragon
	Entity's Exact location: -191.02, 10.88, -755.16
	Entity's Block location: World: (-192,10,-756), Chunk: (at 0,0,12 in -12,-48; contains blocks -192,0,-768 to -177,255,-753), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,re:mixin}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Chewbacca_3105'/61, l='ServerLevel[ME vs dragon]', x=-204.94, y=17.88, z=-771.52]]
	Chunk stats: ServerChunkCache: 3768
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,69,80), Chunk: (at 0,4,0 in 14,5; contains blocks 224,0,80 to 239,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 90592 game time, 37451 day time
	Level name: ME vs dragon
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 19382 (now: false), thunder time: 6035 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$7319/1018099286.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Not an issue anymore since 2.1.12
