### ISSUE TITLE
[Bug]: The client closes when he wants to start a new world

### ISSUE THREAD

**Issue by ORLONFROSKO** [Alex-the-666/Ice_and_Fire#4795]
### What happened?

When I want to start a new world the load does not exceed 0% and the client closes me and gives me this error report
https://mclo.gs/rrR7lsS

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3/1.11.2

### Relevant log output

```shell
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8387_(ServerChunkCache.java:425) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:471) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar#56!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Seems to be an issue with OptiFine. No idea why though. I'll look into it.

**Comment by TheBv** [comment]
OptiFine_1.18.2_HD_U_H7 is only officially compatible with forge versions up to 40.0.24
Consider using one of the preview versions of OptiFine or a different version of forge (minimum 40.1.37)
