### ISSUE TITLE
[Bug]: Pathfinding exception 

### ISSUE THREAD

**Issue by dankxen0n** [Alex-the-666/Ice_and_Fire#4879]
### What happened?

was exploring a world whilst testing out a custom modpack for a server i was gonna host for some friends, noticed i hadn't seen any Ice and Fire structures at all, decided to do a /locate for a Gorgon structure. teleported to it, and the world immediately froze 
latest.log will be pasted below because it wont fit in the character limit
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/11525948/latest.log)

### Minecraft Version

1.16

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by I2pRandom** [comment]
I'm getting a similar error with Path tracing. 
on I&F version 2.1.12-1.16.5, and Citadel version 1.8.1.
Currently profiling MC and not really paying attention to everything in the game atm, My log is too large to upload as i'm unaware when the log began getting flooded with this error. 

`[07:36:04] [Ice and Fire Pathfinding Worker #0/WARN] [co.gi.al.ic.IceAndFire/]: Pathfinding Exception
java.lang.IllegalStateException: Unable to get Y-rotated facing of down
	at net.minecraft.util.Direction.func_176746_e(Direction.java:170) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinDirection,pl:mixin:APP:roadrunner.mixins.json:math.fast_blockpos.DirectionMixin,pl:mixin:APP:roadrunner.mixins.json:math.fast_util.DirectionMixin,pl:mixin:APP:rhino-common.mixins.json:DirectionMixin,pl:mixin:A}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.isPassableBBDown(AbstractPathJob.java:1381) ~[iceandfire:2.1.12-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walkCurrentNode(AbstractPathJob.java:663) ~[iceandfire:2.1.12-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.search(AbstractPathJob.java:596) ~[iceandfire:2.1.12-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.PathJobMoveToLocation.search(PathJobMoveToLocation.java:62) ~[iceandfire:2.1.12-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.call(AbstractPathJob.java:541) [iceandfire:2.1.12-1.16.5] {re:classloading}
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.call(AbstractPathJob.java:46) [iceandfire:2.1.12-1.16.5] {re:classloading}
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_302] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302] {}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302] {}
`

**Comment by TheBv** [comment]
Fixed with 41d3b3c
