### ISSUE TITLE
[Bug]: Random crash during the middle of my game, error code -1

### ISSUE THREAD

**Issue by TempAccount693** [Alex-the-666/Ice_and_Fire#4886]
Was in the middle of a game when it suddenly crashed.

Error: java.lang.NullPointerException: Cannot invoke "com.github.alexthe666.citadel.client.model.TabulaModel.getCube(String)" because "maleModel" is null.

https://pastebin.com/xmEdwxQP

Other mods installed (forge 1.18):
Aquaculture
Astikor Carts
Batty's Coordinates
Betteranimalsplus and betteranimalmodels
Building Gadgets
Connectible Chains
Corail Recycler
Exotic Birds
Forever A Child
Get in the bucket
Hole filler mod
Inventory Sorter
Lava Sponge
Mouse Tweaks
Rubidium + Rubidium Extra
Simply Jetpacks 2
Vanilla Hammers
WTHIT

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
https://pastebin.com/xmEdwxQP
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by landintrees** [comment]
I suspect you might have uploaded the wrong log? The one you provided was a failure at startup due to missing citidel. I just had the same "maleModel is null" error in the middle of a game on 1.18.2 and the log began with:

`
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "com.github.alexthe666.citadel.client.model.TabulaModel.getCube(String)" because "maleModel" is null
	at com.github.alexthe666.iceandfire.client.model.animator.DragonTabulaModelAnimator.genderMob(DragonTabulaModelAnimator.java:274) ~[iceandfire-2.1.12-1.18.2-beta2.jar%23104!/:2.1.12-1.18.2-beta2] {re:classloading}
	at com.github.alexthe666.iceandfire.client.model.animator.DragonTabulaModelAnimator.setRotationsLoop(DragonTabulaModelAnimator.java:148) ~[iceandfire-2.1.12-1.18.2-beta2.jar%23104!/:2.1.12-1.18.2-beta2] {re:classloading}
	at com.github.alexthe666.iceandfire.client.model.animator.DragonTabulaModelAnimator.setRotationAngles(DragonTabulaModelAnimator.java:72) ~[iceandfire-2.1.12-1.18.2-beta2.jar%23104!/:2.1.12-1.18.2-beta2] {re:classloading}
	at com.github.alexthe666.iceandfire.client.model.animator.DragonTabulaModelAnimator.setRotationAngles(DragonTabulaModelAnimator.java:12) ~[iceandfire-2.1.12-1.18.2-beta2.jar%23104!/:2.1.12-1.18.2-beta2] {re:classloading}
	at com.github.alexthe666.citadel.client.model.TabulaModel.m_6973_(TabulaModel.java:92) ~[citadel-1.11.3-1.18.2.jar%2382!/:1.11.3-1.18.2] {re:classloading,pl:runtimedistcleaner:A}
`
