### ISSUE TITLE
[Bug]: Server sometimes freeze when killing a dragon

### ISSUE THREAD

**Issue by LanceFoudre** [Alex-the-666/Ice_and_Fire#4904]
### What happened?

Server will randomly freeze completely right after a player kill a dragon, no crash, trying to reconnect will result in a time-out, the server has to be restarted in order to be able to play again (Which causes a pretty significant rollback)

The console show little information as for what really happens : 
[ConsoleError.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11787494/ConsoleError.txt)

This specific lines will keep repeating too

here's our modlist:
[modlist.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11787509/modlist.txt)

EDIT : After some testing it would seem this issue only happen on the server, not when played in singleplayer

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
19.06 10:46:10 [Server] Server thread/[ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5ed8f7f4, suppressing error
19.06 10:46:10 [Server] [INFO] java.lang.NullPointerException: Cannot invoke "net.minecraft.world.inventory.AbstractContainerMenu.m_6772_()" because "c" is null
19.06 10:46:10 [Server] [INFO] at net.minecraftforge.network.NetworkHooks.openGui(NetworkHooks.java:203) ~[forge-1.18.2-40.2.4-universal.jar%23250!/:?] {re:classloading}
19.06 10:46:10 [Server] [INFO] at net.minecraftforge.network.NetworkHooks.openGui(NetworkHooks.java:171) ~[forge-1.18.2-40.2.4-universal.jar%23250!/:?] {re:classloading}
19.06 10:46:10 [Server] [INFO] at com.mrcrayfish.furniture.block.CrateBlock.m_6227_(CrateBlock.java:111) ~[cfm-7.0.0-pre35-1.18.2.jar%2371!/:7.0.0-pre35-1.18.2] {re:classloading}
19.06 10:46:10 [Server] [INFO] at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:697) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:342) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinServerPlayerGameMode,pl:mixin:APP:survive.mixins.json:ServerPlayerGameModeMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:985) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:classloading}
19.06 10:46:10 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:classloading}
19.06 10:46:10 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:classloading}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:classloading,re:mixin}
19.06 10:46:10 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
19.06 10:46:10 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:computing_frames,re:mixin,re:classloading}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:unionlib.mixins.json:MinecraftServerMixin,pl:mixin:A}
19.06 10:46:10 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Ran-git0** [comment]
Same problem for me, but it crashes my server because it freezes for 3-4 minutes up to 10 minutes! :(

**Comment by LanceFoudre** [comment]
Well, good to know I'm not alone at least!
If you have a modlist, it would be good to share, so we can pinpoint the problem a little better maybe

**Comment by SiverDX** [comment]
not enough information
the console output references an issue with https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod

for deadlocked servers (and in general) i recommend installing modernfix as it does thread dumps which provide needed information
