### ISSUE TITLE
[Bug]: Crash while hitting a fire dragon

### ISSUE THREAD

**Issue by Lampt3rn** [Alex-the-666/Ice_and_Fire#4960]
### What happened?

I was going to attack this fire dragon and then (when I assumed I hit it) the game crashed. When I tried rejoining the world, it crashed again with the same error/crash.
First crash: [crash-2023-09-07_22.20.25-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/12555052/crash-2023-09-07_22.20.25-server.txt)
Second Crash: [crash-2023-09-07_22.32.54-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/12555055/crash-2023-09-07_22.32.54-server.txt)

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
[07Sep2023 22:20:18.552] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Unable to play empty soundEvent: isleofberk:entity.deadly_nadder.sting
[07Sep2023 22:20:19.250] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Unable to play empty soundEvent: isleofberk:entity.deadly_nadder.bite
[07Sep2023 22:20:20.601] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Unable to play empty soundEvent: isleofberk:entity.deadly_nadder.hurt
[07Sep2023 22:20:25.337] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because "p_36042_" is null
	at net.minecraft.world.entity.player.Inventory.m_36040_(Inventory.java:241) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.player.Inventory.m_36054_(Inventory.java:237) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.m_142470_(AbstractArrow.java:486) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.m_6123_(AbstractArrow.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.player.Player.m_36277_(Player.java:556) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:523) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23173!/:?]
	... 6 more
[07Sep2023 22:20:25.547] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 675a9e4d-8c26-4717-bc36-5932067c5ad9
[07Sep2023 22:20:25.561] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\Users\willi\AppData\Roaming\.minecraft\crash-reports\crash-2023-09-07_22.20.25-server.txt
[07Sep2023 22:20:25.563] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[07Sep2023 22:20:25.588] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[07Sep2023 22:20:25.608] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID b95bc9c0-0105-4bf7-8f42-7c5f393a70e6
[07Sep2023 22:20:25.698] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Lamptern lost connection: Disconnected
[07Sep2023 22:20:25.699] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Lamptern left the game
[07Sep2023 22:20:25.809] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out
[07Sep2023 22:20:25.810] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[07Sep2023 22:20:27.964] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[[Internal Screaming]]'/minecraft:overworld
[07Sep2023 22:20:28.422] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[[Internal Screaming]]'/minecraft:the_nether
[07Sep2023 22:20:28.426] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[[Internal Screaming]]'/minecraft:the_end
[07Sep2023 22:20:28.594] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage ([Internal Screaming]): All chunks are saved
[07Sep2023 22:20:28.594] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[07Sep2023 22:20:28.594] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[07Sep2023 22:20:28.594] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
This looks more like whatever projectile you used / picked up has a broken implementation

https://github.com/NikitaCartes-archive/MinecraftDeobfuscated-Mojang/blob/9e726ba943734d13e63828ab3d115371aed49427/minecraft/src/net/minecraft/world/entity/projectile/AbstractArrow.java#L500

iceandfire returns a proper itemstack for `getPickupItem` and there is nothing mentioned in the crash which is relevant to any iceandfire mobs

**Comment by Lampt3rn** [comment]
Thank you for the response, sorry about it not being ice and fire related (I had no idea) and posting it here.
