### ISSUE TITLE
[Bug]: java.lang.NullPointerException: Ticking entity crash?

### ISSUE THREAD

**Issue by BlackhawkGT** [Alex-the-666/Ice_and_Fire#4967]
### What happened?

It just happened randomly when exploring, after a restart it hasn't happened yet.

[crash-2023-10-07_07.30.37-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/12837844/crash-2023-10-07_07.30.37-server.txt)

### Minecraft Version

1.16(CRASHES ONLY)

### Ice and Fire version

2.1.12-1.16.5-patch-1

### Citadel version

1.8.1

### Relevant log output

```shell
Time: 10/7/23 7:30 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75499_g(AdvancedPathNavigate.java:891) ~[iceandfire:2.1.12-1.16.5-patch-1] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_233686_v_(EntityDragonBase.java:1052) ~[iceandfire:2.1.12-1.16.5-patch-1] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.IafDragonLogic.updateDragonServer(IafDragonLogic.java:131) ~[iceandfire:2.1.12-1.16.5-patch-1] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1744) ~[iceandfire:2.1.12-1.16.5-patch-1] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:mixin:APP:mixins.integrated_proxy.json:MixinWorldRedstone,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:memoryleakfix-16.mixins.json:drownedNavigationLeak.ServerLevel_navigationMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_361] {}
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I've seen this issue a couple of times before. In the code we already perform a null check before calling functions that could cause a null pointer exception so to this day I still don't know what could be causing this behavior besides some threaded weirdness...
