### ISSUE TITLE
[Bug]: Forge Server Crash STEP_HEIGHT

### ISSUE THREAD

**Issue by Apotrox** [Alex-the-666/Ice_and_Fire#4993]
### What happened?

Freshly set up forge server crashes almost immediately. So far, no issues in singleplayer.
Issue also persisted in Alpha 4

https://mclo.gs/oWDCKnI

### Minecraft Version

1.20.1

### Ice and Fire version

Alpha 5

### Citadel version

2.4.5

### Relevant log output

```shell
[21:27:44] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.ModLoadingException: Ice and Fire (iceandfire) encountered an error during the common_setup event phase
§7java.lang.NoSuchFieldError: STEP_HEIGHT
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.20.1-47.2.0.jar%23147!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at net.minecraftforge.common.ForgeHooks.modifyAttributes(ForgeHooks.java:1222) ~[forge-1.20.1-47.2.0-universal.jar%23150!/:?] {re:classloading}
        at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:363) ~[forge-1.20.1-47.2.0-universal.jar%23150!/:?] {re:classloading}
        at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.1-47.2.0-universal.jar%23150!/:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.0.jar%23146!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.2.0-universal.jar%23150!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23145!/:?] {re:classloading}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NoSuchFieldError: STEP_HEIGHT
        at com.github.alexthe666.iceandfire.entity.EntityCyclops.bakeAttributes(EntityCyclops.java:93) ~[iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-5.jar%23131!/:2.1.13-1.20.1+build.2.1.13-alpha-5] {re:classloading}
        at com.github.alexthe666.iceandfire.entity.IafEntityRegistry.bakeAttributes(IafEntityRegistry.java:105) ~[iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-5.jar%23131!/:2.1.13-1.20.1+build.2.1.13-alpha-5] {re:classloading}
        at com.github.alexthe666.iceandfire.entity.__IafEntityRegistry_bakeAttributes_EntityAttributeCreationEvent.invoke(.dynamic) ~[iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-5.jar%23131!/:2.1.13-1.20.1+build.2.1.13-alpha-5] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.2.0.jar%23147!/:?] {}
        ... 29 more
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Apotrox** [comment]
went ahead and skimmed through the src, found that with the recent commit, the line `.add(ForgeMod.STEP_HEIGHT.get(), 2.5F);` was added. Might be meant to say `.add(ForgeMod.STEP_HEIGHT_ADDITION.get(), 2.5F);`? Took the freedom to implement that change myself (In Amphithere, Cyclops, DeathWorm, Hippocampus and Siren) and it appears to be working.

**Comment by Apotrox** [comment]
I'll attach the jar in a zip here for anyone to use, i only tested it for like 2 mins though.
[iceandfire-2.1.13-1.20.1_fix_STEPHEIGHT.zip](https://github.com/AlexModGuy/Ice_and_Fire/files/13079434/iceandfire-2.1.13-1.20.1_fix_STEPHEIGHT.zip)

**Comment by Skycryck** [comment]
Thank you! I had the same issue, this seems to have fixed it.

**Comment by TheBv** [comment]
I got lucky and randomly chose to implement a feature that's only available on the newest neoforge version... 🙃 
I just checked and forge doesn't support it either so I'll have to revert the commit I guess...

**Comment by Sova626** [comment]
thanks mod worked but the world still crashes when loaded
[crash-2023-10-23_21.35.58-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13110148/crash-2023-10-23_21.35.58-server.txt)
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/13110183/latest.log)
