### ISSUE TITLE
[Bug]: Crashing when someone else flies a dragon

### ISSUE THREAD

**Issue by ericstran** [Alex-the-666/Ice_and_Fire#5004]
### What happened?

I expected to see the person I was playing with mount/ fly their newly tamed stage 3 ice dragon, but instead I crashed immediately.

This is the second time this has happened. The first time was with a different player in our world. It seems that any time a player looks at someone flying a dragon, the person who is not flying the dragon crashes.

EDIT: It seems that I don't crash unless I'm looking at the dragon while it's flying while someone is currently mounted on it (it's fine if the dragon is flying by itself).

EDIT: This still happens with stage 4 dragons

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

Cient Log (mine):
```shell
[15:15:57] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1419) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1225) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23479!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

Server Log right before I disconnected:
```shell
[server thread/ERROR] [Minecraft/Util]: Invalid entity rotation: NaN, disregarding.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by peetey897** [comment]
I'm trying to figure this out myself as it's really annoying me. Any chance you could upload your full crash log? I'd like to compare your modlist to mine and the other several people who have posted crashes from the same error.

**Comment by peetey897** [comment]
Just wanted to update and I've resolve the crashing issue on my own single player worlds by removing Alex's Delight. Another user in another bug report also mentioned Enlightened End. Do you have either of those mods present on your server?

**Comment by ericstran** [comment]
> Just wanted to update and I've resolve the crashing issue on my own single player worlds by removing Alex's Delight. Another user in another bug report also mentioned Enlightened End. Do you have either of those mods present on your server?

I don't think I have the crash log anymore?? idk what happened to it, it's on someone else's computer. 
I do have Alex's Delight though, but not Enlightened End. 
I'll check if it's fixed for me by removing Alex's Delight (that doesn't seem to make much sense to me though as to why that would cause the error...)

**Comment by ericstran** [comment]
IT WORKS!!! I removed Alex's Delight. It's a small price to pay to be able to look at dragons without fear of crashing.
I'll just make a datapack (kubejs <3) for some of the recipes (ignoring the new items) that Alex's Delight adds.

**Comment by peetey897** [comment]
Holy cow, that's awesome!!! I agree - it doesn't really make sense why that would be the mod. It was basically the last mod I re-enabled when I was binary searching because I was like - there's NO WAY this is the cause, but I know something in the last block I did was the thing that changed it and this is the only thing left.  The only thing I can think is that, since Alex's Mods, Ice and Fire, and Citadel (the library mod for both) are all by the same dev, something in Alex's Delight is touching something - maybe something in Citadel - that's screwing with Ice and Fire? I'm grasping at straws, though.
