### ISSUE TITLE
Worldgen compatability Terralith[Bug]: 

### ISSUE THREAD

**Issue by DragonPriv** [Alex-the-666/Ice_and_Fire#5026]
### What happened?

So basically, i just wanted to share that the terralith 2 update stops dragons and caves from spawning. Atleast in the new biomes. I tried to fix the issue by adding the biomes into the config files by hand, but no luck there. I'm not too sure if that comes from terralith in general or from me using terralith in combination with tectonic. However since there arent any new biomes added except for terralith ones, I belive its a problem with terralith itself.

Would love it if you can look into it ^^

Thank you for your great work!

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
[14Nov.2023 22:30:36.148] [modloading-worker-0/ERROR] [citadel/]: Spawn Biome Config: Could not load D:\Minecraft Modpacks\1.18.2 Magic & Technic\.minecraft\config\iceandfire\ice_lily_biomes.json
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.Arrays$ArrayList.<init>(Arrays.java:4137) ~[?:?]
	at java.util.Arrays.asList(Arrays.java:4122) ~[?:?]
	at com.github.alexthe666.iceandfire.config.biome.IafSpawnBiomeData.<init>(IafSpawnBiomeData.java:35) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.IafSpawnBiomeData$Deserializer.deserialize(IafSpawnBiomeData.java:93) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.IafSpawnBiomeData$Deserializer.deserialize(IafSpawnBiomeData.java:82) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2336!/:?]
	at com.github.alexthe666.iceandfire.config.biome.SpawnBiomeConfig.getOrCreateConfigFile(SpawnBiomeConfig.java:46) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.SpawnBiomeConfig.getConfigData(SpawnBiomeConfig.java:66) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.SpawnBiomeConfig.create(SpawnBiomeConfig.java:32) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.BiomeConfig.init(BiomeConfig.java:74) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.CommonProxy.onModConfigEvent(CommonProxy.java:34) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at net.minecraftforge.eventbus.ASMEventHandler_1068_CommonProxy_onModConfigEvent_Loading.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41) ~[javafmllanguage-1.18.2-40.2.10.jar%23196!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:34) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:186) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:121) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:121) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:103) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[14Nov.2023 22:30:36.219] [modloading-worker-0/ERROR] [citadel/]: Spawn Biome Config: Could not load D:\Minecraft Modpacks\1.18.2 Magic & Technic\.minecraft\config\iceandfire\ice_dragon_skeleton_biomes.json
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.Arrays$ArrayList.<init>(Arrays.java:4137) ~[?:?]
	at java.util.Arrays.asList(Arrays.java:4122) ~[?:?]
	at com.github.alexthe666.iceandfire.config.biome.IafSpawnBiomeData.<init>(IafSpawnBiomeData.java:35) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.IafSpawnBiomeData$Deserializer.deserialize(IafSpawnBiomeData.java:93) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.IafSpawnBiomeData$Deserializer.deserialize(IafSpawnBiomeData.java:82) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2336!/:?]
	at com.github.alexthe666.iceandfire.config.biome.SpawnBiomeConfig.getOrCreateConfigFile(SpawnBiomeConfig.java:46) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.SpawnBiomeConfig.getConfigData(SpawnBiomeConfig.java:66) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.biome.SpawnBiomeConfig.create(SpawnBiomeConfig.java:32) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.config.BiomeConfig.init(BiomeConfig.java:74) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at com.github.alexthe666.iceandfire.CommonProxy.onModConfigEvent(CommonProxy.java:34) ~[iceandfire-2.1.12-1.18.2.jar%23108!/:2.1.12-1.18.2]
	at net.minecraftforge.eventbus.ASMEventHandler_1068_CommonProxy_onModConfigEvent_Loading.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41) ~[javafmllanguage-1.18.2-40.2.10.jar%23196!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:34) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:186) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.10.jar%23195!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:121) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:121) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:103) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.2.10-universal.jar%23199!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
I think you messed up the config files along the way. 
I wrote this a while ago https://github.com/AlexModGuy/Ice_and_Fire/wiki/How-to-specify-the-regions-structures-and-mobs-can-be-spawned#verifying-your-updated-file
Especially the step linked makes sure that the formatting is correct and there's no missing commas etc.
