### ISSUE TITLE
[Bug]: Dying to Dread Beast crashes the server

### ISSUE THREAD

**Issue by Cohzey** [Alex-the-666/Ice_and_Fire#5043]
### What happened?

It says everything on the title!! Basically, the crash said it was a ticking entity error (as shown in crash logs)
But it doesn't crash when I spawn it or kill it, it just crashes when I die to it!

[I'll test if it's only for the Dread Beast or every Dread Mob]
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/149563213/e8d4319c-e296-4a0b-9f19-f978edf6fe41)
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/149563213/a465e318-17df-4adf-bf90-96f667d801e9)
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/149563213/693d1e7b-fe73-442b-9978-cc5c3ded9c93)

crash-log: https://mclo.gs/ULuou1p
logs: https://mclo.gs/uVIW5JK

and here's my modpack (if you want to reproduce!!)
https://drive.google.com/drive/folders/1mtzX9RELcXjWlIi58Qkyvt96DdCGDTMB

### Minecraft Version

1.18

### Ice and Fire version

2.1.12 1.18.2

### Citadel version

1.11.3

### Relevant log output

```shell
[19Dec2023 20:38:39.089] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Friday13th: The difficulty has been set to Hard]
[19Dec2023 20:38:50.765] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Friday13th: Set own game mode to Survival Mode]
[19Dec2023 20:38:56.100] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Friday13th was slain by Dread Beast
[19Dec2023 20:38:56.948] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20185_()" because the return value of "com.github.alexthe666.iceandfire.entity.EntityDreadBeast.m_5448_()" is null
	at com.github.alexthe666.iceandfire.entity.EntityDreadBeast.m_8107_(EntityDreadBeast.java:142) ~[iceandfire-2.1.12-1.18.2.jar%2390!/:2.1.12-1.18.2]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:310) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23131!/:?]
	... 5 more
[19Dec2023 20:38:56.978] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID a6d02d29-d776-4508-a203-8abb9b28636f
[19Dec2023 20:38:56.979] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /server/./crash-reports/crash-2023-12-19_20.38.56-server.txt
[19Dec2023 20:38:56.979] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[19Dec2023 20:38:56.981] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[19Dec2023 20:38:57.115] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: xxxBINLADENxxx lost connection: Server closed
[19Dec2023 20:38:57.116] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: xxxBINLADENxxx left the game
[19Dec2023 20:38:57.143] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Friday13th lost connection: Server closed
[19Dec2023 20:38:57.144] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Friday13th left the game
[19Dec2023 20:38:57.172] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[19Dec2023 20:39:04.984] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[DnD]'/minecraft:overworld
[19Dec2023 20:39:04.988] [Server thread/INFO] [antiqueatlas/]: Saving local markers data to NBT
[19Dec2023 20:39:07.298] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[DnD]'/nullscape:end_island
[19Dec2023 20:39:07.299] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[DnD]'/minecraft:the_end
[19Dec2023 20:39:07.301] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[DnD]'/minecraft:the_nether
[19Dec2023 20:39:07.301] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[DnD]'/twilightforest:twilight_forest
[19Dec2023 20:39:07.380] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[19Dec2023 20:39:07.380] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (end_island): All chunks are saved
[19Dec2023 20:39:07.380] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19Dec2023 20:39:07.380] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19Dec2023 20:39:07.380] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[19Dec2023 20:39:07.381] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[19Dec2023 20:39:07.919] [Server thread/INFO] [net.minecraft.server.rcon.thread.GenericThread/]: Thread Query Listener stopped
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Cohzey** [comment]
forgot to add this ( for proof it crashes!)
![image](https://github.com/AlexModGuy/Ice_and_Fire/assets/149563213/bddcd2a6-2db0-416e-b165-4ac0a46dc358)

**Comment by Cohzey** [comment]
After some investigation with my friends, we discovered that dying to;
[dread thrall : fine
dread ghoul: fine
dread scuttler: fine
beast : not fine (crash)]

 after that, we tested to see if the mod "Hardcore Revival" was the one responsible because it was the only mod that affects player deaths. **Removing the mod was the solution** and it had smth to with the lines here, in the log, that specified what really happened CUZ IDK WHAT ANY OF THIS MEANNSSSS TwT
 
 part of log: https://pastebin.com/AkbYCTvh

**Comment by TheBv** [comment]
I've looked into it and I could see how that mod causes the issue.
There's sadly not much I can do about it, I'll investigate it properly and then potentially open an issue on their github if I find out what exactly the issue is.
