### ISSUE TITLE
[Bug]: Failed to load with the origins mod (build 1.20.1.12.28) 

### ISSUE THREAD

**Issue by JuzeTv** [Alex-the-666/Ice_and_Fire#5056]
### What happened?

When you start minecraft, it closes immediately. In the alternative version of the mod build, the game closes when the world is created.
[crash-2023-12-29_17.50.38-server.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/13794428/crash-2023-12-29_17.50.38-server.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

12.28

### Citadel version

2.4.9

### Relevant log output

```shell
UltimMC version: 0.7.0-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.243.48, 13.33.243.49, 13.33.243.103, 13.33.243.122]

session.minecraft.net resolves to:
    [13.107.246.53, 13.107.213.53]

textures.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

api.mojang.com resolves to:
    [13.107.213.53, 13.107.246.53]


Minecraft folder is:
Z:/Desktop/UltimMC/instances/test/.minecraft


Java path is:
C:/Program Files/java 2/jdk-18.0.2.1/bin/javaw.exe


Checking Java version...
Java is version 18.0.2.1, using 64-bit architecture, from Oracle Corporation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  Z:/Desktop/UltimMC/instances/test/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  Z:/Desktop/UltimMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  Z:/Desktop/UltimMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  Z:/Desktop/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  Z:/Desktop/UltimMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  Z:/Desktop/UltimMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  Z:/Desktop/UltimMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  Z:/Desktop/UltimMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  Z:/Desktop/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  Z:/Desktop/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  Z:/Desktop/UltimMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  Z:/Desktop/UltimMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  Z:/Desktop/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  Z:/Desktop/UltimMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  Z:/Desktop/UltimMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  Z:/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  Z:/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  Z:/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  Z:/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  Z:/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  Z:/Desktop/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  Z:/Desktop/UltimMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  Z:/Desktop/UltimMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.6-prism/ForgeWrapper-1.5.6-prism.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/loader/47.1.47/loader-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/earlydisplay/47.1.47/earlydisplay-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar
  Z:/Desktop/UltimMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  Z:/Desktop/UltimMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  Z:/Desktop/UltimMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  Z:/Desktop/UltimMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  Z:/Desktop/UltimMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  Z:/Desktop/UltimMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  Z:/Desktop/UltimMC/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  Z:/Desktop/UltimMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  Z:/Desktop/UltimMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  Z:/Desktop/UltimMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  Z:/Desktop/UltimMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  Z:/Desktop/UltimMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  Z:/Desktop/UltimMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  Z:/Desktop/UltimMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  Z:/Desktop/UltimMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  Z:/Desktop/UltimMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  Z:/Desktop/UltimMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  Z:/Desktop/UltimMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/events/47.1.47/events-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/core/47.1.47/core-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/language-java/47.1.47/language-java-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/language-lowcode/47.1.47/language-lowcode-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/net/neoforged/fancymodloader/language-minecraft/47.1.47/language-minecraft-47.1.47.jar
  Z:/Desktop/UltimMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  Z:/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [❌] accelerated-decay-forge-3.0.1mc1.20.1.jar.disabled (disabled)
  [❌] Amplified_Nether_1.20.4_v1.2.4.jar.disabled (disabled)
  [❌] apotheosis-1.20.1-7.1.0.jar.disabled (disabled)
  [❌] apothicattributes-1.20.1-1.2.0.jar.disabled (disabled)
  [❌] appleskin-forge-mc1.20.1-2.5.1.jar.disabled (disabled)
  [❌] architectury-9.1.12-forge.jar.disabled (disabled)
  [❌] badpackets-forge-0.4.3.jar.disabled (disabled)
  [❌] balm-forge-1.20.1-7.1.4.jar.disabled (disabled)
  [❌] betterfpsdist-1.20.1-4.1.jar.disabled (disabled)
  [❌] beyond_mines_falling-1.0.0.jar.disabled (disabled)
  [❌] bloodmagic-1.20.1-3.3.2-44.jar.disabled (disabled)
  [❌] bookshelf-forge-1.20.1-20.1.8.jar.disabled (disabled)
  [✔️] caelus-forge-3.1.0+1.20.jar
  [❌] christmasfestivity-1.20.1-1.6.3-forge.jar.disabled (disabled)
  [✔️] citadel-2.4.9-1.20.1.jar
  [❌] clumps-forge-1.20.1-12.0.0.3.jar.disabled (disabled)
  [❌] collective-1.20.1-7.26.jar.disabled (disabled)
  [❌] cupboard-1.20.2-2.1.jar.disabled (disabled)
  [❌] curios-forge-5.4.6-1.20.1.jar.disabled (disabled)
  [❌] Cyclic-1.20.1-1.12.5.jar.disabled (disabled)
  [❌] darkmodeeverywhere-1.20.1-1.2.2.jar.disabled (disabled)
  [❌] deathquotes-forge-1.20.1-3.3.jar.disabled (disabled)
  [❌] does_potato_tick-1.20.1-3.7.0.jar.disabled (disabled)
  [❌] eidolon_repraised-1.20.1-0.3.7.5.jar.disabled (disabled)
  [❌] embersrekindled-1.20.1-1.0.3.jar.disabled (disabled)
  [❌] enchantmentdescriptions-forge-1.20.1-17.0.11.jar.disabled (disabled)
  [❌] enchantmentdescriptions-forge-1.20.2-18.0.5.jar.disabled (disabled)
  [❌] EnigmaticLegacy-2.29.0.jar.disabled (disabled)
  [❌] extractinator-forge-1.20.1-2.3.0.jar.disabled (disabled)
  [❌] EyesInTheDarkness-1.20.1-1.3.10.jar.disabled (disabled)
  [❌] farmersdelight-1.20.1-1.2.3.jar.disabled (disabled)
  [❌] fastload-reforged-8.2.11.20.1.jar.disabled (disabled)
  [❌] ferritecore-6.0.1-forge (1).jar.disabled (disabled)
  [❌] flib-1.20.1-0.0.11.jar.disabled (disabled)
  [❌] From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar.disabled (disabled)
  [❌] geckolib-neoforge-1.20.1-4.3.1.jar.disabled (disabled)
  [✔️] iceandfire-2.1.13-1.20.1-SNAPSHOT+build.12-28-all (2).jar
  [❌] iceandfire-2.1.13-1.20.1-SNAPSHOT+build.12-28-no-mixinextras.jar.disabled (disabled)
  [❌] irons_spellbooks-1.20.1-2.1.1.jar.disabled (disabled)
  [❌] jei-1.20.1-forge-15.2.0.27.jar.disabled (disabled)
  [❌] journeymap-1.20.1-5.9.18-forge.jar.disabled (disabled)
  [❌] Kiwi-1.20.1-forge-11.1.1.jar.disabled (disabled)
  [❌] manyideaschristmas-1.20.1-1.0.0.jar.disabled (disabled)
  [❌] manyideascore-1.20.1-1.4.2.jar.disabled (disabled)
  [❌] mcw-holidays-1.1.0-mc1.20.1forge.jar.disabled (disabled)
  [❌] mcwifipnp-1.6.6-1.20.1-forge.jar.disabled (disabled)
  [❌] medievalorigins-5.2.01.20.1-forge.jar.disabled (disabled)
  [❌] multistorage-forge-1.20.1-1.0.jar.disabled (disabled)
  [❌] nofog-1.3.4_1.20.1-forge.jar.disabled (disabled)
  [❌] notenoughanimations-forge-1.6.4-mc1.20.jar.disabled (disabled)
  [❌] notenoughcrashes-4.4.61.20.1-forge.jar.disabled (disabled)
  [✔️] origins-forge-1.20.1-1.10.0.0-all.jar
  [❌] paganbless-0.0.4-1.20.1.jar.disabled (disabled)
  [❌] Patchouli-1.20.1-84-FORGE.jar.disabled (disabled)
  [❌] pehkui-3.7.121.20.1-forge.jar.disabled (disabled)
  [❌] pipez-forge-1.20.1-1.2.6.jar.disabled (disabled)
  [❌] placebo-1.20.1-8.6.0.jar.disabled (disabled)
  [❌] plasmovoice-forge-1.20.1-2.0.7.jar.disabled (disabled)
  [❌] player-animation-lib-forge-1.0.2-rc11.20.jar.disabled (disabled)
  [❌] radium-mc1.20.1-0.12.2git.5f80f74.jar.disabled (disabled)
  [❌] resourcefulconfig-forge-1.20.1-2.1.0.jar.disabled (disabled)
  [❌] resourcefullib-forge-1.20.1-2.1.20.jar.disabled (disabled)
  [❌] saturn-mc1.20.1-0.0.8.jar.disabled (disabled)
  [❌] shetiphiancore-forge-1.20.1-1.2.jar.disabled (disabled)
  [❌] smoothboot-mc1.20.1-0.0.3.jar.disabled (disabled)
  [❌] SnowRealMagic-1.20.1-forge-10.0.0.jar.disabled (disabled)
  [❌] snowundertrees-1.20.1-1.4.3.jar.disabled (disabled)
  [❌] The_Graveyard_2.6.1_-FORGE-_for_1.20.1.jar.disabled (disabled)
  [❌] timeout_fixes-1.20.1-1.0.0.jar.disabled (disabled)
  [❌] ToolUpgrades-1.20.x-v.3.1.0.jar.disabled (disabled)
  [❌] torohealth-unofficial-forge-1.20.1-1.0.0.jar.disabled (disabled)
  [❌] trajectorypreview-6.0.2-1.20.1.jar.disabled (disabled)
  [❌] treeharvester-1.20.1-8.3.jar.disabled (disabled)
  [❌] vanilla-refresh-1.4.19a.jar.disabled (disabled)
  [❌] waystones-forge-1.20-14.0.2.jar.disabled (disabled)
  [❌] wthit-forge-8.4.3.jar.disabled (disabled)

Params:
  --username <КЛЮЧ ДОСТУПА> --version 1.20.1 --gameDir Z:/Desktop/UltimMC/instances/test/.minecraft --assetsDir Z:/Desktop/UltimMC/assets --assetIndex 5 --uuid <ID ПРОФИЛЯ> --accessToken <КЛЮЧ ДОСТУПА> --userType Local --versionType release --launchTarget forgeclient --fml.forgeVersion 47.1.70 --fml.fmlVersion 47.1.47 --fml.mcVersion 1.20.1 --fml.mcpVersion 20230612.114412

Window size: 854 x 480

Java Arguments:
[-javaagent:Z:/Desktop/UltimMC/injectors/authlib-injector-1.2.4.jar=http://localhost:50425, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms307m, -Xmx3712m, -Duser.language=en]


Minecraft process ID: 8428


[authlib-injector] [INFO] Logging file: Z:\Desktop\UltimMC\instances\test\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.4
[authlib-injector] [INFO] Authentication server: http://localhost:50425
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
[18:00:04.761] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <КЛЮЧ ДОСТУПА>, --version, 1.20.1, --gameDir, Z:/Desktop/UltimMC/instances/test/.minecraft, --assetsDir, Z:/Desktop/UltimMC/assets, --assetIndex, 5, --uuid, <ID ПРОФИЛЯ>, --accessToken, вќ„вќ„вќ„вќ„вќ„вќ„вќ„вќ„, --userType, Local, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.70, --fml.fmlVersion, 47.1.47, --fml.mcVersion, 1.20.1, --fml.mcpVersion, 20230612.114412, --width, 854, --height, 480] 
[18:00:04.766] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 18.0.2.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0 
[18:00:04.952] [main/INFO] [loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow 
[18:00:05.072] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 
[18:00:05.562] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6 
Failed to load forge logo
[18:00:05.678] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Z:/Desktop/UltimMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23124!/ Service=ModLauncher Env=CLIENT 
[18:00:05.768] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.33, NVIDIA Corporation 
[18:00:05.813] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "caelus-forge-3.1.0+1.20.jar" of type MOD with provider {mods folder locator at Z:\Desktop\UltimMC\instances\test\.minecraft\mods} 
[18:00:05.813] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "citadel-2.4.9-1.20.1.jar" of type MOD with provider {mods folder locator at Z:\Desktop\UltimMC\instances\test\.minecraft\mods} 
[18:00:05.813] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "iceandfire-2.1.13-1.20.1-SNAPSHOT+build.12-28-all (2).jar" of type MOD with provider {mods folder locator at Z:\Desktop\UltimMC\instances\test\.minecraft\mods} 
[18:00:05.814] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "origins-forge-1.20.1-1.10.0.0-all.jar" of type MOD with provider {mods folder locator at Z:\Desktop\UltimMC\instances\test\.minecraft\mods} 
[18:00:05.976] [main/WARN] [loading.moddiscovery.ModFileParser/LOADING]: Mod file Z:\Desktop\UltimMC\libraries\net\neoforged\fancymodloader\core\47.1.47\core-47.1.47.jar is missing mods.toml file 
[18:00:05.978] [main/WARN] [loading.moddiscovery.ModFileParser/LOADING]: Mod file Z:\Desktop\UltimMC\libraries\net\neoforged\fancymodloader\language-java\47.1.47\language-java-47.1.47.jar is missing mods.toml file 
[18:00:05.980] [main/WARN] [loading.moddiscovery.ModFileParser/LOADING]: Mod file Z:\Desktop\UltimMC\libraries\net\neoforged\fancymodloader\language-lowcode\47.1.47\language-lowcode-47.1.47.jar is missing mods.toml file 
[18:00:05.982] [main/WARN] [loading.moddiscovery.ModFileParser/LOADING]: Mod file Z:\Desktop\UltimMC\libraries\net\neoforged\fancymodloader\language-minecraft\47.1.47\language-minecraft-47.1.47.jar is missing mods.toml file 
[18:00:06.014] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "core-47.1.47.jar" of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b152928 
[18:00:06.014] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "language-java-47.1.47.jar" of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b152928 
[18:00:06.015] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "language-lowcode-47.1.47.jar" of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b152928 
[18:00:06.015] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "language-minecraft-47.1.47.jar" of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b152928 
[18:00:06.015] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "client-1.20.1-20230612.114412-srg.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b152928 
[18:00:06.015] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "forge-1.20.1-47.1.70-universal.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3b152928 
[18:00:06.020] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "events-47.1.47.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.BuiltinGameLibraryLocator@72458efc 
[18:00:06.193] [main/INFO] [loading.moddiscovery.JarInJarDependencyLocator/]: Found 6 dependencies adding them to mods collection 
[18:00:06.193] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "mixinextras-neoforge-0.3.2.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a5b8489 
[18:00:06.193] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "mixinextras-forge-0.2.0-beta.8.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a5b8489 
[18:00:06.193] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "calio-forge-1.20.1-1.11.0.0.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a5b8489 
[18:00:06.193] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "apoli-forge-1.20.1-2.9.0.0.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a5b8489 
[18:00:06.194] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "additionalentityattributes-forge-1.4.0.4+1.20.1.jar" of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a5b8489 
[18:00:06.194] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "MixinExtras-0.2.0-beta.8.jar" of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a5b8489 
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.module.ResolutionException: Module MixinExtras.beta._8 contains package com.llamalad7.mixinextras.utils, module mixinextras.neoforge exports package com.llamalad7.mixinextras.utils to MixinExtras.beta._8
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:807)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more
Exiting with -1
Процесс завершён с кодом -1 (0xffffffffffffffff).
Пожалуйста, обратите внимание, что обычно ни кода выхода, ни его описания недостаточно для диагностики проблем!
Всегда загружайте весь журнал целиком, а не только код выхода.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Should be fixed now with the latest snapshot 
https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.20-latest-snapshot
