### ISSUE TITLE
[Bug]: Crash when attempting to mount a dragon

### ISSUE THREAD

**Issue by dawntreader03** [Alex-the-666/Ice_and_Fire#5111]
### What happened?

Hello! Casual gamer here. Would just like to report a bug.

Attempting to ride/mount a dragon crashes the game and would not let me load the world unless the mod is disabled or removed.

Does not happen when I try to ride/mount:
-Horses
-Hippogryphs
-Hippocampi

Crash would happen with just dragons.

Thank you!

See attached crash report for reference.

[crash-2024-01-22_17.39.16-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/14009445/crash-2024-01-22_17.39.16-client.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

Ice and Fire-2.1.13-1.20.1-beta-2

### Citadel version

Citadel 2.4.9-1.20.1

### Relevant log output

```shell
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1431) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1229) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
See https://github.com/AlexModGuy/Ice_and_Fire/issues/5100

**Comment by dawntreader03** [comment]
But this means I have to remove MnA's addons for now. A bit sad. But I have also wanted to ride those dragons for a long time in my world.

Will try this workaround. Thank you for this!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
