### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by NotWim** [Alex-the-666/Ice_and_Fire#5153]
### What happened?

The game crashes immediatly

### Minecraft Version

1.19

### Ice and Fire version

2.1.13-beta2

### Citadel version

2.1.4

### Relevant log output

```shell
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-02-08 20:58:59
Description: Rendering overlay

java.lang.ExceptionInInitializerError: null
	at com.github.alexthe666.iceandfire.config.BiomeConfig.<clinit>(BiomeConfig.java:16) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading}
	at com.github.alexthe666.iceandfire.CommonProxy.onModConfigEvent(CommonProxy.java:33) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading}
	at com.github.alexthe666.iceandfire.__CommonProxy_onModConfigEvent_Loading.invoke(.dynamic) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42) ~[javafmllanguage-1.19.2-43.3.0.jar%23241!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$17(ModLoader.java:191) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:191) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:120) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:120) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:102) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at com.github.alexthe666.citadel.config.biome.SpawnBiomeData.addBiomeEntry(SpawnBiomeData.java:34) ~[citadel-2.1.4-1.19.jar%23203!/:2.1.4-1.19] {re:classloading}
	at com.github.alexthe666.iceandfire.config.DefaultBiomes.<clinit>(DefaultBiomes.java:28) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading}
	... 35 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexthe666.iceandfire.config.BiomeConfig.<clinit>(BiomeConfig.java:16) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading}
	at com.github.alexthe666.iceandfire.CommonProxy.onModConfigEvent(CommonProxy.java:33) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading}
	at com.github.alexthe666.iceandfire.__CommonProxy_onModConfigEvent_Loading.invoke(.dynamic) ~[iceandfire-1.19.2-2.1.13-beta-2.jar%23215!/:1.19.2-2.1.13+build.beta-2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42) ~[javafmllanguage-1.19.2-43.3.0.jar%23241!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:150) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:150) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23240!/:?] {}
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.19.2-43.3.0-universal.jar%23244!/:?] {re:classloading}
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
use the latest version (*beta-3 atm)
