### ISSUE TITLE
[Bug]: when me and my friend go to dessert to death worms it crashes our aternos server.

### ISSUE THREAD

**Issue by Christiniie** [Alex-the-666/Ice_and_Fire#5154]
### What happened?

when me and my friend go to dessert to death worms it crashes our aternos server.  It started happening today, everytime we go to dessert where is death worm near. It crashes our server.

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.12-1.20.1-beta-2

### Citadel version

2.4.3-1.20.1

### Relevant log output

```shell
[08Feb2024 22:16:59.950] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
[08Feb2024 22:16:59.955] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10 by Eclipse Adoptium; OS Linux arch amd64 version 5.15.0-91-generic
[08Feb2024 22:17:00.601] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[08Feb2024 22:17:00.764] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[08Feb2024 22:17:01.359] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/fmlcore/1.20.1-47.2.0/fmlcore-1.20.1-47.2.0.jar is missing mods.toml file
[08Feb2024 22:17:01.361] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.2.0/javafmllanguage-1.20.1-47.2.0.jar is missing mods.toml file
[08Feb2024 22:17:01.363] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.2.0/lowcodelanguage-1.20.1-47.2.0.jar is missing mods.toml file
[08Feb2024 22:17:01.365] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/mclanguage/1.20.1-47.2.0/mclanguage-1.20.1-47.2.0.jar is missing mods.toml file
[08Feb2024 22:17:01.571] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[08Feb2024 22:17:07.146] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[08Feb2024 22:17:07.187] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[08Feb2024 22:17:07.369] [main/WARN] [mixin/]: Reference map 'cristellib-forge-refmap.json' for cristellib.mixins.json could not be read. If this is a development environment you can ignore this message
[08Feb2024 22:17:22.459] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 47.2.0, for MC 1.20.1 with MCP 20230612.114412
[08Feb2024 22:17:22.459] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v47.2.0 Initialized
[08Feb2024 22:17:26.483] [modloading-worker-0/INFO] [terrablender/]: Registered region minecraft:overworld to index 0 for type OVERWORLD
[08Feb2024 22:17:26.483] [modloading-worker-0/INFO] [terrablender/]: Registered region minecraft:nether to index 0 for type NETHER
[08Feb2024 22:17:26.484] [modloading-worker-0/INFO] [terrablender/]: Registered region regions_unexplored:primary to index 1 for type OVERWORLD
[08Feb2024 22:17:26.484] [modloading-worker-0/INFO] [terrablender/]: Registered region regions_unexplored:secondary to index 2 for type OVERWORLD
[08Feb2024 22:17:26.484] [modloading-worker-0/INFO] [terrablender/]: Registered region regions_unexplored:nether to index 1 for type NETHER
[08Feb2024 22:17:26.762] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[08Feb2024 22:17:27.554] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 47.2.0 Target: null
[08Feb2024 22:17:27.556] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [gravestone] Starting version check at https://maxhenkel.de/update/gravestone.json
[08Feb2024 22:17:27.877] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [gravestone] Found status: UP_TO_DATE Current: 1.20.1-1.0.10 Target: null
[08Feb2024 22:17:28.388] [modloading-worker-0/INFO] [com.sk89q.worldedit.extension.platform.PlatformManager/]: Got request to register class com.sk89q.worldedit.forge.ForgePlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@c350a0a]
[08Feb2024 22:17:28.398] [modloading-worker-0/INFO] [com.sk89q.worldedit.forge.ForgeWorldEdit/]: WorldEdit for Forge (version 7.2.15+6463-5ca4dff) is loaded
[08Feb2024 22:17:28.441] [modloading-worker-0/INFO] [xaero.common.MinimapLogs/]: Loading Xaero's Minimap - Stage 1/2 (Server)
[08Feb2024 22:17:28.445] [modloading-worker-0/INFO] [xaero.map.server.WorldMapServer/]: Loading Xaero's World Map - Stage 1/2 (Server)
[08Feb2024 22:17:28.448] [main/INFO] [xaero.common.MinimapLogs/]: Loading Xaero's Minimap - Stage 2/2 (Server)
[08Feb2024 22:17:28.448] [main/INFO] [xaero.map.server.WorldMapServer/]: Loading Xaero's World Map - Stage 2/2 (Server)
[08Feb2024 22:17:33.535] [main/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08Feb2024 22:17:36.130] [main/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/server/libraries/net/minecraft/server/1.20.1-20230612.114412/server-1.20.1-20230612.114412-srg.jar%23137!/assets/.mcassetsroot' uses unexpected schema
[08Feb2024 22:17:36.134] [main/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/server/libraries/net/minecraft/server/1.20.1-20230612.114412/server-1.20.1-20230612.114412-srg.jar%23137!/data/.mcassetsroot' uses unexpected schema
[08Feb2024 22:17:36.252] [main/ERROR] [Cristel Lib/]: Cristel Lib Config Pack has no data
[08Feb2024 22:17:36.254] [main/WARN] [Cristel Lib/]: T&T Waystone Patch Pack accepted!
[08Feb2024 22:17:39.842] [main/INFO] [com.sk89q.worldedit.extension.platform.PlatformCommandManager/]: Registering commands with com.sk89q.worldedit.forge.ForgePlatform
[08Feb2024 22:17:43.006] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 11 recipes
[08Feb2024 22:17:43.458] [main/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 2560 advancements
[08Feb2024 22:17:43.478] [main/INFO] [top.theillusivec4.curios.Curios/]: Loaded 10 curio slots
[08Feb2024 22:17:43.481] [main/INFO] [top.theillusivec4.curios.Curios/]: Loaded 1 curio entities
[08Feb2024 22:17:44.952] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting minecraft server version 1.20.1
[08Feb2024 22:17:44.952] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Loading properties
[08Feb2024 22:17:44.952] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Default game type: SURVIVAL
[08Feb2024 22:17:44.952] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[08Feb2024 22:17:45.120] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting Minecraft server on *:50997
[08Feb2024 22:17:45.145] [Server thread/INFO] [net.minecraft.server.network.ServerConnectionListener/]: Using epoll channel type
[08Feb2024 22:17:45.259] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[08Feb2024 22:17:45.260] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: The server will make no attempt to authenticate usernames. Beware.
[08Feb2024 22:17:45.260] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[08Feb2024 22:17:45.260] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: To change this, set "online-mode" to "true" in the server.properties file.
[08Feb2024 22:17:45.451] [Server thread/INFO] [terrablender/]: Initialized TerraBlender biomes for level stem minecraft:the_nether
[08Feb2024 22:17:46.269] [Server thread/INFO] [terrablender/]: Initialized TerraBlender biomes for level stem minecraft:overworld
[08Feb2024 22:17:46.272] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Preparing level "world"
[08Feb2024 22:17:55.966] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[08Feb2024 22:18:06.407] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.433] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.440] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.458] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.461] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.462] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.462] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.463] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.483] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.485] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.486] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.494] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.503] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.507] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.509] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.513] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.515] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.515] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.516] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.516] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.517] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.518] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:06.967] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:07.468] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:08.028] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:08.467] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[08Feb2024 22:18:09.522] [Server thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 13555 ms
[08Feb2024 22:18:09.526] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Done (24.247s)! For help, type "help"
[08Feb2024 22:18:09.526] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting GS4 status listener
[08Feb2024 22:18:09.532] [Server thread/INFO] [net.minecraft.server.rcon.thread.GenericThread/]: Thread Query Listener started
[08Feb2024 22:18:09.532] [Query Listener #1/INFO] [net.minecraft.server.rcon.thread.QueryThreadGs4/]: Query running on 0.0.0.0:9898
[08Feb2024 22:18:09.563] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: JMX monitoring enabled
[08Feb2024 22:18:09.612] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[08Feb2024 22:18:13.378] [Server thread/INFO] [com.github.alexthe666.iceandfire.IceAndFire/]: {iceandfire:fire_dragon_roost=true, iceandfire:fire_lily=true, iceandfire:spawn_dragon_skeleton_fire=true, iceandfire:lightning_dragon_roost=true, iceandfire:spawn_dragon_skeleton_lightning=true, iceandfire:ice_dragon_roost=true, iceandfire:ice_dragon_cave=true, iceandfire:lightning_dragon_cave=true, iceandfire:cyclops_cave=true, iceandfire:spawn_wandering_cyclops=true, iceandfire:spawn_sea_serpent=true, iceandfire:frost_lily=true, iceandfire:hydra_cave=true, iceandfire:lightning_lily=true, iceandfire:pixie_village=true, iceandfire:myrmex_hive_jungle=true, iceandfire:myrmex_hive_desert=true, iceandfire:silver_ore=true, iceandfire:siren_island=true, iceandfire:spawn_dragon_skeleton_ice=true, iceandfire:spawn_stymphalian_bird=true, iceandfire:fire_dragon_cave=true, iceandfire:sapphire_ore=true, iceandfire:spawn_hippocampus=true, iceandfire:spawn_death_worm=true}
[08Feb2024 22:18:13.392] [Server thread/INFO] [com.github.alexthe666.iceandfire.IceAndFire/]: {TROLL_S=true, HIPPOGRYPH=true, AMPHITHERE=true, COCKATRICE=true, TROLL_M=true, DREAD_LICH=true, TROLL_F=true}
[08Feb2024 22:18:24.788] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: Christinie[/193.165.96.180:56173] logged in with entity id 191 at (680.0, 76.0, 168.0)
[08Feb2024 22:18:24.993] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Christinie joined the game
[08Feb2024 22:18:27.621] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 3026ms or 60 ticks behind
[08Feb2024 22:19:15.163] [Server thread/INFO] [net.minecraft.server.commands.LocateCommand/]: Locating element minecraft:desert_pyramid took 12338 ms
[08Feb2024 22:19:15.163] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 12318ms or 246 ticks behind
[08Feb2024 22:19:15.198] [Server thread/WARN] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Christinie moved too quickly! 0.0,10.312500617038765,0.0
[08Feb2024 22:19:15.435] [Server thread/INFO] [net.minecraft.server.commands.LocateCommand/]: Locating element minecraft:desert_pyramid took 235 ms
[08Feb2024 22:19:43.603] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: [Christinie: Teleported Christinie to -3343.500000, 81.068162, -5375.500000]
[08Feb2024 22:19:43.604] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 11408ms or 228 ticks behind
[08Feb2024 22:19:53.173] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalAccessError: class com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions tried to access private field net.minecraft.world.entity.Entity.f_19793_ (com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions is in module citadel@2.4.1 of loader 'TRANSFORMER' @426c0486; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @426c0486)
	at com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions.getAllowedMovementForEntity(ICustomCollisions.java:30) ~[citadel-2.4.1-1.20.jar%23119!/:2.4.1-1.20]
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.m_20272_(EntityDeathWorm.java:471) ~[iceandfire-2.1.13-1.20.1-beta-2.jar%23125!/:2.1.13-1.20.1+build.beta-2]
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:632) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.m_6478_(EntityDeathWorm.java:466) ~[iceandfire-2.1.13-1.20.1-beta-2.jar%23125!/:2.1.13-1.20.1+build.beta-2]
	at net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2195) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2132) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2605) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:128) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.m_8107_(EntityDeathWorm.java:555) ~[iceandfire-2.1.13-1.20.1-beta-2.jar%23125!/:2.1.13-1.20.1+build.beta-2]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.m_8119_(EntityDeathWorm.java:678) ~[iceandfire-2.1.13-1.20.1-beta-2.jar%23125!/:2.1.13-1.20.1+build.beta-2]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23137!/:?]
	... 5 more
[08Feb2024 22:19:53.183] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID b03fae74-9148-4a61-a065-9fa86fa4fd70
[08Feb2024 22:19:53.184] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /server/./crash-reports/crash-2024-02-08_22.19.53-server.txt
[08Feb2024 22:19:53.184] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[08Feb2024 22:19:53.185] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[08Feb2024 22:19:53.301] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Christinie lost connection: Server closed
[08Feb2024 22:19:53.302] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Christinie left the game
[08Feb2024 22:19:53.355] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[08Feb2024 22:19:56.952] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[08Feb2024 22:19:57.427] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[08Feb2024 22:19:57.428] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[08Feb2024 22:19:57.480] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[08Feb2024 22:19:57.480] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08Feb2024 22:19:57.480] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[08Feb2024 22:19:57.481] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[08Feb2024 22:19:58.282] [Server thread/INFO] [net.minecraft.server.rcon.thread.GenericThread/]: Thread Query Listener stopped
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Skyliuslinkius** [comment]
no solution?

**Comment by AlexaKood** [comment]
update your citadel to latest version
