### ISSUE TITLE
[Bug]: Ice and Fire beta-3 works on client but not on server.

### ISSUE THREAD

**Issue by ali-afk** [Alex-the-666/Ice_and_Fire#5181]
### What happened?

Server works perfectly fine, but after updating all three of Citadel, Alex's Caves, and Ice and Fire, it suddenly stopped working.

Would like to add that it is working on my client but not on the server, which has the same modlist (other than serverside mods) and was joinable a just before I updated.

Note that Alex's Caves is 1.1.0

### Minecraft Version

1.20.1

### Ice and Fire version

2.1.13-1.20.1-beta-3

### Citadel version

2.5.3-1.20.1

### Relevant log output

```shell
[20.02 04:43:52] [Server] ---- Minecraft Crash Report ----
[20.02 04:43:52] [Server] // Why is it breaking :(
[20.02 04:43:52] [Server] Time2024-02-20 02:43:52
[20.02 04:43:52] [Server] DescriptionMod loading error has occurred
[20.02 04:43:52] [Server] java.lang.ExceptionMod Loading has failed
[20.02 04:43:52] [Server] 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.20-universal.jar%23382!/:?] {re:classloading}
[20.02 04:43:52] [Server] 	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.2.20-universal.jar%23382!/:?] {re:classloading}
[20.02 04:43:52] [Server] 	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23377!/:?] {re:mixin,re:classloading,pl:mixin:A}
[20.02 04:43:52] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
[20.02 04:43:52] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
[20.02 04:43:52] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
[20.02 04:43:52] [Server] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
[20.02 04:43:52] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[20.02 04:43:52] [Server] ---------------------------------------------------------------------------------------
[20.02 04:43:52] [Server] -- Head --
[20.02 04:43:52] [Server] Threadmain
[20.02 04:43:52] [Server] Suspected ModsNONE
[20.02 04:43:52] [Server] Stacktrace:
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.{}
[20.02 04:43:52] [Server] -- MOD iceandfire --
[20.02 04:43:52] [Server] Details:
[20.02 04:43:52] [Server] 	Mod File/mods/iceandfire-2.1.13-1.20.1-beta-3.jar
[20.02 04:43:52] [Server] 	Failure messageIce and Fire (iceandfire) has failed to load correctly
[20.02 04:43:52] [Server] 		java.lang.RuntimeExceptionAttempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[20.02 04:43:52] [Server] 	Mod Version2.1.13-1.20.1-beta-3
[20.02 04:43:52] [Server] 	Mod Issue URLhttps://github.com/Alex-the-666/ice-and-fire/issues
[20.02 04:43:52] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[20.02 04:43:52] [Server] Stacktrace:
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.{}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[20.02 04:43:52] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
[20.02 04:43:52] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[20.02 04:43:52] [Server] 	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
[20.02 04:43:52] [Server] 	at java.lang.Class.forName(Class.java:467) ~[?:?] {re:mixin}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.20.1-47.2.20.jar%23379!/:?] {}
[20.02 04:43:52] [Server] 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.20.1-47.2.20.jar%23379!/:?] {}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:85) ~[javafmllanguage-1.20.1-47.2.20.jar%23379!/:?] {}
[20.02 04:43:52] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.20.jar%23378!/:?] {}
[20.02 04:43:52] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[20.02 04:43:52] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[20.02 04:43:52] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[20.02 04:43:52] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[20.02 04:43:52] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[20.02 04:43:52] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[20.02 04:43:52] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[20.02 04:43:52] [Server] -- System Details --
[20.02 04:43:52] [Server] Details:
[20.02 04:43:52] [Server] 	Minecraft Version1.20.1
[20.02 04:43:52] [Server] 	Minecraft Version ID1.20.1
[20.02 04:43:52] [Server] 	Operating SystemLinux (amd64) version 5.15.0-67-generic
[20.02 04:43:52] [Server] 	Java Version17.0.8, Oracle Corporation
[20.02 04:43:52] [Server] 	Java VM VersionJava HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
[20.02 04:43:52] [Server] 	Memory455921984 bytes (434 MiB) / 1174405120 bytes (1120 MiB) up to 10737418240 bytes (10240 MiB)
[20.02 04:43:52] [Server] 	CPUs16
[20.02 04:43:52] [Server] 	Processor VendorGenuineIntel
[20.02 04:43:52] [Server] 	Processor NameIntel(R) Xeon(R) E-2288G CPU @ 3.70GHz
[20.02 04:43:52] [Server] 	IdentifierIntel64 Family 6 Model 158 Stepping 13
[20.02 04:43:52] [Server] 	MicroarchitectureCoffee Lake
[20.02 04:43:52] [Server] 	Frequency (GHz)3.70
[20.02 04:43:52] [Server] 	Number of physical packages1
[20.02 04:43:52] [Server] 	Number of physical CPUs8
[20.02 04:43:52] [Server] 	Number of logical CPUs16
[20.02 04:43:52] [Server] 	Graphics card #name: unknown
[20.02 04:43:52] [Server] 	Graphics card #vendor: unknown
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Fixed in beta 4
