### ISSUE TITLE
[Bug]: Client Crashes when using endless Quiver on Dragon bone bow (Server)

### ISSUE THREAD

**Issue by CLittleLunaC** [Alex-the-666/Ice_and_Fire#5200]
### What happened?

Client crashes when Firing an Arrow from a Dragon bone bow with Apotheosis Endless quiver enchantment, Server remains up Client Crashes.
[crash-2024-02-26_17.23.48-client.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/14412801/crash-2024-02-26_17.23.48-client.txt)

### Minecraft Version

1.20.1

### Ice and Fire version

Beta 4

### Citadel version

2.5.3

### Relevant log output

```shell
[17:23:48] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:168) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin,pl:mixin:APP:apoli.mixins.json:EntityRenderDispatcherMixin,pl:mixin:APP:embeddium.mixins.json:features.render.entity.shadows.EntityRenderDispatcherMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.EntityRenderDispatcherMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.EntityRenderDispatcherMixin,pl:mixin:APP:embeddiumplus.mixin.json:entitydistance.EntityDispatcherMixin,pl:mixin:APP:firstperson.mixins.json:RenderDispatcherMixin,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.EntityRenderDispatcherAccessor,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinEntityRenderDispatcher,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntityRenderDispatcher,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1440) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1223) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
Caused by: java.lang.ClassCastException: class com.github.alexthe666.iceandfire.entity.EntityDragonArrow cannot be cast to class tech.thatgravyboat.vanity.common.util.EntityItemHolder (com.github.alexthe666.iceandfire.entity.EntityDragonArrow is in module iceandfire@2.1.13-1.20.1-beta-4 of loader 'TRANSFORMER' @4f9213d2; tech.thatgravyboat.vanity.common.util.EntityItemHolder is in module vanity@2.0.1 of loader 'TRANSFORMER' @4f9213d2)
	at net.minecraft.client.renderer.entity.ArrowRenderer.handler$bbm000$vanity$renderArrow(ArrowRenderer.java:541) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,re:classloading,pl:mixin:APP:vanity-common.mixins.json:client.fixes.ArrowRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ArrowRenderer.m_7392_(ArrowRenderer.java) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,re:classloading,pl:mixin:APP:vanity-common.mixins.json:client.fixes.ArrowRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ArrowRenderer.m_7392_(ArrowRenderer.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,re:classloading,pl:mixin:APP:vanity-common.mixins.json:client.fixes.ArrowRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin,pl:mixin:APP:apoli.mixins.json:EntityRenderDispatcherMixin,pl:mixin:APP:embeddium.mixins.json:features.render.entity.shadows.EntityRenderDispatcherMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.EntityRenderDispatcherMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.EntityRenderDispatcherMixin,pl:mixin:APP:embeddiumplus.mixin.json:entitydistance.EntityDispatcherMixin,pl:mixin:APP:firstperson.mixins.json:RenderDispatcherMixin,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.EntityRenderDispatcherAccessor,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinEntityRenderDispatcher,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntityRenderDispatcher,pl:mixin:A,pl:runtimedistcleaner:A}
	... 30 more
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
```
java.lang.ClassCastException: class com.github.alexthe666.iceandfire.entity.EntityDragonArrow cannot be cast to class tech.thatgravyboat.vanity.common.util.EntityItemHolder (com.github.alexthe666.iceandfire.entity.EntityDragonArrow is in module iceandfire@2.1.13-1.20.1-beta-4 of loader 'TRANSFORMER' @4f9213d2; tech.thatgravyboat.vanity.common.util.EntityItemHolder is in module vanity@2.0.1 of loader 'TRANSFORMER' @4f9213d2)
```

issue is caused by that vanity mod

**Comment by CLittleLunaC** [comment]
Alright, I read through the logs I guess I missed it mentioning Vanity.
