### ISSUE TITLE
[Bug]: Crash due to Chicken Ticking Entity 

### ISSUE THREAD

**Issue by ffuentesm** [Alex-the-666/Ice_and_Fire#5291]
### What happened?

The game crashed due to a ticking chicken when I was wandering 

### Minecraft Version

1.19

### Ice and Fire version

iceandfire-1.19.2-2.1.13-beta-3

### Citadel version

citadel-2.1.4-1.19

### Relevant log output
Full log: https://pastebin.com/50kJJZEP
```shell
Time: 2024-06-01 10:39:30
Description: Ticking entity
 
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.github.alexthe666.iceandfire.entity.props.ChainProperties.getOrCreateChainData(ChainProperties.java:72) ~[iceandfire-1.19.2-2.1.13-beta-3.jar%23379!/:1.19.2-2.1.13+build.beta-3] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.props.ChainProperties.getOrCreateChainData(ChainProperties.java:67) ~[iceandfire-1.19.2-2.1.13-beta-3.jar%23379!/:1.19.2-2.1.13+build.beta-3] {re:classloading}
	at com.github.alexthe666.iceandfire.entity.props.ChainProperties.hasChainData(ChainProperties.java:59) ~[iceandfire-1.19.2-2.1.13-beta-3.jar%23379!/:1.19.2-2.1.13+build.beta-3] {re:classloading}
	at com.github.alexthe666.iceandfire.event.ServerEvents.onEntityUpdate(ServerEvents.java:460) ~[iceandfire-1.19.2-2.1.13-beta-3.jar%23379!/:1.19.2-2.1.13+build.beta-3] {re:classloading}
	at com.github.alexthe666.iceandfire.event.__ServerEvents_onEntityUpdate_LivingTickEvent.invoke(.dynamic) ~[iceandfire-1.19.2-2.1.13-beta-3.jar%23379!/:1.19.2-2.1.13+build.beta-3] {re:classloading,pl:eventbus:B}
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by Drezkil** [comment]
try neruina mod
