### ISSUE TITLE
[Bug]: Dragons are there and active, yet invisible.

### ISSUE THREAD

**Issue by Belmingus** [Alex-the-666/Ice_and_Fire#5315]
### What happened?

[2024-07-01-1.log.gz](https://github.com/user-attachments/files/16057189/2024-07-01-1.log.gz)

I posted a part of the log which I suspect could help you, down in the log output and the rar above. please let me know if you need anything more from me. I'd appreciate any help greatly :) .

in the log I encountered the dragon at like 14:45 until 15:17 ish
so basically all mobs from the mod appear and act fine except for dragons. the dragons attack, have their lair and different attacks and have sounds but are entirely invisible which is very sad. this applies to other friends on my server aswell. we are using a modpack but can't seem to figure out which mod causes the issue or if its the ice and fire mod( which I dont assume).
we use the mod entity culling but since the other mobs from ice and fire appear I doubt its the cause of the issue.

### Minecraft Version

1.20.1

### Ice and Fire version

iceandfire-2.1.13-1.20.1-beta-4

### Citadel version

citadel-2.5.4-1.20.1

### Relevant log output

```shell
[14:46:29] [Render thread/ERROR]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: jeresources.jei.mob.MobWrapper@6ddec6f9

java.lang.NullPointerException: Cannot load from object array because "this.growth_stages" is null
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.getRenderSize(EntityDragonBase.java:1811) ~[iceandfire-2.1.13-1.20.1-beta-4.jar%23396!/:2.1.13-1.20.1-beta-4]
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.m_6134_(EntityDragonBase.java:1802) ~[iceandfire-2.1.13-1.20.1-beta-4.jar%23396!/:2.1.13-1.20.1-beta-4]
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.m_6972_(EntityDragonBase.java:1797) ~[iceandfire-2.1.13-1.20.1-beta-4.jar%23396!/:2.1.13-1.20.1-beta-4]
	at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3496) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.Entity.<init>(Entity.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:233) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.Mob.<init>(Mob.java:123) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.AgeableMob.<init>(AgeableMob.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.animal.Animal.<init>(Animal.java:40) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.world.entity.TamableAnimal.<init>(TamableAnimal.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.<init>(EntityDragonBase.java:238) ~[iceandfire-2.1.13-1.20.1-beta-4.jar%23396!/:2.1.13-1.20.1-beta-4]
	at com.github.alexthe666.iceandfire.entity.EntityIceDragon.<init>(EntityIceDragon.java:53) ~[iceandfire-2.1.13-1.20.1-beta-4.jar%23396!/:2.1.13-1.20.1-beta-4]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at jeresources.util.MobTableBuilder.lambda$add$0(MobTableBuilder.java:37) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at jeresources.entry.MobEntry.getEntity(MobEntry.java:94) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at jeresources.jei.mob.MobWrapper.getSpawnEgg(MobWrapper.java:160) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at jeresources.jei.mob.MobWrapper.hasSpawnEgg(MobWrapper.java:156) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at jeresources.jei.mob.MobCategory.setRecipe(MobCategory.java:63) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at jeresources.jei.mob.MobCategory.setRecipe(MobCategory.java:19) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:120) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:126) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:108) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at jeresources.jei.JEIConfig.registerRecipes(JEIConfig.java:75) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23404!/:1.4.0.247]
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:146) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:146) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.3.0.4.jar%23401!/:15.3.0.4]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.30.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.30.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by joaan14** [comment]
Hi, did you solve the problem? I have the same issue...

Thanks!
