### ISSUE TITLE
[Bug]: Game freezes near dragons.

### ISSUE THREAD

**Issue by matdex1** [Alex-the-666/Ice_and_Fire#5380]
### What happened?

Game freezes when coming close to naturally spawned in dragons and also dragons spawned in via spawn eggs. Config file has been edited to reduce spawns, smarter ai for dragons is false. In the log after [CHAT] <ProvoSantaClaus> f , the dragon was spawned and the freeze occured.

### Minecraft Version

1.18

### Ice and Fire version

2.1.12

### Citadel version

1.11.3

### Relevant log output

```shell
[22:54:35] [Render thread/WARN]: Time from main menu to in-game was 108.51984 seconds
[22:54:35] [Render thread/WARN]: Total time to load game and open world was 172.29083 seconds
[22:54:56] [Render thread/INFO]: Loaded 75 advancements
[22:54:58] [Server thread/INFO]: <ProvoSantaClaus> f
[22:54:58] [Render thread/INFO]: [CHAT] <ProvoSantaClaus> f
[22:55:07] [Render thread/WARN]: Tool stack constructed using non-modifiable tool, this may cause issues as it has no NBT. To debug this issue or disable the warning, use logInvalidToolStack in the config.
[22:55:07] [Render thread/WARN]: Tool stack constructed using non-modifiable tool, this may cause issues as it has no NBT. To debug this issue or disable the warning, use logInvalidToolStack in the config.
[22:55:40] [ModernFix integrated server watchdog/ERROR]: A single server tick has taken 40001, more than 40000 milliseconds
[22:55:41] [ModernFix integrated server watchdog/ERROR]: Thread Dump:
"Render thread" prio=10 Id=1 RUNNABLE
	at MC-BOOTSTRAP/org.lwjgl.opengl/org.lwjgl.opengl.GL30C.glBindFramebuffer(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.opengl/org.lwjgl.opengl.GL30.glBindFramebuffer(GL30.java:1642)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.platform.GlStateManager.m_84486_(GlStateManager.java:361)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.pipeline.RenderTarget.m_83970_(RenderTarget.java:214)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1060)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.21/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.21/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$865/0x00000008004a6598.call(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at app/cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by matdex1** [comment]
I can add more of the log if needed but couldnt fit much

**Comment by matdex1** [comment]
appears to be an incompatibility with 'Dimensional Threading Reforked'
