### ISSUE TITLE
Endless loop in WorldGenSirenIsland

### ISSUE THREAD

**Issue by davenonymous** [Alex-the-666/Ice_and_Fire#656]
This world gen does not seem to work well in void worlds?
You've got a [loop](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/structures/WorldGenSirenIsland.java#L23) that might never end.

This is causing problems with e.g. the Compact Machine mod, see https://github.com/thraaawn/CompactMachines/issues/316

You can reproduce this as described in the above ticket:
1. Set up a minecraft instance with both our mods
2. Place a few compact machines and enter them by right-clicking a PSD on them one after the other.
3. At some point during this (happened for the first or second machine) the WorldGenSirenIsland generator kicks in and gets stuck in the loop.

Stack trace created using jstack:
```
"Server thread" #86 prio=5 os_prio=0 tid=0x0000000068357800 nid=0x1d20 runnable [0x000000008f1ae000]
   java.lang.Thread.State: RUNNABLE
        at net.minecraft.world.World.func_180501_a(World.java:319)
        at com.github.alexthe666.iceandfire.structures.WorldGenSirenIsland.func_180709_b(WorldGenSirenIsland.java:28)
        at com.github.alexthe666.iceandfire.event.StructureGenerator.generate(StructureGenerator.java:72)
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by AlexModGuy** [comment]
oops

well, i know how to fix it so that's good.

**Comment by codewarrior0** [comment]
Confirmed with worldgen occuring in Compact Machines dimension. 

There seems to be no limit to the number of attempts to spawn a Siren.

**Comment by CplPibald** [comment]
Do you have an ETA on when a build with this fix will be released to curseforge?
