### ISSUE TITLE
Crash when zombies kill/convert villagers

### ISSUE THREAD

**Issue by ChrisOfNormandy** [Alex-the-666/Ice_and_Fire#721]
Tested with and without MCA; when a zombie kills a villager or converts them to a zombie villager, the game crashes with the reason "Attempted to set villager profession to unregistered profession." 

Crash log dump:

Description: Ticking entity

java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: 16 null
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:346)
	at net.minecraft.entity.monster.EntityZombieVillager.func_184206_a(EntityZombieVillager.java:319)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(SourceFile:125)
	at net.minecraft.entity.monster.EntityZombieVillager.func_190733_a(EntityZombieVillager.java:55)
	at net.minecraft.entity.monster.EntityZombie.func_70074_a(EntityZombie.java:409)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1172)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:536)
	at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntityZombieVillager.func_70071_h_(EntityZombieVillager.java:121)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

This issue has probably been reported before, but just confirming this is an issue with I/F and not with MCA.

**Comment by AlexModGuy** [comment]
tried to reproduce in 1.5.0 with normal villagers, no issues. but since

>  at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)

is in this code i assume its caused by MCA
