### ISSUE TITLE
Problem with converting Int to Bool while checking if Hippogryph is hovering

### ISSUE THREAD

**Issue by taterdzai** [Alex-the-666/Ice_and_Fire#724]
There is crash report on client side:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-81.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-82-core.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 6/5/18 9:53 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isHovering(EntityHippogryph.java:459)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:764)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:857)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isHovering(EntityHippogryph.java:459)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:764)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:857)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: iceandfire:hippogryph (com.github.alexthe666.iceandfire.entity.EntityHippogryph)
	Entity ID: 63491
	Entity Name: Hippogryph
	Entity's Exact location: 105.17, 78.98, 2504.91
	Entity's Block location: World: (105,78,2504), Chunk: (at 9,4,8 in 6,156; contains blocks 96,0,2496 to 111,255,2511), Region: (0,4; contains chunks 0,128 to 31,159, blocks 0,0,2048 to 511,255,2559)
	Entity's Momentum: 0.37, -0.07, -0.14
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['iliayar'/63399, l='MpServer', x=164.84, y=63.00, z=2494.81]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (112,64,256), Chunk: (at 0,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 28273415 game time, 30661364 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 113 total; [EntityPlayerSP['iliayar'/63399, l='MpServer', x=164.84, y=63.00, z=2494.81], EntityXPOrb['Experience Orb'/63488, l='MpServer', x=81.02, y=71.00, z=2538.47], EntityZombie['Zombie'/63489, l='MpServer', x=95.76, y=28.00, z=2561.48], EntityBat['Bat'/63490, l='MpServer', x=85.69, y=27.51, z=2563.59], EntityHippogryph['Hippogryph'/63491, l='MpServer', x=105.17, y=78.98, z=2504.91], EntityZombie['Zombie'/63494, l='MpServer', x=106.50, y=17.00, z=2443.50], EntityDeer['Deer'/63496, l='MpServer', x=111.96, y=63.00, z=2450.10], EntityBat['Bat'/63504, l='MpServer', x=104.05, y=38.00, z=2483.53], EntitySquid['Squid'/63505, l='MpServer', x=116.51, y=60.40, z=2472.02], EntitySquid['Squid'/63506, l='MpServer', x=132.60, y=61.00, z=2496.60], EntityBat['Bat'/63507, l='MpServer', x=95.02, y=34.12, z=2499.62], EntityDeer['Deer'/63508, l='MpServer', x=101.50, y=67.00, z=2501.00], EntityBat['Bat'/63509, l='MpServer', x=113.44, y=19.10, z=2434.25], EntitySheep['Sheep'/63510, l='MpServer', x=123.25, y=63.00, z=2456.37], EntityCreeper['Creeper'/63511, l='MpServer', x=116.52, y=30.00, z=2546.20], EntityCreeper['Creeper'/63512, l='MpServer', x=123.21, y=27.00, z=2552.42], EntityZombie['Zombie'/63513, l='MpServer', x=115.28, y=14.00, z=2569.47], EntityDeer['Deer'/63514, l='MpServer', x=112.63, y=63.00, z=2505.96], EntityDeer['Deer'/63515, l='MpServer', x=114.20, y=63.00, z=2506.51], EntityDeer['Deer'/63516, l='MpServer', x=113.65, y=64.00, z=2510.09], EntityZombie['Zombie'/63517, l='MpServer', x=96.21, y=17.00, z=2526.50], EntityDeer['Deer'/63518, l='MpServer', x=110.76, y=71.00, z=2545.92], EntityDeer['Deer'/63519, l='MpServer', x=113.04, y=67.00, z=2527.50], EntityDeer['Deer'/63520, l='MpServer', x=117.63, y=63.00, z=2519.44], EntityDeer['Deer'/63521, l='MpServer', x=113.50, y=65.00, z=2524.50], EntitySkeleton['Skeleton'/63525, l='MpServer', x=124.50, y=38.00, z=2430.50], EntitySheep['Sheep'/63543, l='MpServer', x=135.24, y=66.00, z=2431.45], EntitySheep['Sheep'/63544, l='MpServer', x=131.50, y=65.00, z=2422.73], EntitySkeleton['Skeleton'/63545, l='MpServer', x=135.75, y=63.00, z=2532.51], EntitySquid['Squid'/63546, l='MpServer', x=132.60, y=61.00, z=2495.28], EntityBat['Bat'/63547, l='MpServer', x=134.70, y=36.41, z=2496.78], EntitySquid['Squid'/63548, l='MpServer', x=140.32, y=62.54, z=2497.28], EntitySquid['Squid'/63549, l='MpServer', x=135.45, y=62.00, z=2505.83], EntityCreeper['Creeper'/63560, l='MpServer', x=156.24, y=58.00, z=2563.25], EntitySkeleton['Skeleton'/63561, l='MpServer', x=155.40, y=58.00, z=2563.96], EntitySkeleton['Skeleton'/63562, l='MpServer', x=157.56, y=57.00, z=2570.25], EntitySheep['Sheep'/63564, l='MpServer', x=161.23, y=69.00, z=2441.64], EntityBrainyZombie['Angry Zombie'/63565, l='MpServer', x=152.43, y=17.00, z=2534.30], EntityDeer['Deer'/63566, l='MpServer', x=147.11, y=63.00, z=2537.27], EntityCreeper['Creeper'/63567, l='MpServer', x=157.50, y=12.00, z=2523.50], EntityZombie['Zombie'/63568, l='MpServer', x=149.45, y=29.00, z=2476.26], EntityCreeper['Creeper'/63577, l='MpServer', x=172.50, y=18.00, z=2565.50], EntityAncientGolem['Ancient Golem'/63580, l='MpServer', x=188.26, y=20.00, z=2526.59], EntityDeer['Deer'/63581, l='MpServer', x=189.50, y=71.00, z=2525.50], EntityZombie['Zombie'/63582, l='MpServer', x=189.50, y=16.00, z=2496.50], EntityBat['Bat'/63583, l='MpServer', x=186.47, y=12.84, z=2514.65], EntityBrainyZombie['Angry Zombie'/63584, l='MpServer', x=160.46, y=15.00, z=2546.22], EntityCreeper['Creeper'/63585, l='MpServer', x=174.50, y=39.00, z=2552.50], EntityDeer['Deer'/63586, l='MpServer', x=175.73, y=73.00, z=2555.12], EntityDeer['Deer'/63588, l='MpServer', x=175.70, y=65.00, z=2545.82], EntityBrainyZombie['Angry Zombie'/63598, l='MpServer', x=164.50, y=22.00, z=2520.50], EntityDeer['Deer'/63599, l='MpServer', x=190.50, y=64.00, z=2453.50], EntityDeer['Deer'/63600, l='MpServer', x=184.50, y=66.00, z=2459.00], EntityDeer['Deer'/63608, l='MpServer', x=178.50, y=65.00, z=2549.98], EntityDeer['Deer'/63609, l='MpServer', x=177.98, y=64.00, z=2551.50], EntityDeer['Deer'/63610, l='MpServer', x=202.50, y=73.00, z=2528.00], EntityDeer['Deer'/63611, l='MpServer', x=196.49, y=78.90, z=2535.89], EntityBat['Bat'/63612, l='MpServer', x=188.43, y=21.10, z=2569.25], EntitySpider['Spider'/63613, l='MpServer', x=187.01, y=41.00, z=2563.38], EntitySkeleton['Skeleton'/63614, l='MpServer', x=187.90, y=41.00, z=2562.19], EntityCreeper['Creeper'/63615, l='MpServer', x=176.50, y=64.00, z=2562.78], EntityDeer['Deer'/63616, l='MpServer', x=193.14, y=74.00, z=2546.98], EntityDeer['Deer'/63617, l='MpServer', x=202.86, y=82.00, z=2551.73], EntityZombie['Zombie'/63618, l='MpServer', x=207.47, y=11.00, z=2516.59], EntityWitch['Witch'/63619, l='MpServer', x=194.50, y=13.00, z=2521.69], EntityAncientGolem['Ancient Golem'/63620, l='MpServer', x=204.51, y=20.00, z=2527.21], EntityDeer['Deer'/63621, l='MpServer', x=195.50, y=70.00, z=2525.50], EntityDeer['Deer'/63622, l='MpServer', x=193.50, y=70.00, z=2525.50], EntitySkeleton['Skeleton'/63623, l='MpServer', x=203.50, y=19.00, z=2500.50], EntityZombie['Zombie'/63624, l='MpServer', x=193.80, y=50.00, z=2505.51], EntityBat['Bat'/63625, l='MpServer', x=198.51, y=51.18, z=2505.47], EntityZombie['Zombie'/63626, l='MpServer', x=200.43, y=51.00, z=2499.79], EntityEnderman['Enderman'/63628, l='MpServer', x=206.45, y=15.00, z=2564.71], EntityWitch['Witch'/63631, l='MpServer', x=200.77, y=12.00, z=2466.49], EntityZombie['Zombie'/63632, l='MpServer', x=195.51, y=13.00, z=2466.22], EntityWitch['Witch'/63633, l='MpServer', x=201.73, y=14.00, z=2468.53], EntityCreeper['Creeper'/63634, l='MpServer', x=205.79, y=25.00, z=2475.47], EntityDeer['Deer'/63636, l='MpServer', x=219.93, y=81.00, z=2525.85], EntityDeer['Deer'/63637, l='MpServer', x=223.36, y=76.00, z=2536.50], EntityDeer['Deer'/63638, l='MpServer', x=214.50, y=79.00, z=2534.01], EntityZombie['Zombie'/63639, l='MpServer', x=218.50, y=13.00, z=2471.50], EntityZombie['Zombie'/63640, l='MpServer', x=212.26, y=13.00, z=2467.51], EntityCreeper['Creeper'/63641, l='MpServer', x=217.53, y=40.00, z=2466.37], EntitySkeleton['Skeleton'/63642, l='MpServer', x=217.50, y=17.00, z=2508.50], EntityZombie['Zombie'/63646, l='MpServer', x=221.50, y=28.00, z=2552.50], EntityCreeper['Creeper'/63647, l='MpServer', x=220.50, y=29.00, z=2549.50], EntityDeer['Deer'/63649, l='MpServer', x=212.18, y=85.00, z=2554.00], EntitySkeleton['Skeleton'/63654, l='MpServer', x=216.70, y=44.23, z=2449.50], EntitySkeleton['Skeleton'/63655, l='MpServer', x=217.77, y=41.00, z=2456.52], EntityChicken['Chicken'/63660, l='MpServer', x=225.59, y=69.00, z=2414.22], EntityDeer['Deer'/63663, l='MpServer', x=226.65, y=75.00, z=2501.89], EntityBat['Bat'/63665, l='MpServer', x=232.41, y=21.23, z=2488.82], EntityDeer['Deer'/63666, l='MpServer', x=224.96, y=73.00, z=2493.89], EntitySkeleton['Skeleton'/63667, l='MpServer', x=225.26, y=17.00, z=2518.46], EntityDeer['Deer'/63668, l='MpServer', x=224.28, y=81.00, z=2527.95], EntityBat['Bat'/63669, l='MpServer', x=241.75, y=42.92, z=2451.25], EntityDeer['Deer'/63671, l='MpServer', x=224.35, y=68.00, z=2458.08], EntityDeer['Deer'/63674, l='MpServer', x=224.50, y=77.00, z=2537.50], EntityDeer['Deer'/63677, l='MpServer', x=224.13, y=67.00, z=2438.77], EntityXPOrb['Experience Orb'/63432, l='MpServer', x=63.11, y=47.00, z=2579.88], EntityXPOrb['Experience Orb'/63433, l='MpServer', x=61.47, y=47.00, z=2578.41], EntityXPOrb['Experience Orb'/63459, l='MpServer', x=65.27, y=46.00, z=2579.88], EntityBat['Bat'/63464, l='MpServer', x=86.80, y=15.37, z=2416.07], EntityItem['item.tile.sand.default'/63725, l='MpServer', x=150.88, y=62.00, z=2491.13], EntityItem['item.tile.sand.default'/63726, l='MpServer', x=150.13, y=62.00, z=2492.88], EntitySpider['Spider'/63471, l='MpServer', x=99.60, y=25.00, z=2420.98], EntityDeer['Deer'/63481, l='MpServer', x=109.59, y=62.15, z=2479.14], EntitySquid['Squid'/63482, l='MpServer', x=102.23, y=61.00, z=2475.69], EntitySquid['Squid'/63483, l='MpServer', x=102.65, y=62.47, z=2472.35], EntitySquid['Squid'/63484, l='MpServer', x=104.19, y=61.20, z=2473.59], EntitySquid['Squid'/63485, l='MpServer', x=107.84, y=60.50, z=2475.76], EntitySquid['Squid'/63486, l='MpServer', x=113.97, y=60.00, z=2475.97], EntitySquid['Squid'/63487, l='MpServer', x=111.74, y=60.56, z=2472.08]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1083967120 bytes (1033 MB) / 2197815296 bytes (2096 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_D2 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                      | Signature                                |
	|:------ |:-------------------- |:------------------------ |:------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2                   | minecraft.jar                               | None                                     |
	| UCHIJA | mcp                  | 9.42                     | minecraft.jar                               | None                                     |
	| UCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.3.2655-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.3.2655             | forge-1.12.2-14.23.3.2655-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | advancedrocketrycore | 1                        | minecraft.jar                               | None                                     |
	| UCHIJA | libvulpes            | 0.2.8.-31                | LibVulpes-1.12.2-0.2.8-31-universal.jar     | None                                     |
	| UCHIJA | advancedrocketry     | 1.4.0.-81                | AdvancedRocketry-1.12.2-1.4.0-81.jar        | None                                     |
	| UCHIJA | appliedenergistics2  | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar       | None                                     |
	| UCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                      | None                                     |
	| UCHIJA | crafttweaker         | 4.1.8                    | CraftTweaker2-1.12-4.1.8.jar                | None                                     |
	| UCHIJA | astralsorcery        | 1.8.9                    | astralsorcery-1.12.2-1.8.9.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJA | psi                  | r1.1-59                  | Psi-r1.1-59.jar                             | None                                     |
	| UCHIJA | autoreglib           | 1.3-16                   | AutoRegLib-1.3-16.jar                       | None                                     |
	| UCHIJA | guideapi             | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                 | None                                     |
	| UCHIJA | bloodmagic           | 1.12.2-2.2.11-96         | BloodMagic-1.12.2-2.2.11-96.jar             | None                                     |
	| UCHIJA | thaumcraft           | 6.1.BETA16               | Thaumcraft-1.12.2-6.1.BETA16.jar            | None                                     |
	| UCHIJA | botania              | r1.10-354                | Botania+r1.10-354.jar                       | None                                     |
	| UCHIJA | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.8.jar                | None                                     |
	| UCHIJA | jei                  | 4.9.1.168                | jei_1.12.2-4.9.1.168.jar                    | None                                     |
	| UCHIJA | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.8.jar                | None                                     |
	| UCHIJA | durabilityshow       | 5.0.0                    | Durability+Show-1.12-5.0.0.jar              | None                                     |
	| UCHIJA | embers               | 0.230                    | embers-0.230.jar                            | None                                     |
	| UCHIJA | fastbench            | 1.3.2                    | FastWorkbench-1.12.2-1.3.2.jar              | None                                     |
	| UCHIJA | waila                | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                   | None                                     |
	| UCHIJA | llibrary             | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                   | None                                     |
	| UCHIJA | iceandfire           | 1.4.0                    | iceandfire-1.4.0-1.12.2.jar                 | None                                     |
	| UCHIJA | immersiveengineering | 0.12-82                  | ImmersiveEngineering-0.12-82.jar            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJA | immersivecables      | 1.3.0                    | ImmersiveCables-1.12.2-1.3.0.jar            | None                                     |
	| UCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | morpheus             | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                     | None                                     |
	| UCHIJA | reborncore           | 3.8.3.279                | RebornCore-1.12.2-3.8.3.279-universal.jar   | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJA | roots                | 0.104                    | roots-2-0.104.jar                           | None                                     |
	| UCHIJA | stevescarts          | 2.4.19.95                | StevesCarts-1.12.2-2.4.19.95.jar            | None                                     |
	| UCHIJA | torohealthmod        | 1.12.2-11                | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar | None                                     |
	| UCHIJA | bspkrscore           | at_0.9                   | Treecapitator-1.12-at_0.9a.jar              | None                                     |
	| UCHIJA | treecapitator        | at_0.9                   | Treecapitator-1.12-at_0.9a.jar              | None                                     |
	| UCHIJA | wanionlib            | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                    | None                                     |
	| UCHIJA | xaerominimap         | 1.15                     | Xaeros_Minimap_FP1.15_Forge_1.12.jar        | None                                     |
	| UCHIJA | unidict              | 1.12.2-2.5c              | UniDict-1.12.2-2.5c.jar                     | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.9.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-81.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-82-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.677.257' Renderer: 'AMD Radeon (TM) R7 360 Series'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.8.3.279
		Runtime Debofucsation 1
		RenderEngine: 1
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R7 360 Series GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13492 Compatibility Profile Context 22.19.677.257
	OpenGlRenderer: AMD Radeon (TM) R7 360 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

**Comment by AlexModGuy** [comment]
#740
