### ISSUE TITLE
It crashes when you try to ride anything on a multiplayer server.

### ISSUE THREAD

**Issue by BlueYoshi68** [Alex-the-666/Ice_and_Fire#737]
`Time: 6/9/18 2:54 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
	at com.github.alexthe666.iceandfire.entity.EntityHippocampus.up(EntityHippocampus.java:263)
	at com.github.alexthe666.iceandfire.entity.EntityHippocampus.func_70636_d(EntityHippocampus.java:231)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

(It crashes after a few minutes/seconds of riding anything)

**Comment by AlexModGuy** [comment]
#740
