### ISSUE TITLE
1.4.0-1.5.0 Thaumcraft ClassCastException Megathread

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/Ice_and_Fire#740]
This issue has has been fixed on our side, and is mainly caused by thaumcraft. But due to how frequently reported it is, all issues will be redirected here

**Comment by mser7** [comment]
Snow Villagers were crashing due to there is no zombie snow villagers

**Comment by CombatZAK** [comment]
> Snow Villagers were crashing due to there is no zombie snow villagers

This sounds like it might be a different problem that might need to be tracked separately if not already fixed.

**Comment by taterdzai** [comment]
Temporary fix for anyone who wants to keep playing - reduce hippogryphSpawnRate in config to 0. Obviously there will be no hippogryphs while it's being fixed

**Comment by ProsperCraft** [comment]
Actually - 
hippocampi {
    # True if hippocampi are allowed to spawn.
    B:spawnHippocampus=false

**Comment by AlexModGuy** [comment]
this is largly due to thaumcraft and other similar mobs registering DataParameters incorrectly.
See https://github.com/Azanor/thaumcraft-beta/issues/1017

**Comment by renadi** [comment]
Any chance this is a related issue?

```
java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
    at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:125)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2350)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at com.github.alexthe666.iceandfire.entity.EntityPixie.onLivingUpdate(EntityPixie.java:218)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2170)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.redirect$updateEntity$zba000(World.java:4114)
    at net.minecraft.world.World.updateEntities(World.java:1756)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

....

-- Entity being ticked --
  Entity Type: iceandfire:if_pixie (com.github.alexthe666.iceandfire.entity.EntityPixie)
  Entity ID: 30214
  Entity Name: Pixie
  Entity's Exact location: 131.50, 101.00, -469.50
  Entity's Block location: World: (131,101,-470), Chunk: (at 3,6,10 in 8,-30; contains blocks 128,0,-480 to 143,255,-465), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{},Sitting:0b,Attributes:[{Base:-2.0d,Name:"tc.mobmod"},{Base:0.0d,Name:"tc.mobmodtaint"},{Base:1.0d,Name:"generic.physicalDamageRate"},{Base:1.0d,Name:"generic.fireDamageRate"},{Base:0.0d,Name:"generic.fireAspect"},{Base:1.0d,Name:"generic.barehandedPower"},{Base:10.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.25d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:16.0d,Name:"generic.followRange"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,InLove:0,DeathTime:0s,ForgeCaps:{"dsurround:emojidata":{as:0,es:0,et:0},"llibrary:extendedentitydatacapability":{"Ice And Fire - Chicken Property Tracker":{TimeUntilNextEgg:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}}},HandDropChances:[0.0f,0.085f],PersistenceRequired:0b,Age:0,Motion:[0.0d,0.0d,0.0d],Leashed:0b,UUIDLeast:-6617315810901565092L,Health:10.0f,Color:4,LeftHanded:0b,Air:300s,OnGround:0b,Dimension:0,Rotation:[81.0f,0.0f],UpdateBlocked:0b,HandItems:[{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"thermalfoundation:armor.boots_copper",Count:1b,Damage:0s},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],OwnerUUID:"",UUIDMost:4039456909224659086L,Pos:[131.5d,101.0d,-469.5d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

```
https://paste.dimdev.org/adagacasog.mccrash

**Comment by AlexModGuy** [comment]
No that is #401

**Comment by AlexModGuy** [comment]
Fixed in BETA 17 of Thaumcraft
