### ISSUE TITLE
Spawns crashing client

### ISSUE THREAD

**Issue by DEX47** [Alex-the-666/Ice_and_Fire#812]
I just updated my server with your latest Ice and Fire. I ventured off to find one of your new mobs and it didn't take long to find one. Unfortunately the only evidence of the mob is the crash log below.

Forge: 14.23.4.2705
Ice&Fire: 1.12.3-1.5.0
LLibrary: 1.7.14-1.12.2
Thaumcraft: 1.12.2-3.7.424
```

> java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
> 	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.hasTargetedEntity(EntityCockatrice.java:193)
> 	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.getTargetedEntity(EntityCockatrice.java:231)
> 	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.func_70636_d(EntityCockatrice.java:493)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
> 	at net.minecraft.world.World.func_72866_a(World.java:1990)
> 	at net.minecraft.world.World.func_72870_g(World.java:1952)
> 	at net.minecraft.world.World.func_72939_s(World.java:1756)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.hasTargetedEntity(EntityCockatrice.java:193)
> 	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.getTargetedEntity(EntityCockatrice.java:231)
> 	at com.github.alexthe666.iceandfire.entity.EntityCockatrice.func_70636_d(EntityCockatrice.java:493)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
> 	at net.minecraft.world.World.func_72866_a(World.java:1990)
> 	at net.minecraft.world.World.func_72870_g(World.java:1952)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: iceandfire:if_cockatrice (com.github.alexthe666.iceandfire.entity.EntityCockatrice)
> 	Entity ID: 18143
> 	Entity Name: Cockatrice
> 	Entity's Exact location: 3369.24, 86.00, 923.84
> 	Entity's Block location: World: (3369,86,923), Chunk: (aat 9,5,11 in 210,57; contains blocks 3360,0,912 to 3375,255,927), Region: (6,1; contains chunks 192,32 to 223,63, blocks 3072,0,512 to 3583,255,1023)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1756)

```

**Comment by DEX47** [comment]
Looks like there is an existing thread with this issue.. closing and adding to the other one.
