### ISSUE TITLE
Statues not placeable

### ISSUE THREAD

**Issue by Natrukei** [Alex-the-666/Ice_and_Fire#941]
I'm playing the newest Version of the FTB Direwolf 20 pack plus a few other mods (including Ice and Fire)
And I can't place any statue that I mined. When I place this, the server I'm playing this on is spitting out the following message and after relogging I get the Statue back in my inventory.

[19:28:50] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.EntityList.func_90035_a(I)Ljava/lang/Class;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityList.func_90035_a(I)Ljava/lang/Class;
	at com.github.alexthe666.iceandfire.item.ItemStoneStatue.func_180614_a(ItemStoneStatue.java:82) ~[ItemStoneStatue.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:876) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by AlexModGuy** [comment]
@Natrukei what entity where you trying to place

**Comment by Natrukei** [comment]
Stone Statues created by the Gorgon/Gorgon Head

Dragon, Bat, Zombie particularly. Wanted to build my own Stone-Garden

**Comment by Natrukei** [comment]
Bats are understandable because the statues are still flying and moving up/down, but the zombie was interesting

**Comment by AlexModGuy** [comment]
will be fixed in 1.5.2
