### ISSUE TITLE
Client crash after ClassCastException in EntityHippogryph.isHovering

### ISSUE THREAD

**Issue by Ztruwwel** [Alex-the-666/Ice_and_Fire#963]
Great modpack, unfortunately my client now always crashes on login, stack:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isHovering(EntityHippogryph.java:480)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70636_d(EntityHippogryph.java:801)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.func_70071_h_(EntityHippogryph.java:894)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)

**Comment by AlexModGuy** [comment]
Update Thaumcraft
