### ISSUE TITLE
Pixie Hovels Crashing Clientside

### ISSUE THREAD

**Issue by RTT3000** [Alex-the-666/Ice_and_Fire#972]
I have this mod on my Server and it crashes the client if i place one on the ground and break it. Is there a fix for this?

Minecraft: 1.12.2

Mods i use on the server:

Forge.
Biome Bundle
Custom Mob Spawner
MoCreatures
HarvestCraft
Ice And Fire
LLibrary 1.12.2
OTG
OTG Core
Placeable Items
RikMuldsCore
TheCampingMod

Crash Log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (Better-Foliage-Mod-1.12.1.jar)
  ItemPatchingLoader (ItemPhysic-Mod-Lite-1.12.2.jar)
  OTGASMPlugin (OTG-Core.jar)
  llibrary (LLibrary-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/25/18 8:54 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.render(RenderPixieHouse.java:36)
	at com.github.alexthe666.iceandfire.client.render.tile.RenderPixieHouse.func_192841_a(RenderPixieHouse.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1011)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:374)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4390)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1593)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by RTT3000** [comment]
Server crash log:
Ice and Fire loaded a new chunk (-49, 254  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by AlexModGuy** [comment]
fixed
